import {notFound} from "next/navigation";import AdminLayout from "@/app/admin/_components/AdminLayout";import {buildPilotWorkspace,canonicalPilotId} from "@/lib/intelligence/pilot-workspace";import PilotIntake from "./pilot-intake";import PilotReviewOperations from "./pilot-review-operations";
const S={card:{background:"#fff",border:"1px solid #e2e8f0",borderRadius:12,padding:16,marginBottom:14} as const,grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))",gap:10} as const,pill:{display:"inline-block",padding:"3px 8px",borderRadius:99,background:"#eef2ff",color:"#3730a3",fontSize:12} as const};
export default function PilotWorkspacePage({params}:{params:{pilotId:string}}){if(!canonicalPilotId(params.pilotId))notFound();const w=buildPilotWorkspace();return <AdminLayout>
 <header style={S.card}><span style={S.pill}>Internal pilot workspace</span><h1>{w.pilot.client_name}</h1><p>{w.overview.diagnosis}</p><nav><a href="#context">Client Context</a>{" · "}<a href="#accounts">Accounts</a>{" · "}<a href="#theses">Theses</a>{" · "}<a href="#feasibility">Feasibility</a>{" · "}<a href="#readiness">Report Readiness</a>{" · "}<a href="#activity">Activity</a></nav></header>
 <section style={S.card}><h2>Pilot Overview</h2><div style={S.grid}>{[["Status",w.pilot.status],["Context",`${w.overview.context_completeness}%`],["Accounts",w.overview.accounts],["Theses",w.overview.theses],["Reviewed",w.overview.reviewed],["Signals",w.overview.signals],["Critical blockers",w.overview.critical_blockers],["Customer-safe",w.overview.customer_safe]].map(([k,v])=><div key={String(k)}><small>{k}</small><strong style={{display:"block"}}>{v}</strong></div>)}</div><p><strong>Next action:</strong> {w.overview.next_action}</p></section>
 <section id="context" style={S.card}><h2>Client Context · {w.questions.length} unanswered questions</h2><PilotIntake pilotId={w.pilot.pilot_id} questions={w.questions}/></section>
 <section id="accounts" style={S.card}><h2>Account Comparison · {w.accounts.length}</h2><div style={{overflowX:"auto"}}><table><thead><tr><th>Account</th><th>Decision</th><th>Segment</th><th>Client fit</th><th>Accessibility</th><th>Feasibility</th><th>Timing</th><th>Safety</th><th>Main blocker</th></tr></thead><tbody>{w.accounts.map((a:any)=><tr key={a.account_id}><td><strong>{a.account_name}</strong><br/><a href={`https://${a.domain}`} target="_blank">{a.domain}</a></td><td>{a.decision}</td><td>{a.segment}</td><td>{a.confidence.client_fit}</td><td>{a.confidence.accessibility}</td><td>insufficient_context</td><td>{a.why_now.state}</td><td>{a.safety?.state}</td><td>{a.confidence.limiting_factor}</td></tr>)}</tbody></table></div></section>
 <section id="theses" style={S.card}><h2>Opportunity Theses & Review Queue</h2>{w.accounts.map((a:any)=><details key={a.thesis_id}><summary><strong>{a.account_name}</strong> · {a.decision} · {a.review_state}</summary><p>{a.opportunity_statement}</p><p><strong>Why now:</strong> {a.why_now.statement}</p><p><strong>Why not now:</strong> {a.why_not_now.join(" ")}</p><p><strong>Use case:</strong> {a.use_cases[0]?.statement}</p><p><strong>Buying path:</strong> {a.buying_path.category_owner.role} ({a.buying_path.category_owner.state})</p><p><strong>Alternative:</strong> {a.counterevidence.alternative_explanation}</p><p>Review actions remain internal and history-preserving; context must be accepted before recalculation.</p></details>)}</section>
 <section id="review" style={S.card}><h2>Review Operations</h2><PilotReviewOperations pilotId={w.pilot.pilot_id} theses={w.theses}/></section>
 <section id="feasibility" style={S.card}><h2>Commercial Feasibility</h2>{w.feasibility.map((f:any)=><details key={f.account_id}><summary>{w.accounts.find((a:any)=>a.account_id===f.account_id)?.account_name} · insufficient context</summary><ul>{f.dimensions.map((d:any)=><li key={d.dimension}><strong>{d.dimension}:</strong> {d.state} — {d.blocker} Next: {d.next_verification}</li>)}</ul></details>)}</section>
 <section style={S.card}><h2>Evidence, Research & Signals</h2><p>Identity profiles: 6 verified. Current valid signals: 0. Structural relevance does not establish timing. No raw provider payload or secret is exposed.</p><p>Provider health and detailed research operations remain available from the Intelligence Command Center source and signal panels.</p></section>
 <section id="readiness" style={S.card}><h2>Report Readiness</h2><p><strong>Final report generation remains disabled until required readiness and review gates pass.</strong></p>{w.sections.map((x:any)=><div key={x.section}><strong>{x.section}</strong> · {x.state}{x.missing_context.length?` · missing: ${x.missing_context.join(", ")}`:""}</div>)}</section>
 <section style={S.card}><h2>Pilot Operating Checklist</h2><ol>{w.checklist.map(x=><li key={x.step}><strong>{x.label}</strong> · {x.status}{x.blocker?` — ${x.blocker}`:""}</li>)}</ol></section>
 <section id="activity" style={S.card}><h2>Pilot Activity</h2>{w.activity.map((x,i)=><p key={`${x.event_type}:${i}`}><strong>{x.event_type}</strong> · {x.timestamp} · {x.summary}</p>)}</section>
 </AdminLayout>}
