import type{PilotWorkspace}from"@/lib/intelligence/pilot-workspace";import styles from"./workspace.module.css";
const List=({items}:{items:readonly string[]})=><ol>{items.map(x=><li key={x}>{x}</li>)}</ol>;
export default function PilotSearchBlueprint({workspace}:{workspace:PilotWorkspace}){const b=workspace.searchBlueprint,w=workspace.whatChanged;return <div className={styles.contextReview}>
 <section className={styles.successContract}><span>SEARCH BLUEPRINT V{b.version} · {b.approval_state.toUpperCase()}</span><h3>Decisión comercial para los próximos 90–180 días</h3><p>{b.commercial_objective}</p><small>Vinculado a contexto <code>{b.context_id}</code> V{b.context_version}. Mayor potencial comercial relativo; no es probabilidad de compra ni promesa de ventas. Ninguna consulta ha sido ejecutada.</small>
  <div className={styles.contextColumns}><section><h3>Rutas prioritarias</h3><List items={[b.routes.priority_1,b.routes.priority_2,b.routes.priority_3]}/><h3>Exploratoria</h3><p>{b.routes.exploratory}</p></section><section><h3>Diferidas</h3><List items={b.routes.deferred}/><h3>Geografía</h3><p>{b.geography.primary}: descubrimiento nacional; pedidos pequeños distantes condicionados por flete.</p></section></div>
  <details><summary>Reglas de inclusión, exclusión y condicionamiento</summary><div className={styles.contextColumns}><section><h3>Inclusión trazable</h3><ol>{b.inclusion_rules.map(x=><li key={x.rule}>{x.rule}<small>{x.source} · {x.confidence} · {x.affected_route}</small></li>)}</ol></section><section><h3>Exclusión</h3><List items={b.exclusion_rules}/><small>{b.exclusion_boundary}</small><h3>Condicionamiento</h3><List items={b.conditioning_rules}/></section></div></details>
  <details><summary>Arquetipos, ladder y tolerancia de procurement</summary><div className={styles.reviewAnswerList}>{b.account_archetypes.map(x=><article className={styles.reviewAnswer} key={x.account_type}><h4>{x.account_type}</h4><p>{x.why_fit}</p><small>{x.use_case} · {x.initial_order} · procurement {x.procurement}</small><p><strong>Riesgo:</strong> {x.primary_risk}</p><p><strong>Evidencia:</strong> {x.evidence_required}</p></article>)}</div><div className={styles.contextColumns}><section><h3>Tamaños compatibles</h3><ol>{b.account_size_ladder.map(x=><li key={x.tier}><strong>Tier {x.tier} · {x.label}:</strong> {x.range} — {x.state}</li>)}</ol></section><section><h3>Favorecer</h3><List items={b.procurement_tolerance.favor}/><h3>Depriorizar</h3><List items={b.procurement_tolerance.deprioritize}/></section></div></details>
  <details><summary>{b.query_hypotheses.length} hipótesis de consulta — diseñadas, no ejecutadas</summary><div className={styles.reviewAnswerList}>{b.query_hypotheses.map(x=><article className={styles.reviewAnswer} key={x.id}><h4>{x.route} · {x.account_archetype}</h4><p>{x.hypothesis}</p><small>{x.geography} · Evidencia: {x.expected_evidence} · Stop: {x.stop_condition}</small></article>)}</div><h3>Stop rules</h3><List items={b.stop_rules}/></details>
 </section>
 <section className={styles.impactPreview}><header><span>INTERNAL REVIEW · BASELINE PRESERVADO</span><h3>Recalibración de seis cuentas</h3><p>Timing separado; ninguna cuenta está ACT NOW porque no existe señal temporal fresca.</p></header><div>{workspace.recalibratedTheses.map(x=><article key={x.thesis_id}><div><h4>{x.account_name}</h4><em data-direction={x.decision==="raise"?"strengthen":x.decision==="lower"?"weaken":"uncertain"}>{x.actionability}</em></div><p>{x.recalibrated_thesis}</p><small><strong>Cambio:</strong> {x.decision} · antes {x.baseline.recommendation}</small><small><strong>Uso:</strong> {x.strongest_use_case}</small><small><strong>Riesgo:</strong> {x.main_risk}</small><small><strong>Buyer path:</strong> {x.buyer_path_hypothesis.roles}</small><small><strong>Validar:</strong> {x.validation_required}</small></article>)}</div></section>
 <section className={styles.successContract}><span>WHAT CHANGED · V1 → V2</span><h3>Cambio de portafolio</h3><div className={styles.contextColumns}><section><h3>Retail y hospitalidad</h3><p>{w.portfolio.retail}</p><p>{w.portfolio.hospitality}</p><p>{w.portfolio.gifting}</p></section><section><h3>Distribución y límites</h3><p>{w.portfolio.distribution}</p><p>{w.portfolio.capacity}</p><p>{w.portfolio.geography}</p><p>{w.portfolio.evidence}</p></section></div><small>Requiere aprobación del fundador. Phase 4 continúa bloqueada.</small></section>
 </div>}
