// Discovery Engine V2.2 — explainable Colombia market coverage.
// This module adds breadth knowledge around the V1/V2/V2.1 engine. Registration
// is not proof: breadth and depth remain deliberately separate.
import { buildLiveBenchmark } from "./live";

export type CoverageBreadth = "none" | "weak" | "partial" | "good" | "strong";
export type CoverageDepth = "untested" | "hypothesized" | "manually_validated" | "benchmarked" | "multi_benchmark" | "historically_effective";
export type AtlasConfidence = "discovered" | "hypothesized" | "manually_validated" | "benchmarked" | "multi_benchmark" | "historically_effective" | "degraded" | "unreliable" | "deprecated";
export type OperationalAccessibility = "direct_access" | "provider_accessible" | "structured_endpoint" | "parser_required" | "javascript_heavy" | "pagination_complex" | "rate_limited" | "authentication_required" | "manually_accessible_only" | "blocked" | "unstable" | "inaccessible" | "operationally_unsuitable";

export interface DiscoveryCluster {
  id: string; name: string; importance: "high" | "medium"; labels: string[]; subindustries: string[];
  business_models: string[]; routes: string[]; mechanisms: string[];
}

export const COLOMBIA_PRIORITY_CLUSTERS: DiscoveryCluster[] = [
  { id:"manufacturing", name:"Manufacturing / Industrial", importance:"high", labels:["manufacturing"], subindustries:["food_manufacturing","beverage_manufacturing","packaging","chemicals","metalworking","construction_materials","cosmetics","pharmaceutical_manufacturing","automotive_parts"], business_models:["manufacturer","exporter","wholesaler"], routes:["procurement","private_label","channel_distribution"], mechanisms:["supplier_addition","procurement_replacement"] },
  { id:"retail", name:"Retail / Ecommerce", importance:"high", labels:["specialty_retail","ecommerce","multi_brand_retail"], subindustries:["beauty_retail","food_retail","home_retail","fashion_retail","premium_retail"], business_models:["retailer","ecommerce_store","chain_operator","marketplace","reseller"], routes:["retail_listing","ecommerce_listing","wholesale_distribution"], mechanisms:["product_listing","resale"] },
  { id:"hospitality", name:"Hospitality / Tourism", importance:"high", labels:["hospitality","tourism","hotels","spa"], subindustries:["boutique_hospitality","resorts","wellness_hospitality"], business_models:["hotel_operator","hospitality_group","spa_operator"], routes:["hospitality_guest_experience","spa_integration","procurement"], mechanisms:["guest_amenity","spa_ritual","supplier_addition"] },
  { id:"technology", name:"Technology / Software", importance:"high", labels:["technology"], subindustries:["software","saas","fintech","healthtech","edtech","logistics_tech","cybersecurity","ai","it_services"], business_models:["saas_vendor","software_vendor","managed_service_provider","systems_integrator","consultancy"], routes:["saas_purchase","service_contract","strategic_partnership"], mechanisms:["supplier_addition","partnership_bundle"] },
  { id:"professional_services", name:"Professional Services", importance:"medium", labels:["professional_services"], subindustries:["consulting","legal","accounting","engineering_services","business_advisory"], business_models:["professional_service_provider","consultancy","service_provider"], routes:["service_contract","procurement"], mechanisms:["supplier_addition"] },
  { id:"logistics", name:"Logistics / Transportation", importance:"high", labels:["logistics","distribution"], subindustries:["freight","last_mile","cold_chain","warehouse","3pl","courier","fulfillment"], business_models:["logistics_operator","carrier","warehouse_operator","3pl","fulfillment_provider"], routes:["procurement","strategic_partnership","channel_distribution"], mechanisms:["supplier_addition","regional_expansion"] },
  { id:"food_beverage", name:"Food & Beverage", importance:"high", labels:["food_and_beverage","manufacturing"], subindustries:["restaurants","food_manufacturing","beverage_manufacturing","food_service"], business_models:["manufacturer","restaurant_operator","distributor","retailer"], routes:["procurement","retail_listing","wholesale_distribution"], mechanisms:["product_listing","supplier_addition"] },
  { id:"healthcare", name:"Healthcare Businesses", importance:"high", labels:["healthcare","health_and_wellness"], subindustries:["hospitals","clinics","diagnostics","medicine_functional","healthtech"], business_models:["healthcare_operator","service_provider","healthcare_network"], routes:["procurement","service_contract","strategic_partnership"], mechanisms:["supplier_addition","procurement_replacement"] },
  { id:"construction", name:"Construction / Real Estate", importance:"high", labels:["construction","real_estate"], subindustries:["developers","contractors","construction_materials","property_management"], business_models:["construction_company","developer","contractor","property_operator"], routes:["procurement","service_contract","strategic_partnership"], mechanisms:["supplier_addition","procurement_replacement"] },
  { id:"agribusiness", name:"Agribusiness", importance:"high", labels:["agribusiness","food_and_beverage"], subindustries:["agricultural_producer","agroindustrial","food_processing","agricultural_inputs","specialty_agriculture"], business_models:["producer","cooperative","exporter","distributor"], routes:["procurement","wholesale_distribution","channel_distribution"], mechanisms:["supplier_addition","distribution"] },
  { id:"wholesale", name:"Wholesale / Distribution", importance:"high", labels:["wholesale","distribution"], subindustries:["consumer_goods_distribution","industrial_distribution","specialty_distribution"], business_models:["wholesaler","distributor","importer","exporter"], routes:["wholesale_distribution","channel_distribution","reseller"], mechanisms:["distribution","resale"] },
  { id:"financial", name:"Financial Services / Fintech", importance:"high", labels:["financial_services","technology"], subindustries:["banking","insurance","fintech","payments"], business_models:["financial_institution","fintech","saas_vendor"], routes:["saas_purchase","service_contract","strategic_partnership"], mechanisms:["supplier_addition","partnership_bundle"] },
  { id:"beauty_wellness", name:"Beauty / Personal Care / Wellness", importance:"high", labels:["beauty","wellness","health_and_wellness"], subindustries:["cosmetics","personal_care","spa","natural_products_retail"], business_models:["manufacturer","retailer","spa_operator","distributor"], routes:["retail_listing","spa_integration","private_label"], mechanisms:["product_listing","spa_ritual"] },
  { id:"education", name:"Education / Training", importance:"medium", labels:["education","professional_services"], subindustries:["universities","technical_training","corporate_training","edtech"], business_models:["education_operator","training_provider","university_system"], routes:["service_contract","saas_purchase","procurement"], mechanisms:["supplier_addition","partnership_bundle"] },
  { id:"energy", name:"Energy / Utilities", importance:"high", labels:["energy","infrastructure"], subindustries:["electricity","renewables","oil_gas","utilities"], business_models:["energy_operator","utility","contractor"], routes:["procurement","service_contract","strategic_partnership"], mechanisms:["supplier_addition","procurement_replacement"] },
  { id:"automotive", name:"Automotive", importance:"medium", labels:["automotive","manufacturing"], subindustries:["automotive_parts","dealers","mobility_services","vehicle_services"], business_models:["manufacturer","distributor","dealer","service_provider"], routes:["procurement","channel_distribution","retail_listing"], mechanisms:["supplier_addition","distribution"] },
  { id:"creative", name:"Media / Marketing / Creative", importance:"medium", labels:["media","marketing","creative_services"], subindustries:["advertising_agencies","digital_marketing","media_companies","production"], business_models:["agency","professional_service_provider","media_operator"], routes:["service_contract","strategic_partnership"], mechanisms:["supplier_addition","partnership_bundle"] },
  { id:"trade", name:"Import / Export", importance:"high", labels:["import_export","distribution"], subindustries:["importers","exporters","customs","trade_services"], business_models:["importer","exporter","distributor","customs_broker"], routes:["channel_distribution","wholesale_distribution","strategic_partnership"], mechanisms:["distribution","regional_expansion"] },
  { id:"corporate_services", name:"Corporate Services", importance:"medium", labels:["corporate_services","professional_services"], subindustries:["facilities","human_resources","corporate_wellness","corporate_gifting"], business_models:["service_provider","corporate_gifting_provider","managed_service_provider"], routes:["service_contract","corporate_gifting","procurement"], mechanisms:["employee_gifting","supplier_addition"] },
  { id:"life_sciences", name:"Life Sciences / Pharmaceuticals", importance:"high", labels:["healthcare","manufacturing"], subindustries:["pharmaceutical_manufacturing","medical_devices","biotechnology","laboratories"], business_models:["manufacturer","healthcare_operator","distributor","importer"], routes:["procurement","channel_distribution","private_label"], mechanisms:["supplier_addition","procurement_replacement"] },
];

export interface SourceAtlasEntry {
  id:string; name:string; domain:string; country:"CO"; geography:string[]; clusters:string[]; subindustries:string[];
  business_models:string[]; routes:string[]; mechanisms:string[]; ecosystem:string; roles:string[];
  authority:"high"|"medium"|"low"; accessibility:OperationalAccessibility[]; structuredness:"structured"|"semi_structured"|"unstructured";
  entity_density:"high"|"medium"|"low"; official_domain_availability:"high"|"medium"|"low"; freshness:"high"|"medium"|"low";
  limitation:string; last_validated:string|null; confidence:AtlasConfidence; notes:string; specialized:boolean;
}
const A=(x:SourceAtlasEntry)=>x;
export const COLOMBIA_SOURCE_ATLAS: SourceAtlasEntry[] = [
 A({id:"co_rues",name:"RUES",domain:"rues.org.co",country:"CO",geography:["national"],clusters:["manufacturing","retail","professional_services","wholesale","trade","corporate_services"],subindustries:[],business_models:["manufacturer","retailer","service_provider","importer","exporter"],routes:["procurement","wholesale_distribution"],mechanisms:["supplier_addition"],ecosystem:"official_registries",roles:["IDENTITY_SOURCE","VALIDATION_SOURCE","COVERAGE_SOURCE"],authority:"high",accessibility:["direct_access","parser_required"],structuredness:"semi_structured",entity_density:"high",official_domain_availability:"low",freshness:"medium",limitation:"Certificates and some detail are paid; weak domain yield.",last_validated:null,confidence:"hypothesized",notes:"Broad identity fallback, not a specialized buyer source.",specialized:false}),
 A({id:"co_cotelco",name:"Cotelco affiliate directory",domain:"cotelco.org",country:"CO",geography:["national","regional chapters"],clusters:["hospitality"],subindustries:["hotels","boutique_hospitality","spa"],business_models:["hotel_operator","hospitality_group"],routes:["hospitality_guest_experience"],mechanisms:["guest_amenity"],ecosystem:"industry_associations",roles:["DISCOVERY_SOURCE","BUSINESS_MODEL_SOURCE","COVERAGE_SOURCE"],authority:"high",accessibility:["direct_access","parser_required","javascript_heavy","pagination_complex"],structuredness:"semi_structured",entity_density:"high",official_domain_availability:"high",freshness:"medium",limitation:"Pagination state is JS-heavy; robust parser/XHR inspection remains queued.",last_validated:"2026-08-02",confidence:"benchmarked",notes:"Live n=4: 4/4 real, resolved, direct domains, context/evidence/opportunity plausible. Benchmark only.",specialized:true}),
 A({id:"co_rnt",name:"Registro Nacional de Turismo",domain:"rnt.confecamaras.co",country:"CO",geography:["national"],clusters:["hospitality"],subindustries:["hotels","tourism_operators"],business_models:["hotel_operator","hospitality_group"],routes:["hospitality_guest_experience"],mechanisms:["guest_amenity"],ecosystem:"official_registries",roles:["IDENTITY_SOURCE","VALIDATION_SOURCE","COVERAGE_SOURCE"],authority:"high",accessibility:["javascript_heavy","manually_accessible_only"],structuredness:"structured",entity_density:"high",official_domain_availability:"low",freshness:"medium",limitation:"Live automation not established.",last_validated:"2026-08-02",confidence:"manually_validated",notes:"Strong identity universe; not yet a reliable automated discovery source.",specialized:true}),
 A({id:"co_andi",name:"ANDI chambers",domain:"andi.com.co",country:"CO",geography:["national","regional"],clusters:["manufacturing","food_beverage","wholesale","beauty_wellness","life_sciences","energy"],subindustries:["food_manufacturing","beverage_manufacturing","cosmetics","pharmaceutical_manufacturing"],business_models:["manufacturer","distributor","exporter"],routes:["procurement","channel_distribution"],mechanisms:["supplier_addition"],ecosystem:"industry_associations",roles:["DISCOVERY_SOURCE","BUSINESS_MODEL_SOURCE"],authority:"high",accessibility:["direct_access","parser_required"],structuredness:"semi_structured",entity_density:"medium",official_domain_availability:"low",freshness:"medium",limitation:"Company visibility varies by chamber; source pages do not reliably provide domains.",last_validated:"2026-08-07",confidence:"benchmarked",notes:"Manufacturing live n=5: 5/5 accepted in food chamber sample; high large/formal-member and food-subindustry concentration. Context-specific, not historically effective.",specialized:true}),
 A({id:"co_fenalco",name:"Fenalco",domain:"fenalco.com.co",country:"CO",geography:["national","regional"],clusters:["retail","food_beverage","wholesale"],subindustries:["specialty_retail","chain_retail"],business_models:["retailer","chain_operator","distributor"],routes:["retail_listing","wholesale_distribution"],mechanisms:["product_listing"],ecosystem:"industry_associations",roles:["DISCOVERY_SOURCE","BUSINESS_MODEL_SOURCE"],authority:"high",accessibility:["direct_access","parser_required"],structuredness:"semi_structured",entity_density:"low",official_domain_availability:"low",freshness:"medium",limitation:"V2.5 public search surface was duplicate-heavy and exposed no accepted account-level retailer entities; chapter visibility differs.",last_validated:"2026-08-09",confidence:"benchmarked",notes:"Retail LIVE source cohort n=12: 0 retail-compatible and 0 evidence-sufficient after corrected classification; recommended for ecosystem/context, not sole primary discovery.",specialized:true}),
 A({id:"co_procolombia",name:"ProColombia exporter ecosystem",domain:"procolombia.co",country:"CO",geography:["national"],clusters:["manufacturing","agribusiness","wholesale","trade"],subindustries:["exporters","agroindustrial","packaging","chemicals","textiles","metalworking"],business_models:["exporter","manufacturer","distributor","importer"],routes:["procurement","channel_distribution","strategic_partnership"],mechanisms:["supplier_addition","regional_expansion","distribution"],ecosystem:"trade_organizations",roles:["DISCOVERY_SOURCE","BUSINESS_MODEL_SOURCE","EVIDENCE_SOURCE"],authority:"high",accessibility:["direct_access","parser_required"],structuredness:"semi_structured",entity_density:"high",official_domain_availability:"low",freshness:"high",limitation:"Exporter-event lists are selection-biased and mix manufacturers with distributors/importers; domains require resolution.",last_validated:"2026-08-07",confidence:"benchmarked",notes:"Manufacturing live n=25: 17 accepted (68%); adds four subindustries and seven regions, but exporter share is 100% by source design. Context-specific, not representative.",specialized:true}),
 A({id:"co_fedesoft",name:"Fedesoft member directory",domain:"fedesoft.org",country:"CO",geography:["national"],clusters:["technology"],subindustries:["software","saas","it_services","ai"],business_models:["software_vendor","saas_vendor","systems_integrator"],routes:["saas_purchase","service_contract"],mechanisms:["supplier_addition"],ecosystem:"membership_directories",roles:["DISCOVERY_SOURCE","BUSINESS_MODEL_SOURCE","COVERAGE_SOURCE"],authority:"high",accessibility:["direct_access","javascript_heavy","parser_required"],structuredness:"semi_structured",entity_density:"high",official_domain_availability:"medium",freshness:"medium",limitation:"Filter/listing extraction needs validation.",last_validated:"2026-08-07",confidence:"manually_validated",notes:"Official directory observed with company listings and filters; no benchmark.",specialized:true}),
 A({id:"co_camacol",name:"Camacol affiliates and regional network",domain:"camacol.co",country:"CO",geography:["national","Bogotá","Antioquia","Valle del Cauca","Atlántico","Bolívar","Santander","Eje Cafetero"],clusters:["construction"],subindustries:["developers","contractors","construction_materials"],business_models:["construction_company","developer","contractor"],routes:["procurement","service_contract"],mechanisms:["supplier_addition"],ecosystem:"industry_associations",roles:["DISCOVERY_SOURCE","BUSINESS_MODEL_SOURCE","COVERAGE_SOURCE"],authority:"high",accessibility:["direct_access","parser_required"],structuredness:"semi_structured",entity_density:"high",official_domain_availability:"medium",freshness:"medium",limitation:"National page exposes selected affiliates; full regional universes differ.",last_validated:"2026-08-07",confidence:"manually_validated",notes:"Official site reports 1,867 affiliates across 19 regional structures; benchmark required.",specialized:true}),
 A({id:"co_achc",name:"ACHC hospital and clinic network",domain:"achc.org.co",country:"CO",geography:["national"],clusters:["healthcare"],subindustries:["hospitals","clinics"],business_models:["healthcare_operator","healthcare_network"],routes:["procurement","service_contract"],mechanisms:["supplier_addition"],ecosystem:"industry_associations",roles:["DISCOVERY_SOURCE","BUSINESS_MODEL_SOURCE","COVERAGE_SOURCE"],authority:"high",accessibility:["direct_access","parser_required"],structuredness:"semi_structured",entity_density:"high",official_domain_availability:"medium",freshness:"medium",limitation:"Member-detail extraction path not benchmarked.",last_validated:"2026-08-07",confidence:"manually_validated",notes:"Official site states more than 345 affiliated institutions; no live sample.",specialized:true}),
 A({id:"co_sac",name:"Sociedad de Agricultores de Colombia affiliates",domain:"sac.org.co",country:"CO",geography:["national"],clusters:["agribusiness","food_beverage"],subindustries:["agricultural_producer","agroindustrial","agricultural_inputs"],business_models:["producer","cooperative","exporter","association"],routes:["procurement","channel_distribution"],mechanisms:["supplier_addition","distribution"],ecosystem:"industry_associations",roles:["DISCOVERY_SOURCE","COVERAGE_SOURCE"],authority:"high",accessibility:["direct_access","parser_required"],structuredness:"semi_structured",entity_density:"medium",official_domain_availability:"medium",freshness:"medium",limitation:"Mixes associations and companies; entity type resolution required.",last_validated:"2026-08-07",confidence:"manually_validated",notes:"Official affiliate ecosystem observed; association-of-associations bias must be measured.",specialized:true}),
 A({id:"co_invima",name:"INVIMA public registries",domain:"invima.gov.co",country:"CO",geography:["national"],clusters:["food_beverage","beauty_wellness","life_sciences"],subindustries:["food_manufacturing","cosmetics","pharmaceutical_manufacturing","medical_devices"],business_models:["manufacturer","importer"],routes:["procurement","private_label"],mechanisms:["supplier_addition"],ecosystem:"official_registries",roles:["IDENTITY_SOURCE","VALIDATION_SOURCE","EVIDENCE_SOURCE"],authority:"high",accessibility:["direct_access","parser_required"],structuredness:"structured",entity_density:"high",official_domain_availability:"low",freshness:"medium",limitation:"Product/registration records need company resolution; weak commercial context.",last_validated:null,confidence:"hypothesized",notes:"Regulatory validation, not primary commercial discovery.",specialized:true}),
 A({id:"co_snies",name:"SNIES institutions",domain:"snies.mineducacion.gov.co",country:"CO",geography:["national","regional"],clusters:["education"],subindustries:["universities","technical_training"],business_models:["education_operator","university_system"],routes:["procurement","service_contract"],mechanisms:["supplier_addition"],ecosystem:"official_registries",roles:["DISCOVERY_SOURCE","IDENTITY_SOURCE","VALIDATION_SOURCE"],authority:"high",accessibility:["direct_access","parser_required"],structuredness:"structured",entity_density:"high",official_domain_availability:"low",freshness:"medium",limitation:"Institution identity is strong; procurement scope and domains require enrichment.",last_validated:null,confidence:"hypothesized",notes:"Education universe hypothesis.",specialized:true}),
 A({id:"co_colombia_fintech",name:"Colombia Fintech ecosystem",domain:"colombiafintech.co",country:"CO",geography:["national"],clusters:["financial","technology"],subindustries:["fintech","payments"],business_models:["fintech","saas_vendor"],routes:["saas_purchase","strategic_partnership"],mechanisms:["partnership_bundle"],ecosystem:"membership_directories",roles:["DISCOVERY_SOURCE","BUSINESS_MODEL_SOURCE"],authority:"medium",accessibility:["direct_access","parser_required"],structuredness:"semi_structured",entity_density:"medium",official_domain_availability:"medium",freshness:"medium",limitation:"Member directory access and completeness unvalidated.",last_validated:null,confidence:"discovered",notes:"Candidate specialist source.",specialized:true}),
 A({id:"co_fitac",name:"FITAC logistics ecosystem",domain:"fitac.net.co",country:"CO",geography:["national","regional"],clusters:["logistics","trade"],subindustries:["freight","customs","transportation"],business_models:["logistics_operator","carrier","customs_broker"],routes:["procurement","strategic_partnership"],mechanisms:["supplier_addition"],ecosystem:"industry_associations",roles:["DISCOVERY_SOURCE","COVERAGE_SOURCE"],authority:"high",accessibility:["direct_access","parser_required"],structuredness:"semi_structured",entity_density:"medium",official_domain_availability:"medium",freshness:"medium",limitation:"Affiliate surface requires validation.",last_validated:null,confidence:"discovered",notes:"Candidate specialist source; research queued.",specialized:true}),
 A({id:"co_asobancaria",name:"Asobancaria member ecosystem",domain:"asobancaria.com",country:"CO",geography:["national"],clusters:["financial"],subindustries:["banking","payments"],business_models:["financial_institution"],routes:["saas_purchase","service_contract"],mechanisms:["supplier_addition"],ecosystem:"industry_associations",roles:["DISCOVERY_SOURCE","IDENTITY_SOURCE"],authority:"high",accessibility:["direct_access","parser_required"],structuredness:"semi_structured",entity_density:"medium",official_domain_availability:"high",freshness:"medium",limitation:"Small concentrated universe; buying-unit evidence requires company research.",last_validated:null,confidence:"discovered",notes:"Useful universe, likely low novelty after first pass.",specialized:true}),
 A({id:"co_ccb_clusters",name:"Cámara de Comercio de Bogotá cluster initiatives",domain:"ccb.org.co",country:"CO",geography:["Bogotá","Cundinamarca"],clusters:["technology","creative","professional_services","corporate_services","manufacturing"],subindustries:["software","advertising_agencies","business_advisory"],business_models:["service_provider","manufacturer","software_vendor"],routes:["service_contract","procurement","strategic_partnership"],mechanisms:["supplier_addition"],ecosystem:"chambers_of_commerce",roles:["DISCOVERY_SOURCE","COVERAGE_SOURCE"],authority:"high",accessibility:["direct_access","parser_required"],structuredness:"semi_structured",entity_density:"medium",official_domain_availability:"medium",freshness:"medium",limitation:"Cluster pages may describe ecosystems without complete member lists.",last_validated:null,confidence:"hypothesized",notes:"Regional source hypothesis.",specialized:true}),
 A({id:"co_company_sites",name:"Official company websites",domain:"company-owned",country:"CO",geography:["national","regional"],clusters:COLOMBIA_PRIORITY_CLUSTERS.map(c=>c.id),subindustries:[],business_models:[],routes:[],mechanisms:[],ecosystem:"company_websites",roles:["EVIDENCE_SOURCE","BUSINESS_MODEL_SOURCE","VALIDATION_SOURCE"],authority:"high",accessibility:["provider_accessible","parser_required"],structuredness:"unstructured",entity_density:"low",official_domain_availability:"high",freshness:"high",limitation:"Requires a known entity/domain; not a market universe.",last_validated:null,confidence:"hypothesized",notes:"Evidence/enrichment surface only.",specialized:false}),
 A({id:"search_engine",name:"General web search",domain:"provider-dependent",country:"CO",geography:["national","regional"],clusters:COLOMBIA_PRIORITY_CLUSTERS.map(c=>c.id),subindustries:[],business_models:[],routes:[],mechanisms:[],ecosystem:"search_engines",roles:["DISCOVERY_SOURCE","COVERAGE_SOURCE","SIGNAL_SOURCE"],authority:"low",accessibility:["provider_accessible","rate_limited"],structuredness:"unstructured",entity_density:"medium",official_domain_availability:"medium",freshness:"high",limitation:"Provider availability/cost and noisy ranking; deliberate gap filler only.",last_validated:null,confidence:"hypothesized",notes:"Never presented as specialized coverage.",specialized:false}),
];

export interface CountryDiscoveryCoverage { country:string; cluster_id:string; breadth:CoverageBreadth; depth:CoverageDepth; known_ecosystems:number; registered_sources:number; specialized_sources:number; tier1_hypotheses:number; benchmarked_sources:number; live_sources:number; accessible_sources:number; biggest_gap:string; denominator_note:string; }
const breadth=(specialized:number, ecosystems:number):CoverageBreadth=>specialized>=3&&ecosystems>=3?"strong":specialized>=2?"good":specialized===1?"partial":ecosystems>0?"weak":"none";
const depth=(sources:SourceAtlasEntry[]):CoverageDepth=>sources.some(s=>s.confidence==="historically_effective")?"historically_effective":sources.some(s=>s.confidence==="multi_benchmark")?"multi_benchmark":sources.some(s=>s.confidence==="benchmarked")?"benchmarked":sources.some(s=>s.confidence==="manually_validated")?"manually_validated":sources.length?"hypothesized":"untested";
export function buildCountryCoverage(country="CO"):CountryDiscoveryCoverage[]{
 if(country!=="CO") return [];
 return COLOMBIA_PRIORITY_CLUSTERS.map(c=>{const ss=COLOMBIA_SOURCE_ATLAS.filter(s=>s.clusters.includes(c.id)); const sp=ss.filter(s=>s.specialized); const accessible=ss.filter(s=>!s.accessibility.some(a=>["blocked","inaccessible","operationally_unsuitable"].includes(a)));
  return {country,cluster_id:c.id,breadth:breadth(sp.length,new Set(sp.map(s=>s.ecosystem)).size),depth:depth(sp),known_ecosystems:new Set(ss.map(s=>s.ecosystem)).size,registered_sources:ss.length,specialized_sources:sp.length,tier1_hypotheses:sp.filter(s=>["hypothesized","manually_validated","benchmarked"].includes(s.confidence)).length,benchmarked_sources:sp.filter(s=>["benchmarked","multi_benchmark","historically_effective"].includes(s.confidence)).length,live_sources:sp.filter(s=>s.confidence==="benchmarked").length,accessible_sources:accessible.length,biggest_gap:sp.length===0?"cluster_no_specialized_source":depth(sp)==="hypothesized"?"source_unbenchmarked":sp.some(s=>s.accessibility.includes("parser_required"))?"parser_validation_needed":"repeat_benchmark_needed",denominator_note:"Registered and specialized source counts are within the 20 declared Colombia priority clusters; they do not represent all Colombian companies."};
 });
}

export interface BenchmarkCell { id:string; country:string; industry_labels:string[]; subindustry_labels:string[]; business_models:string[]; route:string; mechanism:string; source_ecosystems:string[]; candidate_sources:string[]; coverage_state:CoverageBreadth; benchmark_state:"queued"|"live_complete"|"not_started"; priority:number; rationale:string; }
export const COLOMBIA_BENCHMARK_QUEUE:BenchmarkCell[]=[
 {id:"discovery-v2-colombia-hospitality-live-001",country:"CO",industry_labels:["hospitality","boutique_hospitality","spa","wellness"],subindustry_labels:["boutique_hospitality"],business_models:["hotel_operator"],route:"hospitality_guest_experience",mechanism:"guest_amenity",source_ecosystems:["industry_associations","tourism_directories"],candidate_sources:["co_cotelco","co_rnt"],coverage_state:"good",benchmark_state:"live_complete",priority:1,rationale:"Preserved measured cell #1; n=4 and no search/hybrid comparison."},
 {id:"discovery-v2-colombia-manufacturing-live-001",country:"CO",industry_labels:["manufacturing"],subindustry_labels:["food_manufacturing","packaging","chemicals","textiles","metalworking"],business_models:["manufacturer","distributor","exporter"],route:"procurement",mechanism:"supplier_addition",source_ecosystems:["industry_associations","trade_organizations","search_engines"],candidate_sources:["co_andi","co_procolombia","search_engine"],coverage_state:"good",benchmark_state:"live_complete",priority:2,rationale:"Live n=30; ANDI/ProColombia plus bounded search/hybrid. High subindustry divergence and explicit exporter/formal-member bias."},
 {id:"co-retail-listing",country:"CO",industry_labels:["specialty_retail","multi_brand_retail"],subindustry_labels:["premium_retail"],business_models:["retailer","multi_brand_store"],route:"retail_listing",mechanism:"product_listing",source_ecosystems:["industry_associations","ecommerce_ecosystems"],candidate_sources:["co_fenalco"],coverage_state:"partial",benchmark_state:"live_complete",priority:3,rationale:"Live V2.5 measured fragmented association, mall, ecommerce, general-search and hybrid cohorts; sample remains non-representative."},
 {id:"co-technology-saas",country:"CO",industry_labels:["technology"],subindustry_labels:["software","saas"],business_models:["saas_vendor","software_vendor"],route:"saas_purchase",mechanism:"supplier_addition",source_ecosystems:["membership_directories"],candidate_sources:["co_fedesoft"],coverage_state:"partial",benchmark_state:"queued",priority:4,rationale:"Tests a filterable member directory and technology entity semantics."},
 {id:"co-logistics-partnership",country:"CO",industry_labels:["logistics"],subindustry_labels:["3pl","freight"],business_models:["logistics_operator"],route:"strategic_partnership",mechanism:"supplier_addition",source_ecosystems:["industry_associations"],candidate_sources:["co_fitac"],coverage_state:"partial",benchmark_state:"queued",priority:5,rationale:"Tests transport associations and regional operators."},
 {id:"co-agribusiness-distribution",country:"CO",industry_labels:["agribusiness"],subindustry_labels:["agroindustrial"],business_models:["producer","distributor"],route:"channel_distribution",mechanism:"distribution",source_ecosystems:["industry_associations","trade_organizations"],candidate_sources:["co_sac","co_procolombia"],coverage_state:"good",benchmark_state:"queued",priority:6,rationale:"Tests association-of-associations and exporter discovery."},
 {id:"co-professional-service-contract",country:"CO",industry_labels:["professional_services"],subindustry_labels:["consulting"],business_models:["professional_service_provider"],route:"service_contract",mechanism:"supplier_addition",source_ecosystems:["chambers_of_commerce"],candidate_sources:["co_ccb_clusters"],coverage_state:"partial",benchmark_state:"queued",priority:7,rationale:"Tests regional cluster discovery for service firms."},
 {id:"co-wholesale-channel",country:"CO",industry_labels:["wholesale","distribution"],subindustry_labels:["specialty_distribution"],business_models:["distributor","wholesaler"],route:"channel_distribution",mechanism:"distribution",source_ecosystems:["trade_organizations","industry_associations"],candidate_sources:["co_procolombia","co_andi"],coverage_state:"good",benchmark_state:"queued",priority:8,rationale:"Tests business-model precision across broad trade sources."},
 {id:"co-construction-procurement",country:"CO",industry_labels:["construction"],subindustry_labels:["developers","contractors"],business_models:["developer","contractor"],route:"procurement",mechanism:"supplier_addition",source_ecosystems:["industry_associations"],candidate_sources:["co_camacol"],coverage_state:"partial",benchmark_state:"queued",priority:9,rationale:"Tests a large regionalized affiliate network."},
 {id:"co-healthcare-procurement",country:"CO",industry_labels:["healthcare"],subindustry_labels:["hospitals","clinics"],business_models:["healthcare_operator"],route:"procurement",mechanism:"supplier_addition",source_ecosystems:["industry_associations"],candidate_sources:["co_achc"],coverage_state:"partial",benchmark_state:"queued",priority:10,rationale:"Tests institutional buyer and network/group resolution."},
];

export interface SourceResearchTaskV2 {id:string;country:string;cluster:string;subindustries:string[];route:string;gap:string;candidate_source:string;objective:string;expected_value:"high"|"medium";effort:"low"|"medium"|"high";status:"open"|"in_progress"|"done";result:string|null;}
export const SOURCE_RESEARCH_QUEUE_V2:SourceResearchTaskV2[]=COLOMBIA_BENCHMARK_QUEUE.slice(1).map((b,i)=>({id:`srq-v2-${String(i+1).padStart(2,"0")}`,country:"CO",cluster:b.industry_labels[0],subindustries:b.subindustry_labels,route:b.route,gap:b.benchmark_state==="live_complete"?"measured_followup":"source_unbenchmarked",candidate_source:b.candidate_sources[0],objective:`Validate entity density, domains, business-model precision and operational access for ${b.candidate_sources[0]}.`,expected_value:i<5?"high":"medium",effort:b.candidate_sources[0]==="co_fedesoft"?"medium":"low",status:b.benchmark_state==="live_complete"?"done":"open",result:b.benchmark_state!=="live_complete"?null:b.id==="co-retail-listing"?"Retail LIVE n=72: Fenalco public surface low-yield; search required; Exa added 10 canonical retail-compatible domains; regional/SME evidence remains a gap.":"Manufacturing Live n=30: ANDI n=5 at 100% accepted in food; ProColombia n=25 at 68%, exporter-biased; high routing divergence."}));
SOURCE_RESEARCH_QUEUE_V2.push({id:"srq-v2-10",country:"CO",cluster:"energy",subindustries:["utilities","renewables"],route:"procurement",gap:"cluster_no_specialized_source",candidate_source:"ANDESCO/UPME ecosystem",objective:"Identify an accessible entity-level energy/operator directory.",expected_value:"high",effort:"medium",status:"open",result:null});
SOURCE_RESEARCH_QUEUE_V2.push({id:"srq-v2-11",country:"CO",cluster:"retail",subindustries:["specialty_retail","regional_retail"],route:"retail_listing",gap:"regional_sme_undercoverage",candidate_source:"regional chambers / curated retail ecosystems",objective:"Find account-level regional and SME retail sources without repeating the broad V2.5 benchmark.",expected_value:"high",effort:"medium",status:"open",result:null});
SOURCE_RESEARCH_QUEUE_V2.push({id:"srq-v2-12",country:"CO",cluster:"retail",subindustries:["multi_brand_retail"],route:"retail_listing",gap:"assortment_evidence",candidate_source:"official retailer catalogs",objective:"Improve first-party assortment validation and editorial/directory rejection on the preserved V2.5 universe.",expected_value:"high",effort:"medium",status:"open",result:null});

export const ENTITY_RELATIONSHIP_TYPES=["parent_of","subsidiary_of","brand_of","property_of","branch_of","franchise_of","operates","owned_by","related_but_distinct"] as const;
export type EntityRelationshipType=typeof ENTITY_RELATIONSHIP_TYPES[number];
export const COMMERCIAL_DECISION_SCOPES=["corporate","group","brand","property","branch","regional","local","unknown"] as const;
export type CommercialDecisionScope=typeof COMMERCIAL_DECISION_SCOPES[number];
export interface AccountRelationship {from_account_id:string;to_account_id:string;type:EntityRelationshipType;evidence:string|null;confidence:"low"|"medium"|"high";decision_scope:CommercialDecisionScope;}

export interface SaturationCheckpoint {processed:number;resolved:number;qualified:number;novel:number;incremental_qualified:number;duplicate_rate:number;}
export function calculateSaturation(rows:{resolved:boolean;qualified:boolean;novel:boolean;duplicate:boolean}[],checkpoints=[10,20,30,50,100]):SaturationCheckpoint[]{let prev=0;return checkpoints.filter(n=>n<=rows.length).map(n=>{const x=rows.slice(0,n);const qualified=x.filter(r=>r.qualified).length;const out={processed:n,resolved:x.filter(r=>r.resolved).length,qualified,novel:x.filter(r=>r.novel).length,incremental_qualified:qualified-prev,duplicate_rate:x.filter(r=>r.duplicate).length/n};prev=qualified;return out;});}
export function diversityYield(values:{geography:string;parent:string;business_model:string;subindustry:string;mechanism:string}[]){const ratio=(k:keyof typeof values[number])=>values.length?new Set(values.map(v=>v[k])).size/values.length:0;return {geographic:ratio("geography"),parent_group:ratio("parent"),business_model:ratio("business_model"),subindustry:ratio("subindustry"),mechanism:ratio("mechanism")};}
export function concentrationFlags(values:string[],dimension:string,threshold=.7){if(!values.length)return[];const counts=new Map<string,number>();values.forEach(v=>counts.set(v,(counts.get(v)??0)+1));return Array.from(counts).filter(([,n])=>n/values.length>=threshold).map(([value,n])=>({dimension,value,count:n,share:n/values.length,flag:"source_high_concentration" as const}));}

export interface CoverageGapV2 {type:string;cluster:string|null;severity:"high"|"medium"|"low";evidence:string;next_action:string;}
export function coverageGapsV2():CoverageGapV2[]{const coverage=buildCountryCoverage();const gaps:CoverageGapV2[]=[];for(const c of coverage){if(c.specialized_sources===0)gaps.push({type:"cluster_no_specialized_source",cluster:c.cluster_id,severity:"high",evidence:"0 specialized registered sources",next_action:"Research and validate a sector source."});else if(c.benchmarked_sources===0)gaps.push({type:"source_unbenchmarked",cluster:c.cluster_id,severity:"medium",evidence:`${c.specialized_sources} hypotheses, 0 benchmarked`,next_action:"Run the queued bounded benchmark."});}for(const route of routeCoverage().filter(r=>r.specialized_sources===0))gaps.push({type:"route_no_source",cluster:null,severity:"high",evidence:`${route.route}: 0 specialized sources`,next_action:"Research a route-relevant source or declare controlled transfer."});return gaps;}
export function routeCoverage(){const routes=Array.from(new Set(COLOMBIA_PRIORITY_CLUSTERS.flatMap(c=>c.routes)));return routes.map(route=>({route,clusters:COLOMBIA_PRIORITY_CLUSTERS.filter(c=>c.routes.includes(route)).length,specialized_sources:COLOMBIA_SOURCE_ATLAS.filter(s=>s.specialized&&s.routes.includes(route)).length}));}
export function businessModelCoverage(){const models=Array.from(new Set(COLOMBIA_PRIORITY_CLUSTERS.flatMap(c=>c.business_models)));return models.map(business_model=>({business_model,clusters:COLOMBIA_PRIORITY_CLUSTERS.filter(c=>c.business_models.includes(business_model)).length,specialized_sources:COLOMBIA_SOURCE_ATLAS.filter(s=>s.specialized&&s.business_models.includes(business_model)).length}));}

export function coverageForContext(labels:string[],models:string[],routes:string[]){const candidates=COLOMBIA_PRIORITY_CLUSTERS.map(c=>({c,score:c.labels.filter(x=>labels.includes(x)).length*3+c.business_models.filter(x=>models.includes(x)).length*2+c.routes.filter(x=>routes.includes(x)).length})).sort((a,b)=>b.score-a.score);const primary=candidates[0]?.score?candidates[0].c:null;const coverage=primary?buildCountryCoverage().find(x=>x.cluster_id===primary.id):null;const adjacent=candidates.filter(x=>x.score>0&&x.c.id!==primary?.id).map(x=>x.c.id);return {primary_cluster:primary?.id??null,adjacent_clusters:adjacent,coverage,routing_state:!coverage||coverage.specialized_sources===0?"INSUFFICIENT_SOURCE_COVERAGE":coverage.breadth==="weak"?"fallback_coverage":"specialized_coverage" as "INSUFFICIENT_SOURCE_COVERAGE"|"fallback_coverage"|"specialized_coverage"};}

export function sourceResearchProtocol(){return ["discover_source","verify_relevance","verify_authority","inspect_entity_density","inspect_business_model_relevance","inspect_domains_and_identifiers","inspect_operational_access","assign_source_roles","map_context","queue_benchmark"] as const;}
export const COUNTRY_BOOTSTRAP_WORKFLOW=["create_country_profile","map_priority_clusters","identify_broad_authoritative_sources","identify_sector_ecosystems","create_source_atlas","assess_accessibility","generate_coverage_gaps","build_benchmark_queue","run_representative_benchmarks","accumulate_source_memory"] as const;
export function internationalReadiness(){return {schema:"ready",router:"ready",taxonomy:"portable",source_registry:"portable",benchmark_framework:"ready",country_specific_assumptions:["Spanish Colombia terminology","Colombia organization identifiers","regional chamber structure"],next_country:"MX",start_when:"After manufacturing, retail and technology bounded benchmarks establish three materially different source structures."};}
export function providerDiagnostic(env:Record<string,string|undefined>=process.env){const defs=[{id:"brave",key:"BRAVE_SEARCH_API_KEY",role:"general search / freshness"},{id:"serper",key:"SERPER_API_KEY",role:"general search / domain resolution"},{id:"tavily",key:"TAVILY_API_KEY",role:"evidence discovery"},{id:"firecrawl",key:"FIRECRAWL_API_KEY",role:"page extraction / structured extraction"}];return defs.map(d=>({provider:d.id,configured:Boolean(env[d.key]),runtime_available:Boolean(env[d.key]),quota_test_possible:Boolean(env[d.key]),intended_role:d.role,last_known_working_state:"not_tested_in_v2_2"}));}
export function v22Audit(){return {provider_calls:0,source_access_validations:6,deep_source_inspections:6,limits:{provider_calls:20,source_access_validations:40,deep_source_inspections:25},live_benchmark:buildLiveBenchmark().id};}
