import { mkdir,readFile,rename,writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import type { UsaManufacturingObservation,UsaProviderCall } from "./usa-manufacturing-live";
import { USA_MANUFACTURING_BENCHMARK_ID } from "./usa-manufacturing-live";

export interface LostCallSummary{count:number;providers:Record<string,number>;state:"executed_but_results_not_persisted";recorded_at:string;cost_usd:null;}
export interface RecoveryState{benchmark_id:string;schema_version:"v2.6-recovery-1";created_at:string;updated_at:string;hard_budget:number;lost_calls:LostCallSummary;completed_step_ids:string[];calls:UsaProviderCall[];observations:UsaManufacturingObservation[];partial_funnel:{raw_results:number;unique_urls:number;provider_calls_persisted:number;total_calls_counted:number};reliability:{partial_persistence_failure:true;incremental_persistence_enabled:true;resume_count:number;duplicate_call_blocks:number};}
export function initialRecoveryState(now:string):RecoveryState{return{benchmark_id:USA_MANUFACTURING_BENCHMARK_ID,schema_version:"v2.6-recovery-1",created_at:now,updated_at:now,hard_budget:28,lost_calls:{count:14,providers:{brave:5,tavily:5,exa:4},state:"executed_but_results_not_persisted",recorded_at:now,cost_usd:null},completed_step_ids:[],calls:[],observations:[],partial_funnel:{raw_results:0,unique_urls:0,provider_calls_persisted:0,total_calls_counted:14},reliability:{partial_persistence_failure:true,incremental_persistence_enabled:true,resume_count:0,duplicate_call_blocks:0}};}
export function remainingBudget(s:RecoveryState){return s.hard_budget-s.lost_calls.count-s.calls.length;}
export function recordRecoveryCall(s:RecoveryState,stepId:string,call:UsaProviderCall,observation:UsaManufacturingObservation,now:string):RecoveryState{if(s.completed_step_ids.includes(stepId))return{...s,updated_at:now,reliability:{...s.reliability,duplicate_call_blocks:s.reliability.duplicate_call_blocks+1}};if(remainingBudget(s)<=0)throw new Error("usa_manufacturing_total_budget_exhausted");const observations=[...s.observations,observation],calls=[...s.calls,call],urls=observations.flatMap(x=>x.response.results.map(r=>r.canonical_url));return{...s,updated_at:now,completed_step_ids:[...s.completed_step_ids,stepId],calls,observations,partial_funnel:{raw_results:urls.length,unique_urls:new Set(urls).size,provider_calls_persisted:calls.length,total_calls_counted:s.lost_calls.count+calls.length}};}
export async function persistRecoveryState(path:string,state:RecoveryState){await mkdir(dirname(path),{recursive:true});const tmp=`${path}.tmp`;await writeFile(tmp,JSON.stringify(state,null,2)+"\n","utf8");await rename(tmp,path);}
export async function loadRecoveryState(path:string,now:string){try{const s=JSON.parse(await readFile(path,"utf8")) as RecoveryState;return{...s,reliability:{...s.reliability,resume_count:s.reliability.resume_count+1}};}catch(e){if((e as NodeJS.ErrnoException).code==="ENOENT")return initialRecoveryState(now);throw e;}}
