import type { SearchResultItem } from "@/lib/sources/access/provider-contract";
import type { SourcePerformanceSnapshot } from "./router";

export const USA_MANUFACTURING_BENCHMARK_ID="discovery-v2-usa-manufacturing-live-001";
export const USA_MANUFACTURING_VERSION="discovery-v2-6-usa-manufacturing-v1";
export const USA_MANUFACTURING_CALL_BUDGET=28;
export type UsaManufacturingCohort="specialized_first"|"search_first"|"hybrid"|"exa_escalation";
export type UsaEntityType="manufacturer"|"contract_manufacturer"|"assembler"|"distributor"|"importer"|"wholesaler"|"service_provider"|"logistics_provider"|"brand_owner"|"parent_group"|"subsidiary"|"facility"|"marketplace_directory"|"article"|"other";
export type UsaSubindustry="food_beverage"|"packaging_plastics"|"chemicals_cosmetics"|"textiles_apparel"|"metalworking"|"machinery_equipment"|"building_materials"|"electronics_electrical"|"medical_health"|"other";
export interface UsaManufacturingObservation{provider:string;source_id:string;source_role:string[];cohort:UsaManufacturingCohort;query:string;purpose:string;response:{ok:boolean;latency_ms:number;cost_estimate_usd:number|null;error:string|null;results:SearchResultItem[]};}
export interface UsaProviderCall{provider:string;purpose:string;source_id:string;query:string;timestamp:string;success:boolean;latency_ms:number;result_count:number;estimated_cost_usd:number|null;safe_error:string|null;}
export interface UsaManufacturingCandidate{raw_entity:string;canonical_account:string|null;legal_entity:string|null;parent_group:string|null;domain:string|null;url:string;provider:string;source_id:string;source_roles:string[];cohort:UsaManufacturingCohort;entity_types:UsaEntityType[];subindustries:UsaSubindustry[];state:string;state_resolution:"observed_text"|"unknown";official_domain:boolean;manufacturer_decision:"manufacturer_compatible"|"borderline"|"non_manufacturer";procurement_plausibility:"structurally_plausible"|"weak"|"unsupported";buying_intent:"not_inferred";commercial_decision_scope:"corporate"|"group"|"facility"|"unknown";evidence:string|null;evidence_yield:boolean;novelty:"genuinely_new"|"duplicate"|"uncertain";confidence:"low"|"moderate";data_basis:"live_provider";}

const excluded=/(linkedin|facebook|instagram|youtube|wikipedia|bloomberg|reuters|forbes|yelp|mapquest|thomasnet|industrynet|iqsdirectory|manta|zoominfo|crunchbase|nist\.gov|manufacturingusa|nam\.org|contractmanufacturingcompanies|packworld|contractpackaging|flexpack|medicaldevices\.org|directory|association|expo|tradefair|news|magazine)/i;
const article=/(news|article|report|ranking|top \d|guide|how to|market size|industry outlook|list of|directory|members|exhibitors|success stor|association|publication|magazine)/i;
const manufacturer=/(manufactur|factory|production facilit|we produce|contract manufactur|made in|industrial products|machining|injection mold|assembly)/i;
const distributor=/(distributor|wholesal|reseller|supplier directory|importer)/i;
const service=/(consulting|staffing|software|logistics|marketing|association|extension partnership|economic development)/i;
const stateNames:Record<string,string>={Alabama:"AL",Alaska:"AK",Arizona:"AZ",Arkansas:"AR",California:"CA",Colorado:"CO",Connecticut:"CT",Delaware:"DE",Florida:"FL",Georgia:"GA",Idaho:"ID",Illinois:"IL",Indiana:"IN",Iowa:"IA",Kansas:"KS",Kentucky:"KY",Louisiana:"LA",Maine:"ME",Maryland:"MD",Massachusetts:"MA",Michigan:"MI",Minnesota:"MN",Mississippi:"MS",Missouri:"MO",Montana:"MT",Nebraska:"NE",Nevada:"NV","New Hampshire":"NH","New Jersey":"NJ","New Mexico":"NM","New York":"NY","North Carolina":"NC","North Dakota":"ND",Ohio:"OH",Oklahoma:"OK",Oregon:"OR",Pennsylvania:"PA","Rhode Island":"RI","South Carolina":"SC","South Dakota":"SD",Tennessee:"TN",Texas:"TX",Utah:"UT",Vermont:"VT",Virginia:"VA",Washington:"WA","West Virginia":"WV",Wisconsin:"WI",Wyoming:"WY"};
function host(url:string){try{return new URL(url).hostname.toLowerCase().replace(/^www\./,"");}catch{return null;}}
function root(h:string|null){if(!h)return null;const p=h.split(".");return p.length>2?p.slice(-2).join("."):h;}
function nameOf(title:string|null,h:string|null){return (title??"").split(/[|–—]/)[0].trim()||h?.split(".")[0]||"Unknown";}
function stateOf(text:string){for(const [name,code] of Object.entries(stateNames)){if(new RegExp(`\\b${name}\\b`,"i").test(text)||new RegExp(`\\b${code}\\b`).test(text))return code;}return "unknown";}
function subs(text:string):UsaSubindustry[]{const out:UsaSubindustry[]=[];const add=(x:UsaSubindustry,re:RegExp)=>{if(re.test(text))out.push(x)};add("food_beverage",/food|beverage|ingredient|bakery|drink/i);add("packaging_plastics",/packag|plastic|polymer|bottle|container/i);add("chemicals_cosmetics",/chemical|cosmetic|personal care|cleaning/i);add("textiles_apparel",/textile|apparel|fabric|garment/i);add("metalworking",/metal|steel|machining|fabrication|casting/i);add("machinery_equipment",/machinery|equipment|industrial automation|tooling/i);add("building_materials",/building material|cement|concrete|lumber|construction product/i);add("electronics_electrical",/electronic|electrical|semiconductor|circuit/i);add("medical_health",/medical device|pharma|healthcare product/i);return out.length?out:["other"];}
export function classifyUsaManufacturing(item:Pick<SearchResultItem,"url"|"title"|"snippet">):{types:UsaEntityType[];decision:UsaManufacturingCandidate["manufacturer_decision"]}{const text=`${item.title??""} ${item.snippet??""} ${item.url}`,title=item.title??"";const h=host(item.url);if(excluded.test(h??"")||article.test(text))return{types:[article.test(text)?"article":"marketplace_directory"],decision:"non_manufacturer"};if(/supplier|distributor|dealer/i.test(title)&&!manufacturer.test(title))return{types:["distributor"],decision:"non_manufacturer"};const types:UsaEntityType[]=[];if(/contract manufactur/i.test(text))types.push("contract_manufacturer");else if(manufacturer.test(text))types.push("manufacturer");if(/assembl/i.test(text))types.push("assembler");if(distributor.test(text))types.push("distributor");if(/importer/i.test(text))types.push("importer");if(/logistics|freight|3pl/i.test(text))types.push("logistics_provider");else if(service.test(text))types.push("service_provider");if(!types.length)types.push("other");const compatible=types.some(x=>["manufacturer","contract_manufacturer","assembler"].includes(x));return{types,decision:compatible?"manufacturer_compatible":types.includes("other")?"borderline":"non_manufacturer"};}

export function buildUsaManufacturingArtifact(observations:UsaManufacturingObservation[],calls:UsaProviderCall[],capturedAt:string){
 const seen=new Set<string>();
 const candidates:UsaManufacturingCandidate[]=observations.flatMap(o=>o.response.results.map(item=>{const h=host(item.url),domain=root(h),text=`${item.title??""} ${item.snippet??""}`,classified=classifyUsaManufacturing(item),official=Boolean(domain&&!excluded.test(domain)),key=domain??item.canonical_url,duplicate=seen.has(key);seen.add(key);const evidence=official&&classified.decision==="manufacturer_compatible"?text.slice(0,300):null;return{raw_entity:nameOf(item.title,h),canonical_account:official?nameOf(item.title,h):null,legal_entity:null,parent_group:null,domain:official?domain:null,url:item.canonical_url,provider:o.provider,source_id:o.source_id,source_roles:o.source_role,cohort:o.cohort,entity_types:classified.types,subindustries:subs(text),state:stateOf(text),state_resolution:stateOf(text)==="unknown"?"unknown":"observed_text",official_domain:official,manufacturer_decision:classified.decision,procurement_plausibility:classified.decision==="manufacturer_compatible"?"structurally_plausible":classified.decision==="borderline"?"weak":"unsupported",buying_intent:"not_inferred",commercial_decision_scope:official?"corporate":"unknown",evidence,evidence_yield:Boolean(evidence),novelty:duplicate?"duplicate":official?"genuinely_new":"uncertain",confidence:official&&classified.decision==="manufacturer_compatible"?"moderate":"low",data_basis:"live_provider"} as UsaManufacturingCandidate;}));
 const unique=candidates.filter(x=>x.novelty!=="duplicate"),canonical=unique.filter(x=>x.domain),compatible=canonical.filter(x=>x.manufacturer_decision==="manufacturer_compatible");
 const baseDomains=new Set(candidates.filter(x=>x.provider!=="exa"&&x.domain).map(x=>x.domain));const exa=unique.filter(x=>x.provider==="exa"),exaQualified=exa.filter(x=>x.manufacturer_decision==="manufacturer_compatible"&&x.domain),exaIncremental=exaQualified.filter(x=>!baseDomains.has(x.domain));
 const cohortFunnel=Object.fromEntries((["specialized_first","search_first","hybrid","exa_escalation"] as UsaManufacturingCohort[]).map(cohort=>{const r=unique.filter(x=>x.cohort===cohort);return[cohort,{executed:r.length>0,raw:candidates.filter(x=>x.cohort===cohort).length,unique:r.length,canonical:r.filter(x=>x.domain).length,manufacturer_compatible:r.filter(x=>x.domain&&x.manufacturer_decision==="manufacturer_compatible").length,evidence_sufficient:r.filter(x=>x.evidence_yield).length}]}));
 const checkpoints=[10,20,30,40,50,70].filter(n=>n<=candidates.length).map(n=>{const r=candidates.slice(0,n),u=r.filter(x=>x.novelty!=="duplicate");return{processed:n,canonical:new Set(u.filter(x=>x.domain).map(x=>x.domain)).size,manufacturer_compatible:u.filter(x=>x.domain&&x.manufacturer_decision==="manufacturer_compatible").length,incremental_qualified:u.filter(x=>x.domain&&x.manufacturer_decision==="manufacturer_compatible").length};});
 const sourceSnapshots:SourcePerformanceSnapshot[]=Array.from(new Set(observations.map(x=>x.source_id))).map(source_id=>{const r=candidates.filter(x=>x.source_id===source_id),u=r.filter(x=>x.novelty!=="duplicate"),good=u.filter(x=>x.domain&&x.manufacturer_decision==="manufacturer_compatible");return{source_id,cycle_id:USA_MANUFACTURING_BENCHMARK_ID,captured_at:capturedAt,country:"US",candidates_discovered:r.length,valid_entities:u.filter(x=>x.domain).length,correct_business_models:good.length,context_compatible:good.length,evidence_sufficient:good.filter(x=>x.evidence_yield).length,opportunity_plausible:good.length,portfolio_accounts:0,novelty_yield:good.length?good.filter(x=>x.novelty==="genuinely_new").length/good.length:null,false_positives:u.filter(x=>x.manufacturer_decision==="non_manufacturer").length,duplicates:r.filter(x=>x.novelty==="duplicate").length,extraction_failures:0,access_failures:observations.filter(x=>x.source_id===source_id&&!x.response.ok).length,avg_cost:null,avg_latency_ms:Math.round(observations.filter(x=>x.source_id===source_id).reduce((n,x)=>n+x.response.latency_ms,0)/Math.max(1,observations.filter(x=>x.source_id===source_id).length)),client_selected_rate:null,contact_rate:null,order_rate:null,outcome_state:"awaiting_real_outcomes"};});
 const states=unique.filter(x=>x.state!=="unknown");const stateCounts=Object.fromEntries(Array.from(new Set(states.map(x=>x.state))).map(s=>[s,states.filter(x=>x.state===s).length]));const subCounts=Object.fromEntries(Array.from(new Set(unique.flatMap(x=>x.subindustries))).map(s=>[s,unique.filter(x=>x.subindustries.includes(s)).length]));const strong=compatible.filter(x=>x.evidence_yield).slice(0,10),borderline=unique.filter(x=>x.manufacturer_decision==="borderline").slice(0,10),rejected=unique.filter(x=>x.manufacturer_decision==="non_manufacturer").slice(0,10);
 const totalCost=calls.every(x=>x.estimated_cost_usd===null)?null:calls.reduce((n,x)=>n+(x.estimated_cost_usd??0),0);const exaCost=calls.filter(x=>x.provider==="exa").every(x=>x.estimated_cost_usd===null)?null:calls.filter(x=>x.provider==="exa").reduce((n,x)=>n+(x.estimated_cost_usd??0),0);
 return{id:USA_MANUFACTURING_BENCHMARK_ID,version:USA_MANUFACTURING_VERSION,live_execution:true,data_basis:"live_provider",captured_at:capturedAt,context:{country:"US",cluster:"manufacturing",business_model:"manufacturer",route:"procurement",mechanism:"supplier_addition",client_specific:false},budget:{hard_max:USA_MANUFACTURING_CALL_BUDGET,actual:calls.length,within_budget:calls.length<=USA_MANUFACTURING_CALL_BUDGET},calls,observations,candidates,cohort_funnel:cohortFunnel,metrics:{raw_candidates:candidates.length,unique_candidates:unique.length,canonical_accounts:new Set(canonical.map(x=>x.domain)).size,manufacturer_compatible:compatible.length,manufacturer_precision:canonical.length?compatible.length/canonical.length:0,official_domain_yield:unique.length?canonical.length/unique.length:0,digital_resolution_yield:unique.length?canonical.length/unique.length:0,evidence_yield:compatible.length?compatible.filter(x=>x.evidence_yield).length/compatible.length:0,procurement_plausible:compatible.length,buying_intent_inferred:0,states_observed:new Set(states.map(x=>x.state)).size,exa_calls:calls.filter(x=>x.provider==="exa").length,exa_raw:exa.length,exa_qualified:exaQualified.length,exa_incremental_qualified:exaIncremental.length,exa_overlap:exaQualified.length-exaIncremental.length,exa_official_domain_yield:exa.length?exa.filter(x=>x.domain).length/exa.length:0,exa_evidence_yield:exaQualified.length?exaQualified.filter(x=>x.evidence_yield).length/exaQualified.length:0,total_cost_usd:totalCost,exa_cost_usd:exaCost,cost_per_incremental_exa_qualified:exaCost!==null&&exaIncremental.length?exaCost/exaIncremental.length:null},observed_sample_bias:{states:stateCounts,subindustries:subCounts,digitally_visible_share:unique.length?canonical.length/unique.length:0,public_company_share:"not_measured",government_contractor_share:"not_measured",warning:"Observed sample composition, not market representation."},saturation:checkpoints,source_performance_snapshots:sourceSnapshots,manual_review:{accepted:strong,borderline,rejected,automated_decision_preserved:true},exa_decision:exaIncremental.length>=8?"high_incremental_value":exaIncremental.length>=3?"useful_escalation":exaIncremental.length?"marginal":"redundant",sec:{calls:0,contribution:"not_used_no_reliable_public_company_cik_trigger"},sam:{calls:0,status:"skipped_operational_404_and_no_required_federal_route",contribution:"none"},warnings:["Structural procurement plausibility is not buying intent.","No people/contact data.","Observed bias is not national representativeness.","Confidence ceiling is benchmarked."],stop_reason:calls.length>=USA_MANUFACTURING_CALL_BUDGET?"hard_budget_reached":"planned_cohorts_completed"};
}
