import { loadEnvConfig } from "@next/env";import { mkdir,writeFile } from "node:fs/promises";
import { braveProvider,exaProvider,firecrawlProvider,tavilyProvider } from "@/lib/sources/access/providers";import type { SearchProvider } from "@/lib/sources/access/provider-contract";
import { buildUsaManufacturingArtifact,USA_MANUFACTURING_BENCHMARK_ID,type UsaManufacturingCohort,type UsaManufacturingObservation,type UsaProviderCall } from "@/lib/discovery/source-intelligence/usa-manufacturing-live";
import { loadRecoveryState,persistRecoveryState,recordRecoveryCall,remainingBudget,type RecoveryState } from "@/lib/discovery/source-intelligence/usa-manufacturing-recovery";
loadEnvConfig(process.cwd());const partialPath=`artifacts/discovery/${USA_MANUFACTURING_BENCHMARK_ID}.partial.json`;let state:RecoveryState;
type Step={id:string;provider:SearchProvider;source_id:string;roles:string[];cohort:UsaManufacturingCohort;purpose:string;query:string;max:number};
const discovery:Step[]=[
{id:"recovery-specialized-packaging",provider:braveProvider,source_id:"us_specialized_manufacturing",roles:["DISCOVERY_SOURCE","BUSINESS_MODEL_SOURCE"],cohort:"specialized_first",purpose:"specialized_packaging_accounts",query:'US packaging manufacturers association member companies official websites',max:8},
{id:"recovery-specialized-medical",provider:tavilyProvider,source_id:"us_specialized_manufacturing",roles:["DISCOVERY_SOURCE","BUSINESS_MODEL_SOURCE"],cohort:"specialized_first",purpose:"specialized_medical_accounts",query:'United States medical device manufacturers association member companies official websites',max:8},
{id:"recovery-regional-metal",provider:braveProvider,source_id:"us_regional_manufacturing",roles:["DISCOVERY_SOURCE","COVERAGE_SOURCE"],cohort:"search_first",purpose:"regional_manufacturer_accounts",query:'Ohio Michigan metalworking machinery manufacturers company official site',max:8},
{id:"recovery-regional-diversity",provider:tavilyProvider,source_id:"us_regional_manufacturing",roles:["DISCOVERY_SOURCE","COVERAGE_SOURCE"],cohort:"search_first",purpose:"regional_manufacturer_accounts",query:'Texas North Carolina California contract manufacturers plastics electronics official websites',max:8},
{id:"recovery-exa-incremental",provider:exaProvider,source_id:"exa_semantic",roles:["DISCOVERY_SOURCE","IDENTITY_SOURCE"],cohort:"exa_escalation",purpose:"incremental_company_discovery",query:'US small and mid-sized packaging plastics medical device and metalworking manufacturers official company websites',max:8},
];
async function execute(step:Step){if(state.completed_step_ids.includes(step.id))return;if(remainingBudget(state)<=0)throw new Error("usa_manufacturing_total_budget_exhausted");const r=await step.provider.search({query:step.query,region:"us",language:"en",max_results:step.max,query_type:step.cohort==="specialized_first"?"industry_discovery":"regional_discovery",search_mode:step.provider.id==="exa"?"fast":"standard"});const call:UsaProviderCall={provider:step.provider.id,purpose:step.purpose,source_id:step.source_id,query:step.query,timestamp:new Date().toISOString(),success:r.ok,latency_ms:r.latency_ms,result_count:r.results.length,estimated_cost_usd:r.cost_estimate_usd,safe_error:r.error};const observation:UsaManufacturingObservation={provider:step.provider.id,source_id:step.source_id,source_role:step.roles,cohort:step.cohort,query:step.query,purpose:step.purpose,response:r};state=recordRecoveryCall(state,step.id,call,observation,new Date().toISOString());await persistRecoveryState(partialPath,state);console.log(JSON.stringify({persisted_call:state.calls.length,total_counted:state.partial_funnel.total_calls_counted,step:step.id,results:r.results.length,remaining:remainingBudget(state)}));}
async function main(){state=await loadRecoveryState(partialPath,new Date().toISOString());await persistRecoveryState(partialPath,state);for(const step of discovery)await execute(step);
 const interim=buildUsaManufacturingArtifact(state.observations,state.calls,state.created_at);const top=interim.candidates.filter(x=>x.novelty!=="duplicate"&&x.manufacturer_decision==="manufacturer_compatible"&&x.domain).slice(0,4);for(let i=0;i<top.length&&remainingBudget(state)>0;i++){const c=top[i],step:Step={id:`recovery-evidence-${c.domain}`,provider:firecrawlProvider,source_id:"official_company_evidence",roles:["EVIDENCE_SOURCE","VALIDATION_SOURCE"],cohort:"hybrid",purpose:"manufacturer_evidence_validation",query:`site:${c.domain} manufacturing capabilities products facilities`,max:3};await execute(step);}
 const artifact=buildUsaManufacturingArtifact(state.observations,state.calls,state.created_at);await mkdir("artifacts/discovery",{recursive:true});await mkdir("output",{recursive:true});const final={...artifact,recovery:{original_lost_calls:state.lost_calls,recovery_calls_persisted:state.calls.length,total_calls_counted:state.lost_calls.count+state.calls.length,partial_state_path:partialPath,resumability_verified:true,duplicate_call_protection:true,reliability:state.reliability},execution:{access_method:"authorized provider APIs",no_people_data:true,sec_calls:0,sam_calls:0}};const body=JSON.stringify(final,null,2)+"\n";await writeFile(`artifacts/discovery/${USA_MANUFACTURING_BENCHMARK_ID}.json`,body,"utf8");await writeFile(`output/${USA_MANUFACTURING_BENCHMARK_ID}.json`,body,"utf8");console.log(JSON.stringify({id:artifact.id,recovery_calls:state.calls.length,total_calls:state.lost_calls.count+state.calls.length,raw:artifact.metrics.raw_candidates,canonical:artifact.metrics.canonical_accounts,manufacturer_compatible:artifact.metrics.manufacturer_compatible,precision:artifact.metrics.manufacturer_precision,states:artifact.metrics.states_observed,exa_incremental:artifact.metrics.exa_incremental_qualified,remaining:remainingBudget(state)},null,2));}
main().catch(async e=>{if(state)await persistRecoveryState(partialPath,state);console.error(e instanceof Error?e.message:"usa_manufacturing_recovery_failed");process.exit(1)});
