import{loadEnvConfig}from"@next/env";import{mkdir,readFile,rename,writeFile}from"fs/promises";import{dirname}from"path";import{AMOR_SEARCH_BLUEPRINT as blueprint}from"@/lib/intelligence/amor-de-gea-search-blueprint";import{tavilyProvider}from"@/lib/sources/access/providers";import type{SearchProvider,SearchProviderResponse}from"@/lib/sources/access/provider-contract";
loadEnvConfig(process.cwd());
export const RECOVERY_RUN_ID="amor_phase4_recovery_v1";export const CHECKPOINT_PATH=`ml/data/opportunity-intelligence/${RECOVERY_RUN_ID}.checkpoint.json`;export const RECOVERY_CALL_CEILING=15;
export const EXECUTION_QUERIES=["tienda productos naturales premium extractos botánicos Colombia catálogo oficial","tienda wellness premium independiente Bogotá Medellín Cali productos naturales","concept store vida saludable premium Colombia tienda online","retailer Colombia extractos botánicos bienestar catálogo","hotel boutique spa Colombia tienda bienestar productos","hotel bienestar spa Cartagena Eje Cafetero Antioquia experiencias","spa premium independiente Colombia productos retail bienestar","retiro bienestar Colombia tienda productos alianzas","regalos corporativos premium Colombia kits bienestar catálogo","cajas regalo curadas bienestar natural Bogotá Medellín Cali","proveedor kits bienestar empleados Colombia regalos corporativos","marca experiencias premium Colombia co-branding regalos","distribuidor regional productos naturales premium Colombia portafolio","distribuidor bienestar marcas independientes Colombia catálogo","distribuidor retail especializado productos naturales región andina Colombia"] as const;
type SanitizedCandidate={query_id:string;route:string;provider:string;rank:number;title:string|null;url:string;source_type:string|null;retrieved_at:string;published_date:string|null;snippet:string|null};
type QueryCheckpoint={query_id:string;route:string;original_query:string;execution_query:string;provider:string;status:"pending"|"processing"|"completed"|"failed";attempts:number;executed_at:string|null;raw_result_count:number;persisted_result_count:number;latency_ms:number|null;cost_estimate_usd:number|null;error:string|null;candidates:SanitizedCandidate[]};
export type RecoveryCheckpoint={run_id:string;pilot_id:string;context_id:string;blueprint_id:string;blueprint_version:1;state:"pending"|"processing"|"completed"|"failed";created_at:string;updated_at:string;original_failed_attempt:{provider:"tavily";calls:15;provider_errors:0;local_serialization_failures:1;persisted_results:0};recovery:{provider:"tavily";call_ceiling:15;calls:number;provider_errors:number;exact_cost_usd:null};queries:QueryCheckpoint[];raw_provider_payloads_persisted:false};
const sanitize=(response:SearchProviderResponse,query_id:string,route:string):SanitizedCandidate[]=>response.results.slice(0,6).map(result=>({query_id,route,provider:response.provider,rank:result.rank,title:result.title,url:result.canonical_url,source_type:result.source_type,retrieved_at:result.retrieved_at,published_date:result.published_date,snippet:result.snippet?.slice(0,240)??null}));
async function atomicWrite(path:string,value:RecoveryCheckpoint){await mkdir(dirname(path),{recursive:true});const temp=`${path}.tmp`;await writeFile(temp,JSON.stringify(value,null,2)+"\n","utf8");await rename(temp,path)}
export async function loadOrCreateCheckpoint(path=CHECKPOINT_PATH,now=()=>new Date().toISOString()):Promise<RecoveryCheckpoint>{try{const saved=JSON.parse(await readFile(path,"utf8")) as RecoveryCheckpoint;if(saved.run_id!==RECOVERY_RUN_ID||saved.blueprint_id!==blueprint.blueprint_id)throw new Error("checkpoint_identity_mismatch");return saved}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;const timestamp=now();const checkpoint:RecoveryCheckpoint={run_id:RECOVERY_RUN_ID,pilot_id:"amor-de-gea",context_id:blueprint.context_id,blueprint_id:blueprint.blueprint_id,blueprint_version:1,state:"pending",created_at:timestamp,updated_at:timestamp,original_failed_attempt:{provider:"tavily",calls:15,provider_errors:0,local_serialization_failures:1,persisted_results:0},recovery:{provider:"tavily",call_ceiling:RECOVERY_CALL_CEILING,calls:0,provider_errors:0,exact_cost_usd:null},queries:blueprint.query_hypotheses.map((hypothesis,index)=>({query_id:hypothesis.id,route:hypothesis.route,original_query:EXECUTION_QUERIES[index],execution_query:EXECUTION_QUERIES[index],provider:"tavily",status:"pending",attempts:0,executed_at:null,raw_result_count:0,persisted_result_count:0,latency_ms:null,cost_estimate_usd:null,error:null,candidates:[]})),raw_provider_payloads_persisted:false};await atomicWrite(path,checkpoint);return checkpoint}}
export async function executeRecovery(options:{provider?:SearchProvider;path?:string;now?:()=>string;failBeforeQuery?:number}={}){const provider=options.provider??tavilyProvider,path=options.path??CHECKPOINT_PATH,now=options.now??(()=>new Date().toISOString());const checkpoint=await loadOrCreateCheckpoint(path,now);if(checkpoint.state==="completed")return checkpoint;if(checkpoint.queries.length!==15||checkpoint.recovery.calls>RECOVERY_CALL_CEILING)throw new Error("recovery_integrity_failed");checkpoint.state="processing";checkpoint.updated_at=now();await atomicWrite(path,checkpoint);
 for(let index=0;index<checkpoint.queries.length;index++){const query=checkpoint.queries[index];if(query.status==="completed")continue;if(checkpoint.recovery.calls>=RECOVERY_CALL_CEILING)throw new Error("recovery_call_ceiling_reached");if(options.failBeforeQuery===index+1)throw new Error(`simulated_failure_before_${query.query_id}`);query.status="processing";query.attempts+=1;query.executed_at=now();checkpoint.updated_at=now();await atomicWrite(path,checkpoint);const response=await provider.search({query:query.execution_query,region:"co",language:"es",max_results:6,query_type:"industry_discovery"});checkpoint.recovery.calls+=1;query.raw_result_count=response.results.length;query.latency_ms=response.latency_ms;query.cost_estimate_usd=response.cost_estimate_usd;query.candidates=sanitize(response,query.query_id,query.route);query.persisted_result_count=query.candidates.length;query.error=response.error;if(response.ok){query.status="completed"}else{query.status="failed";checkpoint.recovery.provider_errors+=1;checkpoint.state="failed"}checkpoint.updated_at=now();await atomicWrite(path,checkpoint);if(!response.ok)break}
 if(checkpoint.queries.every(q=>q.status==="completed")){checkpoint.state="completed";checkpoint.updated_at=now();await atomicWrite(path,checkpoint)}return checkpoint}
async function main(){if(blueprint.blueprint_id!=="blueprint_57b88651984aaee555dc23be"||blueprint.version!==1||blueprint.approval_state!=="approved")throw new Error("exact_blueprint_not_approved");const health=await tavilyProvider.health();if(health.status!=="available")throw new Error(`tavily_unavailable:${health.reason}`);const result=await executeRecovery();console.log(JSON.stringify({run_id:result.run_id,state:result.state,recovery_calls:result.recovery.calls,provider_errors:result.recovery.provider_errors,completed:result.queries.filter(q=>q.status==="completed").length,failed:result.queries.filter(q=>q.status==="failed").length,persisted_results:result.queries.reduce((sum,q)=>sum+q.persisted_result_count,0),checkpoint:CHECKPOINT_PATH,exact_cost_usd:null},null,2))}
if(process.argv[1]?.includes("run-amor-phase4-controlled-search"))main().catch(error=>{console.error(error instanceof Error?error.message:String(error));process.exit(1)});
