import { loadEnvConfig } from "@next/env";import { mkdir,writeFile } from "node:fs/promises";
import { braveProvider,exaProvider,tavilyProvider } from "@/lib/sources/access/providers";import type { SearchProvider } from "@/lib/sources/access/provider-contract";
import { buildUsaManufacturingArtifact,USA_MANUFACTURING_BENCHMARK_ID,USA_MANUFACTURING_CALL_BUDGET,type UsaManufacturingCohort,type UsaManufacturingObservation,type UsaProviderCall } from "@/lib/discovery/source-intelligence/usa-manufacturing-live";
loadEnvConfig(process.cwd());const capturedAt=new Date().toISOString(),observations:UsaManufacturingObservation[]=[],calls:UsaProviderCall[]=[];
async function run(provider:SearchProvider,source_id:string,source_role:string[],cohort:UsaManufacturingCohort,purpose:string,query:string,max=6){if(calls.length>=USA_MANUFACTURING_CALL_BUDGET)throw new Error("usa_manufacturing_budget_reached");const r=await provider.search({query,region:"us",language:"en",max_results:max,query_type:cohort==="specialized_first"?"industry_discovery":"regional_discovery",search_mode:provider.id==="exa"?"fast":"standard"});calls.push({provider:provider.id,purpose,source_id,query,timestamp:new Date().toISOString(),success:r.ok,latency_ms:r.latency_ms,result_count:r.results.length,estimated_cost_usd:r.cost_estimate_usd,safe_error:r.error});observations.push({provider:provider.id,source_id,source_role,cohort,query,purpose,response:r});}
async function main(){const base:[SearchProvider,string,string[],UsaManufacturingCohort,string,string][]=[
[braveProvider,"us_mep_ecosystem",["DISCOVERY_SOURCE","BUSINESS_MODEL_SOURCE","EVIDENCE_SOURCE"],"specialized_first","mep_company_discovery",'site:nist.gov/mep manufacturer "success story" company'],
[tavilyProvider,"us_mep_ecosystem",["DISCOVERY_SOURCE","BUSINESS_MODEL_SOURCE"],"specialized_first","mep_company_discovery",'US Manufacturing Extension Partnership client manufacturers company'],
[braveProvider,"us_state_manufacturing_associations",["DISCOVERY_SOURCE","COVERAGE_SOURCE"],"specialized_first","association_member_discovery",'state manufacturing association member directory manufacturers Ohio Michigan Texas'],
[tavilyProvider,"us_industrial_directories",["DISCOVERY_SOURCE","BUSINESS_MODEL_SOURCE"],"specialized_first","industrial_directory_discovery",'United States manufacturer directory packaging plastics machinery companies'],
[braveProvider,"us_search",["DISCOVERY_SOURCE","IDENTITY_SOURCE"],"search_first","food_packaging_discovery",'US food beverage packaging manufacturers official company'],
[tavilyProvider,"us_search",["DISCOVERY_SOURCE","IDENTITY_SOURCE"],"search_first","chemicals_medical_discovery",'USA chemical cosmetics medical device manufacturers official company'],
[braveProvider,"us_search",["DISCOVERY_SOURCE","IDENTITY_SOURCE"],"search_first","metal_machinery_discovery",'US metalworking machinery industrial equipment manufacturers official company'],
[tavilyProvider,"us_search",["DISCOVERY_SOURCE","IDENTITY_SOURCE"],"search_first","electronics_building_discovery",'USA electronics electrical building materials manufacturers official company'],
[braveProvider,"us_hybrid",["IDENTITY_SOURCE","EVIDENCE_SOURCE"],"hybrid","regional_domain_resolution",'American regional manufacturers official websites Texas Ohio Michigan North Carolina'],
[tavilyProvider,"us_hybrid",["IDENTITY_SOURCE","EVIDENCE_SOURCE"],"hybrid","smb_domain_resolution",'US small mid sized manufacturers official website contract manufacturing'],
];for(const p of base)await run(...p);
for(const query of ["United States independent food beverage and packaging manufacturing companies official websites","United States plastics chemicals cosmetics contract manufacturers official websites","American metalworking machinery industrial equipment manufacturers official websites","United States electronics medical device building materials manufacturers official websites"])await run(exaProvider,"exa_semantic",["DISCOVERY_SOURCE","IDENTITY_SOURCE"],"exa_escalation","incremental_company_discovery",query);
const artifact=buildUsaManufacturingArtifact(observations,calls,capturedAt);await mkdir("artifacts/discovery",{recursive:true});await mkdir("output",{recursive:true});const body=JSON.stringify({...artifact,execution:{access_method:"authorized provider APIs",sample_method:"bounded contextual queries and provider ranking",provider_config_fingerprint:"credential presence only",no_people_data:true}},null,2)+"\n";await writeFile(`artifacts/discovery/${USA_MANUFACTURING_BENCHMARK_ID}.json`,body,"utf8");await writeFile(`output/${USA_MANUFACTURING_BENCHMARK_ID}.json`,body,"utf8");console.log(JSON.stringify({id:artifact.id,calls:artifact.budget.actual,raw:artifact.metrics.raw_candidates,canonical:artifact.metrics.canonical_accounts,manufacturer_compatible:artifact.metrics.manufacturer_compatible,precision:artifact.metrics.manufacturer_precision,states:artifact.metrics.states_observed,exa_incremental:artifact.metrics.exa_incremental_qualified,exa_decision:artifact.exa_decision},null,2));}
main().catch(e=>{console.error(e instanceof Error?e.message:"usa_manufacturing_live_failed");process.exit(1)});
