import { loadEnvConfig } from "@next/env";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { tavilyProvider } from "@/lib/sources/access/providers";
import type { SearchProvider, SearchProviderResponse } from "@/lib/sources/access/provider-contract";
import { AMOR_BLUEPRINT_V2_APPROVAL } from "@/lib/intelligence/amor-de-gea-blueprint-v2-replay";
loadEnvConfig(process.cwd());

export const RUN_ID="amor_blueprint_v2_bounded_search_20260803_v1";
export const CHECKPOINT_PATH=`ml/data/opportunity-intelligence/${RUN_ID}.checkpoint.json`;
export const LIMITS={provider_calls:8,query_families:4,queries_per_family:2,raw_results:60,unique_domains:40,identity_verified:20,qualified:12,deep_researched:8,new_portfolio_accounts:6} as const;
export const QUERY_PLAN=[
 {id:"v2_retail_owner_multibrand",family:"retail",route:"specialty_retail",query:'Colombia "tienda multimarca" "productos naturales" catálogo marcas comprar online',archetype:"founder/owner-led multibrand wellness retailer",fields:["Pilot MOQ","Early recurring range","Procurement tolerance","Durable relationship objective"],rules:["R01_CATEGORY_BUYER","R02_FORMAT_TEST","R07_RECURRENCE","R18_PROCUREMENT"],mechanism:"approximately 50-unit multibrand test followed by shelf/ecommerce replenishment",size:"50 test; 100–300 recurrence",procurement:"founder/owner/direct purchasing preferred",recurrence:"shelf or ecommerce replenishment",evidence:"official active catalog showing third-party brands",exclude:["monobrand","MLM","national chain","content community"],not_scenario_a:"Requires bounded test, direct procurement and explicit replenishment.",stop:"two identity-resolved qualified challengers"},
 {id:"v2_retail_regional_replenishment",family:"retail",route:"specialty_retail",query:'Colombia tienda regional saludable multimarca "nuestras marcas" domicilio productos naturales',archetype:"small regional specialty retailer",fields:["National coverage","Pilot MOQ","Business maturity","Procurement tolerance"],rules:["R02_FORMAT_TEST","R10_NATIONAL_FREIGHT","R15_MATURITY","R18_PROCUREMENT"],mechanism:"regional shelf test with concentrated reorder",size:"50 test; staged recurrence",procurement:"local purchasing preferred",recurrence:"regional shelf replenishment",evidence:"official assortment and operating location",exclude:["mass retail","inactive ecommerce","own-brand only"],not_scenario_a:"Requires modest onboarding, concentrated freight and direct buying.",stop:"one stronger challenger or saturation"},
 {id:"v2_hospitality_retail_repeat",family:"hospitality",route:"hospitality_spa",query:'Colombia "hotel boutique" spa "tienda" productos bienestar regalos huéspedes',archetype:"boutique hotel/spa with retail or guest gifting",fields:["Premium packaging","Glass packaging","Pilot MOQ","Route priorities"],rules:["R02_FORMAT_TEST","R03_PREMIUM_ROUTE","R11_GLASS","R17_ROUTE_PRIORITY"],mechanism:"spa retail or guest gifting followed by inventory replenishment",size:"approximately 50-unit pilot",procurement:"boutique/local management preferred",recurrence:"spa retail or guest-program replenishment",evidence:"official hotel page showing store, gifting, package or external products",exclude:["spa language only","centralized chain","single-use amenity dependency"],not_scenario_a:"Requires recurring guest use, glass validation and boutique procurement.",stop:"two accounts with official commercial mechanism"},
 {id:"v2_hospitality_wellness_package",family:"hospitality",route:"hospitality_spa",query:'Colombia retiro bienestar hotel "paquete" huéspedes tienda regalos productos locales',archetype:"retreat/hotel with recurring wellness package",fields:["Special assortments","Co-branding","Short commercial-cycle preference","Pilot learning objectives"],rules:["R04_CUSTOMIZATION","R14_SHORT_CYCLE","R19_BUYER_PATH","R20_LEARNING"],mechanism:"curated recurring guest or retreat package using finished products",size:"bounded package test",procurement:"program owner or guest-experience lead",recurrence:"recurring retreat/guest program",evidence:"official package and third-party/local product integration",exclude:["decorative partnership","no repeat program","unsupported claims"],not_scenario_a:"Requires a programmatic use, buyer-path change and learning experiment.",stop:"one evidence-backed challenger"},
 {id:"v2_gifting_recurring_program",family:"gifting",route:"gifting",query:'Colombia "regalos corporativos" personalizados "bienestar" empresas programas recurrentes marcas',archetype:"corporate gifting curator with repeat-client programs",fields:["Corporate gifting","Custom labels","Co-branding","Early recurring range"],rules:["R04_CUSTOMIZATION","R07_RECURRENCE","R17_ROUTE_PRIORITY","R20_LEARNING"],mechanism:"co-branded employee/client wellness kits across recurring programs",size:"moderate project order",procurement:"commercial/partnerships route",recurrence:"repeat corporate-client programs",evidence:"official B2B customization and third-party curation",exclude:["consumer gift shop","own products only","private label dependency"],not_scenario_a:"Requires co-branding plus repeat corporate-client mechanics.",stop:"two qualified gifting challengers"},
 {id:"v2_gifting_curated_brands",family:"gifting",route:"gifting",query:'Colombia cajas corporativas "marcas aliadas" personalización regalos clientes empleados',archetype:"curated multi-brand corporate box provider",fields:["Packaging adaptation","Special assortments","Private-label uncertainty","Procurement tolerance"],rules:["R04_CUSTOMIZATION","R05_PRIVATE_LABEL","R18_PROCUREMENT","R19_BUYER_PATH"],mechanism:"finished-product inclusion in repeat seasonal/client boxes",size:"moderate curated assortment",procurement:"direct gifting-company buyer",recurrence:"seasonal and repeat-client gifting",evidence:"official corporate catalog and partner-brand model",exclude:["private-label required","generic events agency","no curation"],not_scenario_a:"Requires finished-product compatibility and rejects private-label dependence.",stop:"one challenger with clearer recurrence than Habibi"},
 {id:"v2_distribution_selective_regional",family:"distribution",route:"regional_distribution",query:'Colombia distribuidor regional selectivo "productos naturales" marcas independientes catálogo',archetype:"selective regional wellness distributor",fields:["Capacity above 300","Capacity near 1,000+","National coverage","Procurement tolerance"],rules:["R08_CAPACITY_300","R09_VOLUME_1000","R10_NATIONAL_FREIGHT","R18_PROCUREMENT"],mechanism:"controlled regional listing followed by independent-retailer replenishment",size:"100–300 staged introduction",procurement:"selective portfolio buyer",recurrence:"regional wholesale replenishment",evidence:"official distributor catalog and regional role",exclude:["mass distribution","immediate 1,000+","private label","unclear identity"],not_scenario_a:"Requires staged volume and explicitly blocks immediate scale.",stop:"one selective distributor or route remains gap"},
 {id:"v2_distribution_staged_onboarding",family:"distribution",route:"regional_distribution",query:'Colombia mayorista productos saludables "marcas" distribuimos tiendas independientes regional',archetype:"specialized wholesaler serving independents",fields:["Early recurring range","Business maturity","Documentation stated available","Pilot learning objectives"],rules:["R07_RECURRENCE","R12_DOCUMENTS","R15_MATURITY","R20_LEARNING"],mechanism:"phased supplier onboarding and replenishment to independent stores",size:"100–300 recurring compatibility required",procurement:"structured validation, no FIRST TEST",recurrence:"wholesale replenishment",evidence:"official wholesale role, catalog and service area",exclude:["national-chain supply","complex compliance","theoretical scale only"],not_scenario_a:"Requires maturity-compatible onboarding and a staged learning exception.",stop:"one qualified account or saturation"},
] as const;

type Candidate={query_id:string;family:string;route:string;provider:string;rank:number;title:string|null;url:string;domain:string;source_type:string|null;retrieved_at:string;published_date:string|null;snippet_persisted:false;gate:{identity:"candidate"|"insufficient";colombia:"probable";hard_rule_failure:boolean;decision:"investigate"|"insufficient evidence";rules_passed:string[];rules_conditioned:string[];counterfactual_a:"generic include";v2_result:string}};
type QueryState={query_id:string;family:string;route:string;query:string;context_fields:readonly string[];rule_ids:readonly string[];mechanism:string;status:"pending"|"processing"|"completed"|"failed";attempts:number;provider:string;executed_at:string|null;latency_ms:number|null;raw_results:number;error:string|null;candidates:Candidate[]};
export type BoundedCheckpoint={run_id:string;state:"pending"|"processing"|"completed"|"failed";blueprint_id:string;compiler_version:"2.0.0";created_at:string;updated_at:string;limits:typeof LIMITS;provider_health:{tavily:string};provider_calls:number;provider_errors:number;exact_cost_usd:null;queries:QueryState[];raw_payloads_persisted:false};
const domain=(url:string)=>{try{return new URL(url).hostname.replace(/^www\./,"")}catch{return url}};
const weakDomain=(d:string)=>/(facebook|instagram|linkedin|youtube|tripadvisor|booking|wikipedia|pinterest|tiktok)\./.test(d);
const sanitize=(response:SearchProviderResponse,plan:typeof QUERY_PLAN[number]):Candidate[]=>response.results.slice(0,5).map(result=>{const d=domain(result.canonical_url);const insufficient=weakDomain(d);return{query_id:plan.id,family:plan.family,route:plan.route,provider:response.provider,rank:result.rank,title:result.title,url:result.canonical_url,domain:d,source_type:result.source_type,retrieved_at:result.retrieved_at,published_date:result.published_date,snippet_persisted:false,gate:{identity:insufficient?"insufficient":"candidate",colombia:"probable",hard_rule_failure:false,decision:insufficient?"insufficient evidence":"investigate",rules_passed:insufficient?[]:[...plan.rules],rules_conditioned:["R10_NATIONAL_FREIGHT","R16_RELATIONSHIP_UNKNOWN","R22_OFFICIAL_EVIDENCE"],counterfactual_a:"generic include",v2_result:insufficient?"stop before qualification":"identity/evidence verification required"}}});
async function save(path:string,state:BoundedCheckpoint){await mkdir(dirname(path),{recursive:true});const temp=`${path}.tmp`;await writeFile(temp,JSON.stringify(state,null,2)+"\n","utf8");await rename(temp,path)}
export async function loadOrCreate(path=CHECKPOINT_PATH,now=()=>new Date().toISOString()){try{const state=JSON.parse(await readFile(path,"utf8")) as BoundedCheckpoint;if(state.run_id!==RUN_ID||state.blueprint_id!==AMOR_BLUEPRINT_V2_APPROVAL.blueprint_id||state.compiler_version!=="2.0.0"||state.provider_calls>LIMITS.provider_calls)throw new Error("bounded_checkpoint_integrity_failed");return state}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;const t=now();const state:BoundedCheckpoint={run_id:RUN_ID,state:"pending",blueprint_id:AMOR_BLUEPRINT_V2_APPROVAL.blueprint_id,compiler_version:"2.0.0",created_at:t,updated_at:t,limits:LIMITS,provider_health:{tavily:"not_checked"},provider_calls:0,provider_errors:0,exact_cost_usd:null,queries:QUERY_PLAN.map(p=>({query_id:p.id,family:p.family,route:p.route,query:p.query,context_fields:p.fields,rule_ids:p.rules,mechanism:p.mechanism,status:"pending",attempts:0,provider:"tavily",executed_at:null,latency_ms:null,raw_results:0,error:null,candidates:[]})),raw_payloads_persisted:false};await save(path,state);return state}}
export async function executeBounded(options:{provider?:SearchProvider;path?:string;now?:()=>string;stopAfter?:number}={}){const provider=options.provider??tavilyProvider,path=options.path??CHECKPOINT_PATH,now=options.now??(()=>new Date().toISOString());const state=await loadOrCreate(path,now);if(state.state==="completed")return state;if(state.queries.length!==8||new Set(state.queries.map(q=>q.family)).size>4)throw new Error("query_plan_limit_failed");const health=await provider.health();state.provider_health.tavily=health.status;if(health.status!=="available")throw new Error(`provider_unavailable:${health.reason}`);state.state="processing";await save(path,state);
 for(const query of state.queries){if(query.status==="completed")continue;if(state.provider_calls>=LIMITS.provider_calls)throw new Error("provider_call_ceiling_reached");if(options.stopAfter!==undefined&&state.provider_calls>=options.stopAfter)break;query.status="processing";query.attempts++;query.executed_at=now();state.updated_at=now();await save(path,state);const plan=QUERY_PLAN.find(p=>p.id===query.query_id)!;const response=await provider.search({query:query.query,region:"co",language:"es",max_results:5,query_type:"industry_discovery"});state.provider_calls++;query.latency_ms=response.latency_ms;query.raw_results=Math.min(response.results.length,5);query.error=response.error;query.candidates=sanitize(response,plan);query.status=response.ok?"completed":"failed";if(!response.ok){state.provider_errors++;state.state="failed"}state.updated_at=now();await save(path,state);if(!response.ok)break;const raw=state.queries.reduce((n,q)=>n+q.raw_results,0),unique=new Set(state.queries.flatMap(q=>q.candidates.map(c=>c.domain))).size;if(raw>=LIMITS.raw_results||unique>=LIMITS.unique_domains)break}
 if(state.queries.every(q=>q.status==="completed")){state.state="completed";state.updated_at=now();await save(path,state)}return state}
async function main(){if(AMOR_BLUEPRINT_V2_APPROVAL.status!=="APPROVED FOR DETERMINISTIC REPLAY"||AMOR_BLUEPRINT_V2_APPROVAL.compiler_version!=="2.0.0")throw new Error("blueprint_v2_not_approved");const state=await executeBounded();console.log(JSON.stringify({run_id:state.run_id,state:state.state,provider_calls:state.provider_calls,provider_errors:state.provider_errors,raw_results:state.queries.reduce((n,q)=>n+q.raw_results,0),unique_domains:new Set(state.queries.flatMap(q=>q.candidates.map(c=>c.domain))).size,completed:state.queries.filter(q=>q.status==="completed").length,checkpoint:CHECKPOINT_PATH,exact_cost_usd:null},null,2))}
if(process.argv[1]?.includes("run-amor-blueprint-v2-bounded-search"))main().catch(error=>{console.error(error instanceof Error?error.message:String(error));process.exit(1)});
