import type { CustomerDependency, RouteDefinition } from "@/lib/intelligence/market-research-universe";

export const AMOR_DE_GEA_US_ROUTE_ONTOLOGY: RouteDefinition[] = [
  { canonical_route_family_id: "specialty_premium_retail", canonical_route_id: "natural_specialty_grocery", display_label: "Natural and specialty grocery", aliases: ["Natural grocery retail", "Natural and organic grocery", "Regional premium grocery chain", "Regional premium grocery"], parent_route_id: null, buyer_types: ["Category management", "Grocery procurement", "New item review"], commercial_role: "retailer", scope: "US natural, organic and premium grocery retailers" },
  { canonical_route_family_id: "specialty_premium_retail", canonical_route_id: "online_natural_retail", display_label: "Online natural-products retail", aliases: ["Online natural products retail", "Wellness e-commerce"], parent_route_id: null, buyer_types: ["Marketplace category management", "Merchandising"], commercial_role: "retailer", scope: "US online retailers of natural and wellness products" },
  { canonical_route_family_id: "specialty_premium_retail", canonical_route_id: "specialty_beverage_retail", display_label: "Specialty beverage retail", aliases: ["Premium beverage retail", "Specialty drink retail"], parent_route_id: null, buyer_types: ["Beverage category management", "Merchandising"], commercial_role: "retailer", scope: "US specialty beverage retail" },
  { canonical_route_family_id: "wellness_hospitality", canonical_route_id: "wellness_hospitality", display_label: "Wellness hospitality and spa", aliases: ["Wellness resorts and spas", "Luxury hospitality and wellness", "Hotel and spa", "Wellness retail"], parent_route_id: null, buyer_types: ["Food and beverage procurement", "Spa retail", "Guest experience"], commercial_role: "operator", scope: "US wellness hospitality, resorts and spas" },
  { canonical_route_family_id: "wellness_hospitality", canonical_route_id: "fitness_wellness_clubs", display_label: "Fitness and wellness clubs", aliases: ["Health clubs and wellness", "Fitness and wellness"], parent_route_id: null, buyer_types: ["Retail merchandising", "Procurement", "Member experience"], commercial_role: "operator", scope: "US fitness and wellness club operators" },
  { canonical_route_family_id: "distribution_import", canonical_route_id: "natural_products_distribution", display_label: "Natural-products distribution", aliases: ["Natural product distributor", "Natural-products distributor", "Specialty distributor"], parent_route_id: null, buyer_types: ["Supplier development", "Category management", "Purchasing"], commercial_role: "distributor", scope: "US distributors serving natural and wellness channels" },
  { canonical_route_family_id: "distribution_import", canonical_route_id: "specialty_food_beverage_import", display_label: "Specialty food and beverage import", aliases: ["Food beverage importer", "Premium beverage distributor", "Latin American specialty importer", "Importer"], parent_route_id: null, buyer_types: ["Import procurement", "Brand portfolio management", "Supplier partnerships"], commercial_role: "importer", scope: "US importers and distributors onboarding external specialty brands" },
  { canonical_route_family_id: "foodservice_hospitality", canonical_route_id: "foodservice_procurement", display_label: "Foodservice and hospitality procurement", aliases: ["Foodservice", "Hospitality procurement"], parent_route_id: null, buyer_types: ["Food and beverage procurement", "Strategic sourcing"], commercial_role: "buyer", scope: "US foodservice and hospitality procurement ecosystems" },
  { canonical_route_family_id: "corporate_programs", canonical_route_id: "corporate_gifting", display_label: "Corporate gifting", aliases: ["Gifting", "Corporate gift programs"], parent_route_id: null, buyer_types: ["Corporate gifting", "Employee experience", "Client marketing"], commercial_role: "buyer", scope: "US corporate gifting programs and intermediaries" },
];

export const AMOR_DE_GEA_CUSTOMER_DEPENDENCIES: CustomerDependency[] = [
  { dependency_id: "product_classification", label: "Exact US product classification", status: "CUSTOMER_INPUT_REQUIRED", blocking_level: "route", source: "customer_context", route_ids: AMOR_DE_GEA_US_ROUTE_ONTOLOGY.map((r) => r.canonical_route_id), account_refs: [], validation_question: "What is the exact product, ingredient and claims classification for US sale?" },
  { dependency_id: "landed_economics", label: "Landed economics and target margin", status: "CUSTOMER_INPUT_REQUIRED", blocking_level: "decision", source: "customer_context", route_ids: AMOR_DE_GEA_US_ROUTE_ONTOLOGY.map((r) => r.canonical_route_id), account_refs: [], validation_question: "What landed unit economics and channel margins are commercially viable?" },
  { dependency_id: "minimum_order_quantity", label: "Minimum order quantity compatibility", status: "CUSTOMER_INPUT_REQUIRED", blocking_level: "account", source: "customer_context", route_ids: AMOR_DE_GEA_US_ROUTE_ONTOLOGY.map((r) => r.canonical_route_id), account_refs: [], validation_question: "Which minimum order quantities and case packs can Amor de Gea support?" },
  { dependency_id: "importer_of_record", label: "Importer-of-record model", status: "CUSTOMER_INPUT_REQUIRED", blocking_level: "route", source: "customer_context", route_ids: ["specialty_food_beverage_import", "natural_products_distribution", "natural_specialty_grocery", "online_natural_retail"], account_refs: [], validation_question: "Will Amor de Gea appoint an importer of record or require the route partner to provide that role?" },
];
