import phase4 from "../../ml/data/opportunity-intelligence/amor_phase4_recovery_v1.checkpoint.json";
import bounded from "../../ml/data/opportunity-intelligence/amor_blueprint_v2_bounded_search_20260803_v1.checkpoint.json";
import { AMOR_PHASE4_PORTFOLIO } from "../intelligence/amor-de-gea-phase4-intelligence";

export type EntityType="buyer_account"|"retailer"|"hospitality_account"|"spa_account"|"gifting_intermediary"|"distributor"|"brand"|"manufacturer"|"product"|"article_media"|"directory"|"marketplace"|"association"|"event"|"unknown";
export type BusinessRole="potential_buyer"|"reseller"|"curator"|"hospitality_user"|"gifting_intermediary"|"distributor_buyer"|"supplier"|"brand_seeking_distribution"|"manufacturer"|"unclear";
export type VerificationState="verified"|"strongly_inferred"|"weakly_inferred"|"unknown"|"contradictory";
export type DiscoverySourcePlan={route:string;preferred:string[];discovery_evidence:string[];reject:string[]};
export type HarvestedEntity={source_url:string;source_class:string;extracted_name:string|null;extraction_method:string;candidate_domain:string;official_domain_match:boolean;route:string;confidence:number};
export type CanonicalAccountIdentity={entity_id:string;commercial_name:string;legal_name:string|null;official_domain:string|null;alternative_names:string[];social_profiles:string[];branches:string[];parent_organization:string|null;geography:string|null;route:string;entity_type:EntityType;business_role:BusinessRole;source_references:string[];identity_confidence:number;active_status:VerificationState;prior_appearance:boolean;pilot_history:string[]};

export const ACCOUNT_FIRST_PIPELINE_AUDIT={
 current_order:["commercial hypothesis","keyword query","provider result","URL/domain normalization","late entity creation","identity verification","route assignment","qualification","deep research","portfolio comparison"],
 diagnosis:"Context is compiled at qualification, but retrieval is webpage-first. Page type and buyer role are not hard gates before candidate creation, so irrelevant documents consume identity and qualification attention.",
 stages:[
  {stage:"query generation",input:"commercial mechanism",output:"keyword web query",loss:"source ecosystem unspecified",context_timing:"present in wording, not entity selection"},
  {stage:"provider request",input:"query",output:"ranked webpages",loss:"provider optimizes page relevance, not buyer entities",context_timing:"query only"},
  {stage:"result extraction",input:"webpages",output:"URLs/titles",loss:"articles, directories, products and suppliers accepted",context_timing:"absent"},
  {stage:"normalization",input:"URLs",output:"domains",loss:"page type and parent/branch semantics collapse",context_timing:"absent"},
  {stage:"entity creation",input:"domain",output:"candidate",loss:"web domain is treated as organization proxy",context_timing:"too late"},
  {stage:"identity/route",input:"candidate",output:"resolved/qualified candidate",loss:"buyer-vs-seller verification inconsistent",context_timing:"partial"},
  {stage:"deep research",input:"qualified candidate",output:"evidence",loss:"research spent on structurally invalid entities",context_timing:"active"},
  {stage:"portfolio",input:"enriched accounts",output:"prioritized accounts",loss:"strict filters rescue precision but cannot restore retrieval yield",context_timing:"fully active"},
 ],
 contamination:["editorial/article pages","directories and marketplaces as accounts","product/category pages","supplier brands seeking distributors","foreign entities","generic wellness adjacency","duplicate social/location pages","inactive or unresolved identities"],
 observed:{v1_raw:90,v1_unique_domains:56,v1_identity_verified:24,v1_qualified:18,v2_raw:39,v2_unique_domains:28,v2_identity_verified:6,v2_qualified:1},
} as const;

export const ACCOUNT_FIRST_SOURCE_MAP:DiscoverySourcePlan[]=[
 {route:"specialty_retail",preferred:["official store locators","official ecommerce category pages","brand stockist directories","reliable chamber/local listings","shopping-centre tenant directories","resolved marketplace seller profiles"],discovery_evidence:["active store","multibrand assortment","third-party retail","local/founder-led identity","replenishment model"],reject:["blogs","health articles","reviews","generic directories","MLM","brand-only pages"]},
 {route:"hospitality_spa",preferred:["official hotel directories","official hotel/spa sites","hotel associations","verified hospitality identity platforms","official amenities/wellness pages","boutique/gift-shop pages"],discovery_evidence:["real property","active spa","retail/gifting/package","third-party product use","local purchasing plausibility"],reject:["travel articles","listicles","booking page without official confirmation","spa language without business use"]},
 {route:"gifting",preferred:["official corporate-gifting catalogs","B2B gifting directories","corporate service/customization pages","curated gift-box ecommerce","employee-wellness catalogs","supplier/brand-partner pages"],discovery_evidence:["third-party curation","corporate clients","customization/co-branding","recurring programs","moderate orders"],reject:["consumer-only shops","event agencies without products","own-brand-only businesses","seasonal articles"]},
 {route:"regional_distribution",preferred:["official distributor catalogs","brand distributor pages","trade-association members","verified supplier directories","regional portfolio pages","wholesale catalogs"],discovery_evidence:["actual distributor role","third-party portfolio","relevant category","selective geography","replenishment"],reject:["brands seeking distributors","retailers mislabeled as distributors","logistics companies","mass distributors","generic B2B directories"]},
];

const text=(x:{title?:string|null;url:string;description?:string|null})=>`${x.title??""} ${x.url} ${x.description??""}`.toLowerCase();
export function classifyEntityType(input:{title?:string|null;url:string;description?:string|null;route?:string}):{label:EntityType;confidence:number;reason:string;evidence:string[];source:string}{const t=text(input),path=(()=>{try{return new URL(input.url).pathname.toLowerCase()}catch{return""}})();let label:EntityType="unknown",reason="No structural entity signal.";if(/\/blog|\/noticias|\/article|guía|ideas|cómo |ranking|mejores|news\./.test(t)){label="article_media";reason="Editorial URL/title pattern."}else if(/directory|directorio|tripadvisor|booking\.com|bookimed|tripaneer|europages|marketplace/.test(t)){label="directory";reason="Directory/booking ecosystem."}else if(/\/products?\/|producto[s]?\b/.test(path)){label="product";reason="Product page, not organization identity."}else if(/asociaci[oó]n|c[aá]mara|miembros/.test(t)){label="association";reason="Membership organization."}else if(/evento|feria|congreso/.test(t)){label="event";reason="Event entity."}else if(/hotel|hostal|resort|hospedaje/.test(t)){label="hospitality_account";reason="Hospitality business signal."}else if(/\bspa\b|centro de bienestar/.test(t)){label="spa_account";reason="Spa service signal."}else if(/regalos corporativos|gifting|cajas corporativas/.test(t)){label="gifting_intermediary";reason="Corporate gifting service signal."}else if(/distribuidor|mayorista|wholesale/.test(t)){label="distributor";reason="Wholesale/distribution signal; role still requires verification."}else if(/tienda|mercado saludable|ecommerce|comprar online|shopify|woocommerce/.test(t)){label="retailer";reason="Retail transaction signal."}else if(/fabricante|manufactur|fábrica/.test(t)){label="manufacturer";reason="Manufacturing signal."}else if(/marca|nuestros productos/.test(t)){label="brand";reason="Brand/own-product signal."}const confidence=label==="unknown"?.25:label==="article_media"||label==="directory"||label==="product"?.95:.72;return{label,confidence,reason,evidence:[input.title??"",path].filter(Boolean),source:input.url}}
export function classifyBusinessRole(input:{title?:string|null;url:string;description?:string|null;entity_type:EntityType}):{role:BusinessRole;compatible_buyer:boolean;confidence:number;reason:string}{const t=text(input);if(/sé distribuidor|se distribuidor|conviértete en distribuidor|become a distributor|distribuye nuestros|nuestros productos/.test(t))return{role:"brand_seeking_distribution",compatible_buyer:false,confidence:.96,reason:"Supplier language recruits distributors or promotes own products."};if(input.entity_type==="article_media"||input.entity_type==="directory"||input.entity_type==="product"||input.entity_type==="association"||input.entity_type==="event")return{role:"unclear",compatible_buyer:false,confidence:.95,reason:"Non-account entity cannot pass buyer gate."};if(input.entity_type==="retailer")return{role:"reseller",compatible_buyer:true,confidence:.78,reason:"Retail transaction model; third-party assortment still required."};if(input.entity_type==="hospitality_account"||input.entity_type==="spa_account")return{role:"hospitality_user",compatible_buyer:true,confidence:.72,reason:"Potential service/retail user; commercial mechanism required."};if(input.entity_type==="gifting_intermediary")return{role:"gifting_intermediary",compatible_buyer:true,confidence:.78,reason:"Potential curator; third-party physical-product curation required."};if(input.entity_type==="distributor"&&/portafolio|marcas que distribuimos|distribuimos marcas|catálogo mayorista/.test(t))return{role:"distributor_buyer",compatible_buyer:true,confidence:.74,reason:"Third-party portfolio language."};if(input.entity_type==="distributor")return{role:"unclear",compatible_buyer:false,confidence:.55,reason:"Distribution word alone does not distinguish buyer from supplier."};if(input.entity_type==="brand"||input.entity_type==="manufacturer")return{role:input.entity_type==="manufacturer"?"manufacturer":"supplier",compatible_buyer:false,confidence:.78,reason:"Own-brand/supply role lacks buyer evidence."};return{role:"unclear",compatible_buyer:false,confidence:.35,reason:"Buyer role not evidenced."}}
export function verifyBusinessModel(input:{entity_type:EntityType;role:BusinessRole;official_domain:boolean;active_signal:boolean;colombia:boolean;third_party_signal:boolean}):{state:VerificationState;may_enrich:boolean;reason:string}{if(!input.official_domain||!input.active_signal)return{state:"unknown",may_enrich:false,reason:"Official identity and activity must precede enrichment."};if(!input.colombia)return{state:"contradictory",may_enrich:false,reason:"Geography conflicts with route scope."};if(["brand_seeking_distribution","supplier","manufacturer","unclear"].includes(input.role))return{state:"contradictory",may_enrich:false,reason:"Commercial role is not a verified buyer."};if(!input.third_party_signal)return{state:"weakly_inferred",may_enrich:false,reason:"Third-party buying/curation behavior is not established."};return{state:"strongly_inferred",may_enrich:true,reason:"Identity, activity, geography, buyer role and third-party model clear structural gate."}}
export function canonicalizeAccount(input:{name:string;domain?:string|null;route:string;entity_type:EntityType;role:BusinessRole;sources:string[];geography?:string|null;parent?:string|null;branches?:string[]}):CanonicalAccountIdentity{const key=(input.domain??input.name).toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"");return{entity_id:`account_${key}`,commercial_name:input.name,legal_name:null,official_domain:input.domain??null,alternative_names:[],social_profiles:[],branches:input.branches??[],parent_organization:input.parent??null,geography:input.geography??null,route:input.route,entity_type:input.entity_type,business_role:input.role,source_references:input.sources,identity_confidence:input.domain?.length?.8:.35,active_status:input.domain?"strongly_inferred":"unknown",prior_appearance:false,pilot_history:[]}}
export function structuralAccountGate(input:{identity:CanonicalAccountIdentity;business_model:ReturnType<typeof verifyBusinessModel>;context_rules_applied:boolean;hard_rule_failures:string[]}):{passed:boolean;may_enrich:boolean;stage:string;reason:string}{if(!input.identity.official_domain)return{passed:false,may_enrich:false,stage:"identity_resolution",reason:"Official identity unresolved."};if(!input.business_model.may_enrich)return{passed:false,may_enrich:false,stage:"business_model",reason:input.business_model.reason};if(!input.context_rules_applied)return{passed:false,may_enrich:false,stage:"context_gate",reason:"Context rules must execute before enrichment."};if(input.hard_rule_failures.length)return{passed:false,may_enrich:false,stage:"context_gate",reason:`Hard failures: ${input.hard_rule_failures.join(", ")}`};return{passed:true,may_enrich:true,stage:"evidence_enrichment",reason:"Structural account gate passed."}}

export const ACCOUNT_FIRST_ORDER=["source_ecosystem","entity_harvesting","entity_classification","identity_resolution","buyer_role_verification","business_model_verification","context_structural_gate","evidence_enrichment","qualification","portfolio_comparison"] as const;
export const ACCOUNT_FIRST_STRATEGIES=[
 {id:"directory_to_official",routes:["hospitality_spa","gifting","regional_distribution"],source:"authoritative directory/association",yield:"named entities",identity_risk:"medium",buyer_relevance:"medium",provider_need:"one ecosystem locator",cost:"low",failure:"directory becomes candidate",stop:"20 harvested or 10 resolved"},
 {id:"stockist_network_mining",routes:["specialty_retail"],source:"official adjacent-brand stockist locator",yield:"retailer names/locations",identity_risk:"low-medium",buyer_relevance:"high",provider_need:"locator discovery only",cost:"low",failure:"stockist inactive or monobrand",stop:"10 official domains"},
 {id:"association_membership",routes:["hospitality_spa","regional_distribution"],source:"official association members",yield:"member businesses",identity_risk:"medium",buyer_relevance:"medium",provider_need:"association discovery",cost:"low",failure:"membership does not prove buying",stop:"20 entities"},
 {id:"catalog_entity_extraction",routes:["gifting","regional_distribution"],source:"official curated/wholesale catalog",yield:"partner brands or curator identity",identity_risk:"medium",buyer_relevance:"high after role gate",provider_need:"catalog discovery",cost:"low-medium",failure:"own-brand catalog",stop:"6 verified buyers"},
 {id:"local_cluster_discovery",routes:["specialty_retail","hospitality_spa"],source:"tenant directory/hotel collection",yield:"local named accounts",identity_risk:"medium",buyer_relevance:"medium",provider_need:"cluster locator",cost:"low",failure:"branch duplication",stop:"10 canonical parents"},
 {id:"adjacency_network",routes:["specialty_retail","gifting"],source:"official partner/stockist pages",yield:"accounts already carrying adjacent premium products",identity_risk:"low-medium",buyer_relevance:"high",provider_need:"exact ecosystem only",cost:"medium",failure:"supplier mistaken for buyer",stop:"4 qualified challengers"},
] as const;

const firstByDomain=new Map<string,{title:string|null;url:string;route:string}>();for(const q of phase4.queries)for(const c of q.candidates){let d=c.url;try{d=new URL(c.url).hostname.replace(/^www\./,"")}catch{}if(!firstByDomain.has(d))firstByDomain.set(d,{title:c.title,url:c.url,route:q.route})}
const enrichedDomains=new Set(AMOR_PHASE4_PORTFOLIO.map(x=>x.identity.official_domain));
export const ACCOUNT_FIRST_UNDER_ENRICHED_TRIAGE=Array.from(firstByDomain.entries()).filter(([domain])=>!enrichedDomains.has(domain)).slice(0,41).map(([domain,item])=>{const type=classifyEntityType(item);const role=classifyBusinessRole({...item,entity_type:type.label});const disposition=type.label==="article_media"?"article/media":type.label==="directory"||type.label==="marketplace"?"directory":type.label==="brand"?"brand":role.role==="supplier"||role.role==="brand_seeking_distribution"?"supplier":role.compatible_buyer?"likely buyer":type.label==="unknown"?"evidence missing":"likely non-buyer";return{domain,...item,entity_type:type.label,business_role:role.role,disposition,prevented_before_candidate:!role.compatible_buyer||["article_media","directory","product","unknown"].includes(type.label),reason:role.reason}});
export const ACCOUNT_FIRST_TRIAGE_SUMMARY=ACCOUNT_FIRST_UNDER_ENRICHED_TRIAGE.reduce((a,x)=>{a[x.disposition]=(a[x.disposition]??0)+1;if(x.prevented_before_candidate)a.prevented=(a.prevented??0)+1;return a},{} as Record<string,number>);

export const ACCOUNT_FIRST_QUALITY_METRICS=["entity_yield_per_source","buyer_account_rate","official_domain_resolution_rate","business_model_verification_rate","article_contamination_rate","directory_contamination_rate","brand_as_buyer_error_rate","identity_resolution_rate","context_gate_pass_rate","qualification_rate","deep_research_efficiency","cost_per_verified_buyer","time_per_verified_buyer","portfolio_challenge_rate"] as const;
export const ACCOUNT_FIRST_BASELINES={V1:{raw:90,unique_domains:56,identity_verified:24,qualified:18,context_trace_rate:0},V2:{raw:39,unique_domains:28,identity_verified:6,qualified:1,context_trace_rate:1},account_first:{status:"NOT YET TESTED",claims_allowed:false,expected:"lower contamination and higher deep-research efficiency; no superiority claim until validation"}} as const;
export const ACCOUNT_FIRST_VALIDATION_PLAN={id:"amor_account_first_validation_v1",status:"FOUNDER REVIEW",executed:false,provider_calls:0,ceilings:{source_ecosystems:4,provider_calls:4,extracted_entities:20,official_domain_resolutions:10,business_models_verified:6,qualified_challengers:4},ecosystems:[{route:"specialty_retail",strategy:"stockist_network_mining",source:"one official premium-adjacent brand stockist locator",expected:"named Colombian retailers"},{route:"hospitality_spa",strategy:"association_membership",source:"one official boutique-hotel/spa membership ecosystem",expected:"active property identities"},{route:"gifting",strategy:"catalog_entity_extraction",source:"one official B2B curated-gifting catalog/partner ecosystem",expected:"curators with physical third-party products"},{route:"regional_distribution",strategy:"association_membership",source:"one verified natural-products trade/member ecosystem",expected:"selective distributor identities"}],success:["buyer-account rate above V2","article contamination below V2","at least 4 official domains","at least 2 verified business models","no supplier-as-buyer error"],stop:["4 calls","20 entities","10 resolutions","6 verified models","source saturation","first hard provider error"],exact_cost_usd:null} as const;
export const ACCOUNT_FIRST_VERSION={id:"account-first-discovery-architecture-v1",state:"IMPLEMENTED — VALIDATION NOT AUTHORIZED",provider_calls:0,portfolio_changed:false,v3r4_created:false} as const;
