export const AMOR_PILOT1_FINAL = {
  report:{id:"amor-de-gea-pilot1-final-report-v1",filename:"Amor-de-Gea-LeadLens-Pilot-1-Final-Report.pdf",title:"AMOR DE GEA Opportunity Portfolio & Commercial Validation Plan",state:"FOUNDER REVIEW REQUIRED"},
  portfolio:{first_validation:["Éteka","Celestino Hotel Boutique & Spa","Sinergy On","Vitálica"],strategic_priority:["Ser Saludable","Masaya Collection","Natural + Mente"],investigate_selectively:["Hotel Charleston Santa Teresa Spa","Habibi Plantitas","Funat"],excluded:["BioPlaza","Distribuidora DAM","Hotel Spa La Colina","Tu Tienda Saludable","Somos Consiente"]},
  relationship_disclosure:"LeadLens no recibió confirmación de la relación comercial previa de Amor de Gea con estas cuentas. Antes de contactar, confirme si ya existe relación, conversación, exclusión o conflicto.",
  accounts:[
    {name:"Éteka",group:"Primera validación",route:"Spa / hospitalidad",why:"Su propuesta pública de spa permite explorar un ritual de bienestar o regalo para huéspedes.",test:"Validar un único caso de uso con 50 unidades.",unknown:"No está confirmado que compre productos de terceros ni quién decide.",next:"Confirmar modelo de retail/regalo, responsable de compra y manejo de vidrio."},
    {name:"Celestino Hotel Boutique & Spa",group:"Primera validación",route:"Hotel boutique / spa",why:"La combinación hotel boutique y spa crea una hipótesis concreta de regalo o venta complementaria.",test:"Probar una referencia en una propiedad y medir aceptación.",unknown:"No se verificó retail de terceros ni frecuencia de reposición.",next:"Confirmar área compradora, caso de uso y cadencia potencial."},
    {name:"Sinergy On",group:"Primera validación",route:"Regalos corporativos",why:"Su oferta pública de soluciones corporativas permite evaluar un producto terminado dentro de un kit.",test:"Presentar un kit muestra para un brief compatible.",unknown:"No hay evidencia de un proyecto activo ni de aceptación del formato.",next:"Validar brief, volumen, plazo, personalización y economía."},
    {name:"Vitálica",group:"Primera validación",route:"Retail natural",why:"El surtido natural visible permite contrastar un formato botánico líquido diferenciado.",test:"Proponer un surtido mixto pequeño y medir rotación.",unknown:"Margen, onboarding y desempeño de líquidos no están confirmados.",next:"Preguntar por categoría, documentación, margen y reposición."},
    {name:"Ser Saludable",group:"Prioridad estratégica",route:"Retail bienestar",why:"La operación pública en bienestar sugiere afinidad estructural para una prueba acotada.",test:"Validar encaje de posicionamiento y una prueba de baja exposición.",unknown:"Apertura de categoría, comprador y requisitos documentales.",next:"Confirmar lenguaje no médico, documentación y proceso de alta."},
    {name:"Masaya Collection",group:"Prioridad estratégica",route:"Hospitalidad",why:"Su presencia en hospitalidad ofrece una plataforma para explorar gifting o experiencia de huésped.",test:"Diseñar una prueba en una sola propiedad antes de escalar.",unknown:"No se verificó compra de terceros, autonomía local ni encaje de 50 unidades.",next:"Identificar propiedad, caso de uso y nivel de decisión."},
    {name:"Natural + Mente",group:"Prioridad estratégica",route:"Retail / fitoterapia",why:"El ecommerce activo y categorías de fitoterapia muestran adyacencia de surtido multimarcas.",test:"Evaluar una prueba pequeña con posicionamiento seguro.",unknown:"Acceso comprador, margen, premiumización y recompra.",next:"Confirmar onboarding, comparación de precio y criterios de rotación."},
    {name:"Hotel Charleston Santa Teresa Spa",group:"Investigar selectivamente",route:"Lujo / spa",why:"Los rituales de spa visibles justifican una validación de alto nivel como referencia de mercado.",test:"Explorar solo si existe patrocinador operativo para una prueba pequeña.",unknown:"Procurement puede ser complejo y no hay retail de terceros confirmado.",next:"Validar autonomía del spa, canal de compra y tamaño mínimo."},
    {name:"Habibi Plantitas",group:"Investigar selectivamente",route:"Regalos corporativos",why:"La oferta pública de regalos personalizados abre una hipótesis para integrar un producto terminado.",test:"Probar compatibilidad en un kit estacional o corporativo.",unknown:"Aceptación de ingeribles, volumen y recurrencia.",next:"Confirmar manejo de producto, temporadas, personalización y margen."},
    {name:"Funat",group:"Investigar selectivamente",route:"Botánicos / benchmark",why:"Su catálogo botánico aporta aprendizaje de categoría y una posible afinidad comercial.",test:"Determinar primero si existe espacio no competitivo para terceros.",unknown:"Apertura a marcas externas y solapamiento competitivo.",next:"Validar rol comercial, política de terceros y diferenciación."}],
  feedback:{id:"amor-de-gea-pilot1-feedback-v1",version:"1.0",state:"ready_for_delivery",delivered:false,response_status:"Awaiting client feedback.",respondent:null,response_date:null,responses:[]},
  closure:{state:"FOUNDER REVIEW REQUIRED",blockers:["Revisión manual de los 17 controles","Confirmación manual de envío","Retroalimentación real pendiente"],delivered:false},
  pilot2:{id:"amor-de-gea-pilot2-planned-v1",state:"PLANNED — NOT AUTHORIZED",accounts:[],account_memory:["Éteka","Celestino Hotel Boutique & Spa","Sinergy On","Vitálica","Ser Saludable","Masaya Collection","Natural + Mente","Hotel Charleston Santa Teresa Spa","Habibi Plantitas","Funat","BioPlaza","Distribuidora DAM","Hotel Spa La Colina","Tu Tienda Saludable","Somos Consiente"],repeat_suppression:true},provider_calls:0} as const;
export const AMOR_PILOT1_FOUNDER_CHECKLIST=["Final portfolio reviewed","Executive conclusion reviewed","Commercial Readiness reviewed","Market Opportunity Map reviewed","Ten account summaries reviewed","Four Action Briefs reviewed","What Changed reviewed","30–60 day plan reviewed","Limitations reviewed","Claims safety reviewed","Evidence citations reviewed","Page layout reviewed","Feedback document reviewed","Customer email reviewed","Presentation agenda reviewed","Filenames verified","Download links verified"].map((label,index)=>({id:`founder-${index+1}`,label,checked:false}));
export const AMOR_PILOT1_EMAIL={sent:false,subject:"Resultados del Piloto 1 de LeadLens — Amor de Gea",body:`Hola Juliana,\n\nYa finalizamos el primer piloto de LeadLens para Amor de Gea.\n\nA partir de la información que nos compartieron, revisamos y ajustamos la búsqueda para priorizar cuentas más compatibles con el momento comercial, la capacidad, los formatos y las rutas que Amor de Gea puede explorar actualmente.\n\nAdjuntamos:\n\n1. El reporte final del piloto.\n2. Los Account Action Briefs de las cuentas recomendadas para la primera validación.\n3. Un documento breve de retroalimentación.\n\nEl reporte presenta las cuentas que recomendamos validar primero, las razones detrás de cada selección, las principales oportunidades por ruta y la información que todavía conviene confirmar antes de iniciar conversaciones.\n\nLa retroalimentación será especialmente importante para revisar qué cuentas ya conocen, cuáles consideran más relevantes y qué debería mejorar LeadLens en un segundo ciclo.\n\nMuchas gracias por la confianza y por la información compartida durante este primer piloto.\n\nQuedo atento a sus comentarios.\n\nMartín Galeano\nLeadLens`};
export const AMOR_PILOT1_AGENDA=["Contexto de Amor de Gea y qué cambió — 5 min","Mapa de oportunidades — 5 min","Portafolio y primera secuencia — 10 min","Cuatro Action Briefs — 10–15 min","Plan de validación recomendado — 5 min","Feedback y prioridades del Piloto 2 — 5 min"];
