import { AMOR_PHASE4_PORTFOLIO, AMOR_PHASE4_RUN } from "./amor-de-gea-phase4-intelligence";

export const AMOR_PHASE45_REVIEW_VERSION = { id:"amor-de-gea-v3r-founder-review", version:"V3R", reviewer:"LeadLens internal evidence audit", reviewed_at:"2026-08-03T20:00:00.000Z", preserves:"V3 controlled-search proposal", state:"founder_decision_pending", customer_safe:false, provider_calls:0 } as const;
type Verdict="APPROVE — WORK FIRST"|"APPROVE — PRIORITY"|"APPROVE — INVESTIGATE"|"APPROVE — MONITOR"|"NEEDS EVIDENCE"|"REVISE"|"REJECT";
type Decision={verdict:Verdict;final_group:string;confidence:"high"|"medium"|"low";reason:string;counterevidence:string;uncertainty:string;next_validation:string;comparative_value:string;action_brief:string};
const decisions:Record<string,Decision>={
 "Hotel Spa La Colina":{verdict:"NEEDS EVIDENCE",final_group:"hold",confidence:"low",reason:"The mechanism is specific, but persisted evidence only says the identity was previously verified and does not establish a current official spa or retail offer.",counterevidence:"Current retail behavior and active spa offer are unverified.",uncertainty:"Whether the account is active under the same identity and can replenish third-party products.",next_validation:"Revisit the captured official URL to confirm active identity, spa offer, buyer function and retail/gifting behavior.",comparative_value:"Potential boutique-hospitality test, but Éteka and Celestino have stronger official evidence.",action_brief:"ready after minor evidence repair"},
 "Éteka":{verdict:"APPROVE — WORK FIRST",final_group:"work_first",confidence:"medium",reason:"A current official spa page supports a bounded ritual-linked retail or guest-gift test with a plausible buyer path.",counterevidence:"No evidence of third-party product retail.",uncertainty:"Whether retail, gifting, glass handling and safe copy are operationally acceptable.",next_validation:"Confirm one operational use case, purchasing ownership and a 50-unit test.",comparative_value:"Provides fresher, differentiated hospitality evidence.",action_brief:"ready"},
 "Celestino Hotel Boutique & Spa":{verdict:"APPROVE — WORK FIRST",final_group:"work_first",confidence:"medium",reason:"Official boutique-hotel and spa evidence supports a concrete guest-gift or boutique-retail transaction hypothesis.",counterevidence:"No verified third-party product retail behavior.",uncertainty:"Decision ownership and frequency of product consumption.",next_validation:"Confirm buyer area, retail/gifting use and replenishment cadence.",comparative_value:"Complements Éteka with a Medellín property and manageable scope.",action_brief:"ready"},
 "Natural + Mente":{verdict:"NEEDS EVIDENCE",final_group:"hold",confidence:"low",reason:"Retail replenishment is plausible, but current V3 evidence is inherited and does not describe an active comparable assortment.",counterevidence:"Comparable liquids, buyer path and current assortment are unknown.",uncertainty:"Whether the correct active company accepts third-party premium botanicals.",next_validation:"Revisit the captured official domain and verify identity, assortment, geography and buyer route.",comparative_value:"Vitálica and Ser Saludable have stronger current evidence.",action_brief:"not ready"},
 "Sinergy On":{verdict:"APPROVE — WORK FIRST",final_group:"work_first",confidence:"medium",reason:"Official customized corporate-kit activity supports a concrete component-supply transaction and bounded sample-kit test.",counterevidence:"Private-label expectations, seasonality and customization economics are unknown.",uncertainty:"Whether finished/co-branded bottles fit a live client brief and viable lead time.",next_validation:"Confirm one active brief, volume, co-branding scope, economics and lead time.",comparative_value:"Adds the clearest non-retail route and tests project orders.",action_brief:"ready"},
 "Vitálica":{verdict:"APPROVE — WORK FIRST",final_group:"work_first",confidence:"medium",reason:"An active official Colombian natural-products ecommerce supports a small assortment test and observable reorder mechanism.",counterevidence:"Its supplement-heavy assortment may reject Amor de Gea’s format.",uncertainty:"Comparable liquids, onboarding burden and category openness.",next_validation:"Confirm buyer access, comparable products, margins and a mixed 50-unit pilot.",comparative_value:"Strongest evidence-backed specialty-retail learning account.",action_brief:"ready; replacement for Hotel Spa La Colina"},
 "Ser Saludable":{verdict:"APPROVE — PRIORITY",final_group:"priority",confidence:"medium",reason:"Official natural-medicine and wellness assortment supports a replenishable retail test.",counterevidence:"Health-oriented positioning may create claims and documentation friction.",uncertainty:"Acceptance of non-medical positioning and liquid format.",next_validation:"Confirm buyer, assortment, documentation and safe-positioning requirements.",comparative_value:"Complements Vitálica in a more health-oriented context.",action_brief:"not in first sequence"},
 "BioPlaza":{verdict:"APPROVE — PRIORITY",final_group:"priority",confidence:"medium",reason:"Established natural retail offers meaningful multi-channel learning and a clear replenishment mechanism.",counterevidence:"Centralized procurement, competition and scale may exceed readiness.",uncertainty:"Onboarding threshold, category gap, economics and opening volume.",next_validation:"Confirm buyer route and whether a staged Tier 1–2 pilot is possible.",comparative_value:"Higher-scale learning, but not first-sequence accessibility.",action_brief:"not in first sequence"},
 "Masaya Collection":{verdict:"APPROVE — PRIORITY",final_group:"priority",confidence:"medium",reason:"Fresh official collection evidence supports a property-level guest-gift or curated-experience pilot.",counterevidence:"Retail behavior and decision centralization are unverified.",uncertainty:"Whether one property can authorize recurring inventory use.",next_validation:"Confirm property authority, exact use case, replenishment and conflict.",comparative_value:"Tests property-to-collection scalability.",action_brief:"not in first sequence"},
 "Hotel Charleston Santa Teresa Spa":{verdict:"APPROVE — INVESTIGATE",final_group:"investigate",confidence:"medium",reason:"Official spa rituals establish relevance, but luxury-hotel procurement makes it less accessible than boutique alternatives.",counterevidence:"Complex procurement and no visible third-party retail behavior.",uncertainty:"Buyer route, onboarding, safe claims and pilot-size fit.",next_validation:"Confirm third-party product model and whether spa management can sponsor a test.",comparative_value:"Useful high-end benchmark; inferior to Éteka and Celestino for first attention.",action_brief:"not ready"},
 "Tu Tienda Saludable":{verdict:"NEEDS EVIDENCE",final_group:"hold",confidence:"low",reason:"The retail mechanism is concrete, but persisted evidence lacks current assortment and identity depth.",counterevidence:"Differentiation and active buyer access are not evidenced.",uncertainty:"Current activity, comparable assortment and economics.",next_validation:"Revisit the official URL to verify active identity, assortment and purchasing route.",comparative_value:"Currently weaker than Vitálica and Ser Saludable.",action_brief:"not ready"},
 "Funat":{verdict:"APPROVE — MONITOR",final_group:"monitor",confidence:"medium",reason:"Fresh official botanical assortment is relevant, but its own-brand position may make Amor de Gea a competitor.",counterevidence:"Cannibalization, private-brand bias and complex onboarding.",uncertainty:"Whether third-party differentiated brands are accepted.",next_validation:"Confirm third-party assortment policy before founder attention.",comparative_value:"Valuable competitive benchmark rather than immediate target.",action_brief:"not ready"},
 "Habibi Plantitas":{verdict:"APPROVE — INVESTIGATE",final_group:"investigate",confidence:"medium",reason:"Official nationwide personalized gifting supports a bounded kit-component hypothesis.",counterevidence:"Visible assortment centers on plants and lifestyle gifts, not ingestible wellness products.",uncertainty:"Category openness, handling, economics and repeat demand.",next_validation:"Confirm acceptance of sealed wellness products, volumes and lead times.",comparative_value:"Complements Sinergy On by testing broader gifting fit.",action_brief:"ready after minor evidence repair"},
 "Distribuidora DAM":{verdict:"APPROVE — MONITOR",final_group:"monitor",confidence:"low",reason:"The distribution mechanism is coherent, but economics, capacity and opening-volume compatibility remain unresolved.",counterevidence:"Likely procurement burden and scale mismatch.",uncertainty:"Territory, margin, minimum order, portfolio requirements and conflict.",next_validation:"Validate economics and staged territory before product discussion.",comparative_value:"Retained only as a route-learning benchmark.",action_brief:"not ready"},
 "Somos Consiente":{verdict:"REJECT",final_group:"rejected",confidence:"medium",reason:"The persisted thesis does not establish a repeatable purchasing transaction beyond generic collaboration alignment.",counterevidence:"No evidenced recurring order logic, active model or differentiated buyer path.",uncertainty:"Whether any commercial purchase mechanism exists.",next_validation:"Do not research now; reconsider only if a recurring procurement use case appears.",comparative_value:"Inferior to Sinergy On and Habibi because it adds no evidenced transaction mechanism.",action_brief:"not ready"}
};
export const AMOR_PHASE45_ACCOUNT_REVIEWS=AMOR_PHASE4_PORTFOLIO.map(account=>{const review=decisions[account.identity.commercial_name];if(!review)throw new Error(`Missing V3R review for ${account.identity.commercial_name}`);return{review_id:`${account.portfolio_id}:v3r`,account:account.identity.commercial_name,current_group:account.bucket,route:account.route,opportunity_mechanism:account.opportunity_mechanism,official_domain:account.identity.official_domain,geography:account.identity.geography,identity_state:account.identity.activity_state,evidence:account.evidence,timing:account.timing,buyer_path:account.opportunity_mechanism.likely_buying_function,operational_test:account.opportunity_mechanism.initial_test,conflict_check:{required:true,active_client:false,current_negotiation:false,channel_conflict:false,exclusion_requested:false,confirmation_state:"founder_confirmation_required"},founder_control:"pending",historical_v3_preserved:true,...review}});
export const AMOR_PHASE45_ROUTE_REVIEW=[
 {route:"hospitality_spa",found:5,surviving:4,evidence_quality:"moderate–strong",mechanism_strength:"strong but use case unverified",buyer_path:"moderate",procurement:"moderate to high",repeat:"plausible",operational_fit:"good for bounded property tests",contradiction:"No account proves third-party retail or repeat demand.",learning:"Test one concrete spa-retail or guest-gift use.",conclusion:"partially supported"},
 {route:"specialty_retail",found:5,surviving:4,evidence_quality:"uneven",mechanism_strength:"strong and observable",buyer_path:"moderate–strong",procurement:"low to high",repeat:"strongest structural mechanism",operational_fit:"good for approximately 50 units",contradiction:"Three inherited accounts lack current assortment depth.",learning:"Measure onboarding, sell-through and reorder.",conclusion:"supported as easiest test route"},
 {route:"gifting",found:3,surviving:2,evidence_quality:"moderate",mechanism_strength:"promising but project-dependent",buyer_path:"moderate",procurement:"moderate",repeat:"seasonal/uncertain",operational_fit:"conditioned by customization",contradiction:"Category openness and repeat cadence are not evidenced.",learning:"Test finished/co-branded product in one live brief.",conclusion:"partially supported"},
 {route:"regional_distribution",found:1,surviving:1,evidence_quality:"low",mechanism_strength:"conditioned",buyer_path:"low",procurement:"high",repeat:"plausible only after listing",operational_fit:"unresolved",contradiction:"Capacity, margin and opening volume may be incompatible.",learning:"Determine whether distribution is premature.",conclusion:"most conditioned"}
] as const;
export const AMOR_PHASE45_PACKET={version:AMOR_PHASE45_REVIEW_VERSION,run_id:AMOR_PHASE4_RUN.run_id,proposed:15,approved_candidates:11,needs_evidence:3,revised:0,rejected:1,final_recommended_portfolio_size:11,work_first:["Éteka","Celestino Hotel Boutique & Spa","Sinergy On","Vitálica"],priority:["Ser Saludable","BioPlaza","Masaya Collection"],investigate_monitor:["Hotel Charleston Santa Teresa Spa","Habibi Plantitas","Funat","Distribuidora DAM"],hold:["Hotel Spa La Colina","Natural + Mente","Tu Tienda Saludable"],rejected_accounts:["Somos Consiente"],main_strength:"Specific, testable transactions across hospitality, retail and gifting.",main_weakness:"No account has buying timing or observed repeat behavior; inherited baseline evidence is uneven.",founder_decision:"Approve, revise or reject each V3R verdict and complete all four conflict confirmations per account.",strongest_route:"Hospitality/spa remains differentiated but only partially supported; specialty retail is currently easier to test.",most_conditioned_route:"Regional distribution remains most conditioned.",redundancy:"Hospitality is not excessive after one hold; retail has three evidence holds; gifting needs only two differentiated tests. No route quota was enforced.",action_briefs_ready:["Éteka","Celestino Hotel Boutique & Spa","Sinergy On","Vitálica"],action_briefs_repair:["Hotel Spa La Colina","Habibi Plantitas"],action_briefs_not_ready:["Natural + Mente"],proposed_replacement:"Replace Hotel Spa La Colina with Vitálica in the first Action Brief sequence pending evidence repair.",narrow_repair_lookups_proposed:[{account:"Hotel Spa La Colina",gap:"Current identity, spa offer and retail behavior",query:"site:hotelspalacolina.com spa tienda productos bienestar",expected_source:"Captured official domain",provider_calls:1},{account:"Natural + Mente",gap:"Current assortment and third-party retail behavior",query:"site:naturalmente.com.co productos extractos bienestar tienda",expected_source:"Captured official domain",provider_calls:1},{account:"Tu Tienda Saludable",gap:"Current identity, assortment and buyer fit",query:"site:tutiendasaludable.com extractos líquidos bienestar",expected_source:"Captured official domain",provider_calls:1}],provider_calls_consumed:0,migration_required:false,customer_safe:false,final_report_created:false,outreach_started:false,crm_created:false,phase5_authorized:false} as const;
