import repair from "../../ml/data/opportunity-intelligence/amor_phase4_6_evidence_repair_v1.checkpoint.json";
import { AMOR_PHASE45_ACCOUNT_REVIEWS, AMOR_PHASE45_REVIEW_VERSION } from "./amor-de-gea-phase4-5-review";
const byName=(name:string)=>{const account=AMOR_PHASE45_ACCOUNT_REVIEWS.find(x=>x.account===name);if(!account)throw new Error(`Missing account ${name}`);return account};
export const AMOR_PHASE46_REPAIR_RUN={run_id:repair.run_id,state:repair.state,provider:repair.provider,call_ceiling:repair.call_ceiling,actual_calls:repair.actual_calls,exact_cost_usd:repair.exact_cost_usd,total_historical_calls:30+repair.actual_calls,operations:repair.operations} as const;
export const AMOR_PHASE46_REPAIRS=[
 {account:"Hotel Spa La Colina",original_thesis:byName("Hotel Spa La Colina").opportunity_mechanism.use,gap:"Current official spa, retail and recurring-use evidence",query:repair.operations[0].query,sources:repair.operations[0].results.map(x=>x.url),facts:["Official active site describes a romantic Eje Cafetero hotel with outdoor spa, accommodation and experiences."],counterevidence:"No official retail, gift-shop, third-party product or replenishment behavior was found.",unchanged_uncertainty:"Whether the property purchases third-party wellness inventory repeatedly.",mechanism_impact:"Active spa identity is resolved, but the recurring product transaction remains inferred.",buyer_impact:"Local hotel/spa management is plausible; purchasing ownership is not evidenced.",comparative_impact:"Still weaker than Éteka and Celestino, which already cover the same learning route.",verdict:"NEEDS EVIDENCE",confidence:"medium"},
 {account:"Natural + Mente",original_thesis:byName("Natural + Mente").opportunity_mechanism.use,gap:"Active assortment, third-party behavior and retail identity",query:repair.operations[1].query,sources:repair.operations[1].results.map(x=>x.url),facts:["Official active WooCommerce product page lists a Natural Medy 500 ml product.","Official navigation exposes fitoterapia, nutrición and multiple laboratory/brand categories including UPN and Proscience."],counterevidence:"The visible catalog is health/sports oriented; acceptance of Amor de Gea positioning and economics is unverified.",unchanged_uncertainty:"Buyer access, premium-format fit, onboarding and margin.",mechanism_impact:"Third-party multi-brand retail behavior materially strengthens the sell-through and reorder hypothesis.",buyer_impact:"Category/purchasing function is plausible through an active ecommerce operation.",comparative_impact:"Adds an independent multi-brand fitoterapia retailer beyond Vitálica and Ser Saludable.",verdict:"REINSTATE — PRIORITY",confidence:"medium"},
 {account:"Tu Tienda Saludable",original_thesis:byName("Tu Tienda Saludable").opportunity_mechanism.use,gap:"Differentiation, active catalog and third-party behavior",query:repair.operations[2].query,sources:repair.operations[2].results.map(x=>x.url),facts:["Official active WooCommerce product page shows an in-stock Omnilife supplement and ecommerce checkout.","Visible branding and related products are strongly centered on Omnilife."],counterevidence:"The captured evidence supports an Omnilife-focused reseller, not a differentiated multi-brand buyer for Amor de Gea.",unchanged_uncertainty:"Whether unrelated third-party brands are accepted and whether the identity has independent purchasing authority.",mechanism_impact:"Active retail is resolved, but comparative differentiation and third-party openness are weakened.",buyer_impact:"A store owner/operator is plausible, but the portfolio relationship may constrain buying.",comparative_impact:"Inferior to Vitálica, Ser Saludable and Natural + Mente for the same retail learning objective.",verdict:"REJECT",confidence:"medium"},
] as const;

export const AMOR_PHASE46_VERSION={id:"amor-de-gea-v3r2-founder-approved-internal",version:"V3R2",created_at:"2026-08-03T20:10:00.000Z",supersedes_review:AMOR_PHASE45_REVIEW_VERSION.id,preserves:["V3","V3R"],state:"founder_approved_internal_candidate",customer_safe:false,phase5_authorized:false} as const;
const workFirst=["Éteka","Celestino Hotel Boutique & Spa","Sinergy On","Vitálica"];
const priority=["Ser Saludable","BioPlaza","Masaya Collection","Natural + Mente"];
const investigateMonitor=["Hotel Charleston Santa Teresa Spa","Habibi Plantitas","Funat","Distribuidora DAM"];
export const AMOR_PHASE46_PORTFOLIO={version:AMOR_PHASE46_VERSION,approved_internal_accounts:[...workFirst,...priority,...investigateMonitor],work_first:workFirst,priority,investigate_monitor:investigateMonitor,evidence_pending:["Hotel Spa La Colina"],rejected:["Somos Consiente","Tu Tienda Saludable"],size:12,founder_approval:{actor:"founder",state:"approved_provisional_internal",scope:"V3R decisions plus Vitálica replacement",recorded_at:"2026-08-03T20:10:00.000Z"},conflict_check_state:"pending",customer_safe:false} as const;

const brief=(name:string,angle:string,offer:string,questions:string[],objections:string[],materials:string[])=>{const a=byName(name);return{brief_id:`${a.review_id}:internal-action-brief-draft`,account:name,state:"ready_after_conflict_check",internal_only:true,customer_safe:false,identity:{domain:a.official_domain,geography:a.geography,activity:a.identity_state},executive_opportunity:{why:a.comparative_value,route:a.route,archetype:a.opportunity_mechanism.use,primary_use_case:a.opportunity_mechanism.use,initial_test:a.operational_test,repeat:a.opportunity_mechanism.repeat_purchase},account_context:{official_evidence:a.evidence.facts,visible_offering:a.evidence.facts[0].claim},mechanism:{offer:a.opportunity_mechanism.offer,use:a.opportunity_mechanism.use,buying_function:a.buyer_path,centralization:"unverified",initial_order:a.operational_test,repeat:a.opportunity_mechanism.repeat_purchase,upside:a.comparative_value,rejection_risk:a.counterevidence},entry:{probable_function:a.buyer_path,route:"Use the official business channel to validate the buying function; do not contact a named person without verification.",official_channel:a.official_domain,procurement:"unverified",conflict_check:"required",validate_before_contact:a.next_validation},pre_meeting:{angle,offer,questions,objections,materials,next_action:"Complete conflict check, then validate the named unknowns before any outreach authorization."},integrity:{facts:a.evidence.facts,signals:a.evidence.signals,inferences:a.evidence.inferences,counterevidence:a.counterevidence,uncertainty:a.uncertainty,confidence:a.confidence},timing:"NO TIMING EVIDENCE",named_buyer:null}};
export const AMOR_PHASE46_ACTION_BRIEFS=[
 brief("Éteka","Position one safe, bounded botanical ritual complement—not a medical claim.","50-unit spa retail or guest-gift test",["Do you retail third-party wellness products?","Which guest ritual can use a sealed 50 ml product?","Who owns spa purchasing?","What replenishment cadence is realistic?"],["No retail model","Glass handling","Claims risk","Supplier onboarding"],["Finished-product samples","Safe-copy sheet","Wholesale terms","Packaging dimensions"]),
 brief("Celestino Hotel Boutique & Spa","Connect one product to guest gifting or boutique resale around existing wellness amenities.","Bounded 50-unit single-use-case pilot",["Is there boutique or guest-gift inventory?","Who owns the decision?","Which amenity creates recurring use?","Can one property test independently?"],["No third-party retail","Low consumption frequency","Procurement uncertainty"],["Product collection","Guest-gift concept","Safe-use copy","Pilot economics"]),
 brief("Sinergy On","Offer Amor de Gea as a finished premium wellness component inside a live corporate brief.","One sample kit and bounded co-branded project",["Is there a suitable live brief?","What volumes and lead times apply?","Is finished-product co-branding accepted?","How often do wellness briefs recur?"],["Private label required","Seasonality","Customization cost","Lead time"],["Sample kit","Co-branding options","Volume tiers","Lead-time sheet"]),
 brief("Vitálica","Test differentiated premium botanical liquids beside the current natural-products assortment.","Mixed 50-unit retail assortment",["Which comparable liquids already sell?","Who owns category onboarding?","What margin and documentation are required?","How is sell-through measured?"],["Format mismatch","Assortment competition","Claims requirements","Margin"],["Samples","Product data sheet","Safe positioning","Wholesale and replenishment terms"]),
] as const;
export const AMOR_PHASE46_CONFLICT_PACKAGE={package_id:"amor-de-gea-v3r2-conflict-check",state:"ready_not_sent",instructions:"For each account choose one relationship state and add an optional note. This package contains no internal ranking, counterevidence, provider or confidence data.",allowed_states:["not known","known but never contacted","previously contacted","active conversation","current client","former client","existing partner","conflict or exclusion","interested in exploring","not interested"],accounts:[...AMOR_PHASE46_PORTFOLIO.approved_internal_accounts,"Hotel Spa La Colina"].map(account=>({account,relationship_state:null,note:""})),sensitive_internal_logic_exposed:false,sent:false} as const;
export const AMOR_PHASE46_BLOCKERS=["Conflict check unanswered","Founder has not reviewed V3R2 repair outcomes","No customer-safe evidence review","No Phase 5 activation event","No buying timing evidence"] as const;
