import bioplaza from "../../ml/data/opportunity-intelligence/amor_phase5a1_bioplaza_confirmation_v1.json";
import { AMOR_PHASE5A_ACTION_BRIEFS, AMOR_PHASE5A_CONFLICT_REQUEST, AMOR_PHASE5A_EVIDENCE_GATES, AMOR_PHASE5A_REPORT_BLUEPRINT, AMOR_PHASE5A_VERSION } from "./amor-de-gea-phase5a-customer-safe";
export const AMOR_PHASE5A1_VERSION={id:"amor-de-gea-v4d1-founder-signed-customer-safe-draft",version:"V4D.1",created_at:"2026-08-03T20:40:00.000Z",preserves:AMOR_PHASE5A_VERSION.id,state:"READY FOR CLIENT CONFLICT CHECK — NOT READY FOR FINAL DELIVERY",founder_signoff:{actor:"founder",state:"FOUNDER APPROVED AS DRAFT — BLOCKED BY CLIENT CONFLICT CHECK AND FINAL CUSTOMER-SAFE VALIDATION",approved_at:"2026-08-03T20:40:00.000Z"},client_answers:0,final_report_generated:false,commercial_activation:false} as const;
const revisions=[
 {account:"Ser Saludable",original:"Official wellness assortment supports a replenishable retail test.",risk:"Could imply verified effects, regulatory suitability or demonstrated commercial openness.",revised:"La evidencia pública muestra un comercio activo con categorías de bienestar. Presenta afinidad estructural con Amor de Gea, pero LeadLens recomienda validar posicionamiento no médico, documentación, comprador y apertura a la categoría.",evidence_retained:"Public wellness assortment.",inference_retained:"A bounded retail test may be plausible.",claim_removed:"Regulatory suitability, need and willingness to list.",uncertainty:"Category openness, buyer path and documentation.",state:"SAFE AFTER CONFLICT CHECK"},
 {account:"Natural + Mente",original:"Active multi-brand ecommerce and fitoterapia strengthen the sell-through hypothesis.",risk:"Could imply buyer accessibility, premium fit or proven repeat purchasing.",revised:"La evidencia pública muestra ecommerce activo, categorías de fitoterapia y presencia de distintos laboratorios. Existe una hipótesis comercial plausible de afinidad de surtido; precio, acceso comprador y recurrencia deben validarse.",evidence_retained:"Active ecommerce, fitoterapia and multiple laboratory categories.",inference_retained:"Assortment adjacency may support a retail validation.",claim_removed:"Accessible buyer, premium acceptance and proven reorder.",uncertainty:"Margin, onboarding, positioning and repeat demand.",state:"SAFE AFTER CONFLICT CHECK"},
 {account:"Habibi Plantitas",original:"Nationwide personalized gifting supports a bounded kit-component hypothesis.",risk:"Could imply demonstrated interest in ingestible wellness products.",revised:"La evidencia pública muestra una oferta de regalos corporativos personalizados. Podría existir un caso de uso para un producto terminado de bienestar dentro de un kit; la apertura a esta categoría, los volúmenes y la recurrencia siguen por validar.",evidence_retained:"Public personalized corporate-gifting offer.",inference_retained:"A sealed product may fit a future kit.",claim_removed:"Category acceptance and active project demand.",uncertainty:"Product handling, economics, volume and seasonality.",state:"SAFE AFTER CONFLICT CHECK"},
 {account:"Funat",original:"Fresh botanical assortment is relevant, with competitive benchmark value.",risk:"Could imply third-party brand acceptance or supplier readiness.",revised:"La evidencia pública muestra un catálogo propio de productos botánicos. La cuenta aporta valor comparativo y podría existir afinidad de categoría, pero LeadLens recomienda validar si acepta marcas de terceros y si existe un caso comercial no competitivo.",evidence_retained:"Public botanical catalog.",inference_retained:"Category adjacency has learning value.",claim_removed:"Third-party openness and buying readiness.",uncertainty:"Competitive overlap, onboarding and commercial role.",state:"SAFE AFTER CONFLICT CHECK"},
] as const;
export const AMOR_PHASE5A1_WORDING_REVISIONS=revisions;
export const AMOR_PHASE5A1_SOURCE_CONFIRMATIONS=[
 {account:"BioPlaza",official_url:"https://bioplaza.org/",source_type:"official_domain",source_date:null,retrieved_at:"2026-08-03",provider_calls:bioplaza.provider_calls,verified_facts:[],unsupported_removed:["Current active ecommerce","Current multibrand assortment","Procurement compatibility"],remaining_inference:"Previously verified natural-retail adjacency remains an internal hypothesis.",uncertainty:"Official domain returned HTTP 500 and the single narrow provider confirmation returned no official result.",customer_safe_claim:"BioPlaza may remain internally relevant, but current operating and assortment claims require official confirmation before delivery.",blocked_claim:"Active current catalog, multibrand behavior or purchasing openness.",status:"STILL REQUIRES SOURCE CONFIRMATION",conflict_check:"pending_client_check"},
 {account:"Distribuidora DAM",official_url:"https://distribuidoradam.com/",source_type:"official_domain",source_date:null,retrieved_at:"2026-08-03",provider_calls:0,verified_facts:["Official domain returned HTTP 200.","Official title identifies Distribuidora DAM as a wholesale distributor of healthy products.","The site exposes an active official business and contact surface."],unsupported_removed:["Selective-distribution compatibility","Acceptable margin","Onboarding willingness","Available capacity"],remaining_inference:"A selective regional-distribution hypothesis may be worth monitoring, subject to scale and economics.",uncertainty:"Geographic coverage, category detail, volumes, margins and selective-fit remain unverified.",customer_safe_claim:"La evidencia pública muestra una operación mayorista de productos saludables; LeadLens recomienda validar escala, cobertura y requisitos antes de considerar una prueba.",blocked_claim:"Willingness, buyer interest, margins, onboarding or capacity.",status:"SAFE AFTER CONFLICT CHECK",conflict_check:"pending_client_check"},
] as const;
export const AMOR_PHASE5A1_EVIDENCE_GATES=AMOR_PHASE5A_EVIDENCE_GATES.map(g=>{if(revisions.some(x=>x.account===g.account)||g.account==="Distribuidora DAM")return{...g,gate:"safe after conflict check",reason:g.account==="Distribuidora DAM"?AMOR_PHASE5A1_SOURCE_CONFIRMATIONS[1].customer_safe_claim:revisions.find(x=>x.account===g.account)!.revised,correction:"Conflict check plus final founder review."};return g});
export const AMOR_PHASE5A1_ACTION_BRIEFS=AMOR_PHASE5A_ACTION_BRIEFS.map(x=>({...x,status:"READY AFTER CONFLICT CHECK",customer_safe_ready:false,published:false,next_step:"Pending Amor de Gea relationship and conflict confirmation."}));
export const AMOR_PHASE5A1_HANDOFF={title:"Validación de relaciones comerciales — Piloto LeadLens",purpose:"Esta revisión permite evitar recomendar empresas que Amor de Gea ya conoce, con las que tenga conversaciones activas o que prefiera excluir. Completarla no inicia ningún contacto ni compromete ninguna acción comercial.",instructions:"Para cada empresa, seleccione la opción que mejor describa la relación actual. Agregue una nota únicamente cuando sea útil.",accounts:AMOR_PHASE5A_CONFLICT_REQUEST.answers.map(x=>x.account),return_instructions:"Devuelva el archivo completo incluyendo nombre de quien responde, fecha de respuesta y observaciones opcionales.",client_message:"Hola Juliana,\n\nYa completamos la primera revisión interna de cuentas para el piloto de Amor de Gea. Antes de cerrar la cartera y preparar las recomendaciones, necesitamos confirmar si Amor de Gea ya conoce, ha contactado o mantiene alguna relación con las empresas incluidas.\n\nAdjuntamos una revisión breve. Para cada empresa, solo deben seleccionar el estado que mejor describa la relación actual y agregar una nota cuando sea necesario.\n\nEsta validación no inicia contactos ni compromete ninguna acción comercial. Su función es evitar duplicaciones, conflictos y recomendaciones sobre cuentas que ya estén siendo trabajadas.\n\nMuchas gracias.",sent:false} as const;
const allowed=new Set(AMOR_PHASE5A_CONFLICT_REQUEST.allowed_client_answers);const expected=AMOR_PHASE5A_CONFLICT_REQUEST.answers.map(x=>x.account);
const parse=(line:string)=>line.match(/("(?:[^"]|"")*"|[^,]*)(?:,|$)/g)?.map(v=>v.replace(/,$/,"").replace(/^"|"$/g,"").replaceAll('""','"'))??[];
export function previewAmorConflictCheckImport(csv:string){const lines=csv.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean);const rows=lines.slice(1).map(parse);const seen=new Set<string>(),errors:string[]=[];const preview=rows.map((row,index)=>{const [name,response,note,respondent,date,version]=row;if(!expected.includes(name)){errors.push(`row_${index+2}:unknown_account`)}if(seen.has(name))errors.push(`row_${index+2}:duplicate_account`);seen.add(name);if(response&&!allowed.has(response as never))errors.push(`row_${index+2}:invalid_response`);return{account:name,response:response||null,note:note||"",respondent:respondent||null,response_date:date||null,pilot_version:version||null,state:response?"response_pending_review":"pending_client_check"}});for(const name of expected)if(!seen.has(name))errors.push(`missing:${name}`);return{mode:"preview",valid:errors.length===0,errors,rows:preview,persistence_writes:0,portfolio_mutations:0}}
export const AMOR_PHASE5A1_PROVIDER_ACCOUNTING={phase4:30,phase4_5:0,phase4_6:3,phase5a:0,phase5a_1:bioplaza.provider_calls,total:33+bioplaza.provider_calls,exact_cost:"Exact cost unavailable."} as const;
export const AMOR_PHASE5A1_REPORT_BLUEPRINT=AMOR_PHASE5A_REPORT_BLUEPRINT;
export const AMOR_PHASE5A1_BLOCKERS=["13 real client conflict responses","BioPlaza current official-source confirmation","Final founder review of incorporated responses","Final customer-safe approval","No Phase 5B activation event"] as const;
