import { AMOR_PHASE45_ACCOUNT_REVIEWS } from "./amor-de-gea-phase4-5-review";
import { AMOR_PHASE46_ACTION_BRIEFS, AMOR_PHASE46_CONFLICT_PACKAGE, AMOR_PHASE46_PORTFOLIO, AMOR_PHASE46_VERSION } from "./amor-de-gea-phase4-6-portfolio";
const account=(name:string)=>AMOR_PHASE45_ACCOUNT_REVIEWS.find(x=>x.account===name)!;
export const AMOR_PHASE5A_FOUNDER_APPROVAL={approval_id:"amor-de-gea-v3r2-founder-approval",actor:"founder",approved_at:"2026-08-03T20:25:00.000Z",state:"FOUNDER APPROVED — PENDING CLIENT CONFLICT CHECK AND CUSTOMER-SAFE GATE",portfolio_version:AMOR_PHASE46_VERSION.id,rationale:"Founder approved the 12-account V3R2 portfolio, repair decisions and four internal Action Brief foundations.",dependencies:{client_conflict_check:"pending",customer_safe_gate:"founder_review"},commercial_activation:false,customer_safe_approval:false,client_approval:false,timing_state:"no timing evidence"} as const;
export const AMOR_PHASE5A_VERSION={id:"amor-de-gea-v4d-customer-safe-draft",version:"V4D",created_at:"2026-08-03T20:25:00.000Z",preserves:["V1","V2","V3","V3R",AMOR_PHASE46_VERSION.id],state:"FOUNDER REVIEW — BLOCKED BY CLIENT CONFLICT CHECK",delivered:false,final_report_generated:false,provider_calls:0} as const;
const safeStates:Record<string,{gate:string;reason:string;blocking_claim:string;correction:string;can_remain:boolean}>={
 "Éteka":{gate:"safe after conflict check",reason:"Official spa evidence supports structural relevance.",blocking_claim:"Third-party retail and demand are unverified.",correction:"Present retail/gifting only as a validation hypothesis.",can_remain:true},
 "Celestino Hotel Boutique & Spa":{gate:"safe after conflict check",reason:"Official boutique-hotel and spa identity supports the route.",blocking_claim:"Product retail and repeat consumption are unverified.",correction:"Describe the use case as proposed, not observed.",can_remain:true},
 "Sinergy On":{gate:"safe after conflict check",reason:"Official customized-kit offering supports a possible component-supply use case.",blocking_claim:"No live brief, volume or co-branding acceptance is confirmed.",correction:"Label every project and repeat mechanism as a hypothesis.",can_remain:true},
 "Vitálica":{gate:"safe after conflict check",reason:"Official active natural-products ecommerce supports retail adjacency.",blocking_claim:"Category openness, margin and onboarding are unknown.",correction:"Recommend validation without implying willingness to list.",can_remain:true},
 "Ser Saludable":{gate:"safe after wording revision",reason:"Official wellness assortment supports adjacency.",blocking_claim:"Health-oriented language could imply verified effects or regulatory suitability.",correction:"Remove effect claims and attribute only visible public assortment.",can_remain:true},
 "BioPlaza":{gate:"safe after source confirmation",reason:"Established natural retail remains structurally relevant.",blocking_claim:"Current V3 fact relies on prior verification without fresh source date.",correction:"Use qualified wording and confirm the official assortment before delivery.",can_remain:true},
 "Masaya Collection":{gate:"safe after conflict check",reason:"Fresh official hospitality collection evidence supports structural fit.",blocking_claim:"Property authority and recurring guest use are unverified.",correction:"Present the property test and replenishment as hypotheses.",can_remain:true},
 "Natural + Mente":{gate:"safe after wording revision",reason:"Repair confirmed active multi-brand ecommerce and fitoterapia categories.",blocking_claim:"Premium fit, buyer access and margin are unknown.",correction:"State only catalog facts; frame product fit as LeadLens inference.",can_remain:true},
 "Hotel Charleston Santa Teresa Spa":{gate:"safe after conflict check",reason:"Official spa rituals support route relevance.",blocking_claim:"Third-party retail and procurement accessibility are unverified.",correction:"Classify as selective investigation, not immediate target.",can_remain:true},
 "Habibi Plantitas":{gate:"safe after wording revision",reason:"Official corporate gifting activity supports project adjacency.",blocking_claim:"Acceptance of ingestible wellness products is unknown.",correction:"Describe category expansion as a question to validate.",can_remain:true},
 "Funat":{gate:"safe after wording revision",reason:"Official botanical catalog provides market-comparison value.",blocking_claim:"Third-party brand acceptance and competitive conflict are unknown.",correction:"Keep as selective investigation and remove supplier-readiness implications.",can_remain:true},
 "Distribuidora DAM":{gate:"safe after source confirmation",reason:"Distribution offers route-learning value.",blocking_claim:"Current identity depth, margin, volume and capacity compatibility are unresolved.",correction:"Keep as monitor only and confirm official operating model before delivery.",can_remain:true},
};
export const AMOR_PHASE5A_EVIDENCE_GATES=AMOR_PHASE46_PORTFOLIO.approved_internal_accounts.map(name=>({account:name,...safeStates[name],timing:"no timing evidence",conflict_check:"pending_client_check",unsafe_removed:["purchase intent","confirmed need","known procurement terms","named decision-maker","verified health effect"]}));
const customerGroup=(name:string)=>AMOR_PHASE46_PORTFOLIO.work_first.includes(name)?"FIRST VALIDATION SEQUENCE":AMOR_PHASE46_PORTFOLIO.priority.includes(name)?"STRATEGIC PRIORITY":"INVESTIGATE SELECTIVELY";
export const AMOR_PHASE5A_PORTFOLIO=AMOR_PHASE46_PORTFOLIO.approved_internal_accounts.map(name=>{const a=account(name);const gate=safeStates[name];return{account:name,group:customerGroup(name),account_type:a.route.replaceAll("_"," "),geography:a.geography,reason_it_may_fit:`La evidencia pública sugiere encaje estructural con ${a.opportunity_mechanism.use.toLowerCase()}.`,proposed_use_case:`Hipótesis: ${a.opportunity_mechanism.offer}.`,recommended_validation:a.next_validation,main_limitation:gate.blocking_claim,current_recommendation:gate.gate,relationship_check_status:"pending_client_check",timing:"No encontramos evidencia pública de timing activo."}});
export const AMOR_PHASE5A_ACTION_BRIEFS=AMOR_PHASE46_ACTION_BRIEFS.map(b=>({candidate_id:`${b.brief_id}:v4d`,account:b.account,status:safeStates[b.account].gate,next_step:"Pending Amor de Gea relationship and conflict confirmation.",why_this_account:`La cuenta presenta encaje estructural relevante por su modelo público de ${b.executive_opportunity.route.replaceAll("_"," ")}; pertenece a la primera secuencia para validar el mecanismo, no por intención de compra observada.`,opportunity_hypothesis:{label:"LeadLens hypothesis — not a confirmed account need",mechanism:b.executive_opportunity.primary_use_case,use_case:b.mechanism.use,initial_test:b.executive_opportunity.initial_test,repeat:b.executive_opportunity.repeat},account_context:{identity:b.account,geography:b.identity.geography,business_model:b.executive_opportunity.route.replaceAll("_"," "),visible_offering:b.account_context.visible_offering,evidence:b.integrity.facts},buyer_path_hypothesis:{probable_function:b.entry.probable_function,entry_route:"Canal oficial de la empresa, sujeto a conflict check.",centralization:"Unknown",procurement_complexity:"Requires validation",unknowns:b.entry.validate_before_contact,named_person:null},pre_meeting:{angle:b.pre_meeting.angle,offer:b.pre_meeting.offer,questions:b.pre_meeting.questions,objections:b.pre_meeting.objections.map(x=>`Hipótesis de objeción: ${x}`),materials:b.pre_meeting.materials,validation_priorities:[b.entry.validate_before_contact]},evidence_limitations:{facts:b.integrity.facts,internal_inference:b.integrity.inferences,main_uncertainty:b.integrity.uncertainty,freshness:b.integrity.facts[0]?.freshness??"unknown",timing:"NO TIMING EVIDENCE",conflict_check:"pending_client_check"},customer_safe_ready:false,published:false}));
export const AMOR_PHASE5A_CONFLICT_REQUEST={package_id:"amor-de-gea-v4d-conflict-check-request",version:"V4D",state:"ready_not_sent",explanation:"Esta revisión evita recomendar cuentas ya trabajadas, relaciones activas o empresas que Amor de Gea prefiera excluir. No inicia contacto ni compromete ninguna acción comercial.",allowed_client_answers:["no la conocemos","la conocemos, pero nunca la hemos contactado","fue contactada anteriormente","existe una conversación activa","es cliente actual","fue cliente","es aliado actual","existe conflicto o debe excluirse","nos interesa explorarla","no nos interesa trabajarla"],supported_internal_states:["pending_client_check","clear_to_consider","known_not_contacted","prior_contact","active_conversation","current_client","former_client","current_partner","conflict_exclude","client_not_interested","needs_clarification"],respondent:null,response_date:null,answers:AMOR_PHASE46_CONFLICT_PACKAGE.accounts.map(x=>({account:x.account,answer:null,note:"",state:"pending_client_check"})),pilot_version:"V4D",sent:false};
export function buildAmorConflictCheckCsv(){const q=(v:string)=>`"${v.replaceAll('"','""')}"`;const header=["Cuenta","Estado de relación","Nota opcional","Respondente","Fecha de respuesta","Versión piloto"];return "\uFEFF"+[header,...AMOR_PHASE5A_CONFLICT_REQUEST.answers.map(x=>[x.account,"","","","",AMOR_PHASE5A_CONFLICT_REQUEST.pilot_version])].map(row=>row.map(q).join(",")).join("\r\n")+"\r\n"}
export const AMOR_PHASE5A_WHAT_CHANGED={title:"Cómo cambió la recomendación",items:["Las respuestas de Amor de Gea orientaron la búsqueda hacia pilotos manejables y mecanismos de recompra que todavía deben validarse.","Retail, hotelería, gifting y distribución se evaluaron con mecanismos y exigencias operativas diferentes.","Se priorizaron productos terminados y pruebas acotadas; gran volumen y private label quedaron condicionados por capacidad y economía.","Hotel Spa La Colina salió de la primera secuencia porque la evidencia pública no confirmó retail de terceros ni reposición.","Natural + Mente regresó tras confirmar ecommerce activo, múltiples laboratorios y categorías adyacentes.","Tu Tienda Saludable y Somos Consiente se excluyeron porque la evidencia disponible no mostró un mecanismo suficientemente diferenciado o recurrente.","Vitálica entró en la primera secuencia por su ecommerce activo y un mecanismo de sell-through verificable mediante prueba.","Se conservaron 12 cuentas de calidad en lugar de maximizar volumen."],provenance:["Contexto declarado por Amor de Gea","Evidencia pública atribuida","Inferencia LeadLens","Decisión interna del piloto","Confirmación del cliente pendiente"]};
export const AMOR_PHASE5A_MARKET_MAP=[{route:"Retail especializado",summary:"Prueba inicial más sencilla, mecanismo de reventa claro y reposición por validar.",hypothesis_strength:"strong test hypothesis — not validated"},{route:"Hotelería / spa",summary:"Encaje diferenciado y múltiples usos posibles; retail de terceros y recurrencia siguen sin confirmar.",hypothesis_strength:"differentiated hypothesis — partially supported"},{route:"Gifting / co-branding",summary:"Presentación y personalización atractivas; demanda por proyecto o temporada y recurrencia por probar.",hypothesis_strength:"promising conditioned hypothesis"},{route:"Distribución regional",summary:"Mayor alcance potencial y mayor dependencia de capacidad, economía y requisitos de canal.",hypothesis_strength:"most conditioned hypothesis"}] as const;
export const AMOR_PHASE5A_SUCCESS_CONTRACT={objective:"Mejorar qué cuentas validar primero y cómo preparar cada conversación.",value_dimensions:["Inteligencia comercial","Priorización","Preparación antes de reuniones","Aprendizaje de mercado","Revisión estratégica"],indicators:{quality:["Relevancia de cuentas","Utilidad de recomendaciones","Razones de aceptación o rechazo"],action:["Cuentas seleccionadas","Validación comercial iniciada","Buyer paths confirmados","Conversaciones obtenidas"],learning:["Objeciones","Encaje de ruta","Formato","Precio","Canal","Reposición"],outcomes:["Oportunidades","Pruebas","Órdenes","Ventas cuando existan"]},no_sales_guarantee:"LeadLens mejora la calidad de decisión comercial y la preparación. Las ventas dependen también de la ejecución del cliente, respuesta de las cuentas, negociación, precio, timing y otros factores de mercado."} as const;
export const AMOR_PHASE5A_REPORT_BLUEPRINT=["Conclusión ejecutiva","Qué aprendió LeadLens de Amor de Gea","Commercial Readiness","Market Opportunity Map","Portfolio overview","First Validation Sequence","Strategic Priority","Investigate Selectively","Cuatro Account Action Briefs","What Changed","Pilot Learning Agenda","Próximos 30–60 días","Medición de éxito","Evidencia y limitaciones"] as const;
export const AMOR_PHASE5A_NEXT_60_DAYS=["Completar conflict checks","Aprobar la lista definitiva","Preparar materiales comerciales","Validar buyer paths","Seleccionar 2–4 cuentas para primera acción","Registrar respuestas y objeciones","Revisar las primeras señales comerciales","Recalibrar la siguiente secuencia"] as const;
export const AMOR_PHASE5A_BLOCKERS=["13 conflict-check responses from Amor de Gea","Founder approval of V4D wording and evidence gates","Customer-safe approval remains separate","Final report generation remains disabled","No Phase 5B activation event"] as const;
