import {createHash} from "crypto";
import {AMOR_ACCEPTED_CONTEXT,AMOR_COMMERCIAL_READINESS} from "./amor-de-gea-commercial-readiness";

const id=(prefix:string,value:unknown)=>`${prefix}_${createHash("sha256").update(JSON.stringify(value)).digest("hex").slice(0,24)}`;
const createdAt="2026-08-03T18:00:00.000Z";
const objective="Which B2B accounts should Amor de Gea work first during the next 90–180 days, given its current offer, operating capacity, brand positioning and pilot objectives?";

const archetypes=[
 ["Independent natural-product retailers","Direct premium-wellness adjacency","Retail resale","Tier 1–2","low–moderate","Assortment may be incompatible","Official current assortment"],
 ["Premium wellness stores","Premium positioning and repeat retail","Curated wellness assortment","Tier 1–2","low–moderate","Price architecture unknown","Official catalog and positioning"],
 ["Boutique hotels","Guest experience, gifting and boutique retail","Boutique hotel retail","Tier 1–2","moderate","Consumption model and frequency unknown","Official amenities, shop or wellness offer"],
 ["Hotel spas","Strong wellness context and accessible pilot","Spa retail / guest experience","Tier 1–2","moderate","Health-claim and bottle-use constraints","Official spa menu and retail evidence"],
 ["Independent spas and wellness centers","Aligned ritual and experience use","Spa retail","Tier 1","low–moderate","Repeat demand unproven","Official services and product assortment"],
 ["Compatible integrative wellness clinics","Category adjacency where compliance permits","Curated wellness assortment","Tier 1","moderate–high","Regulated proposition may be required","Official non-clinical retail offer and compliance needs"],
 ["Corporate gifting providers","Customization, kits and co-branding fit","Corporate gifting","Tier 1–2","moderate","Seasonality and unit economics","Official corporate catalog and current programs"],
 ["Employee-wellness program providers","Potential recurring curated kits","Employee wellness kits","Tier 1–2","moderate","Procurement and claims requirements","Official programs and buyer model"],
 ["Curated gift-box and premium experience brands","Finished packaging and special assortments","Co-branded gifting","Tier 1–2","low–moderate","Repeatability may be seasonal","Official catalog and partnership evidence"],
 ["Selective regional distributors","Geographic reach with bounded scale","Selective distribution","Tier 2–3","high","Economics and capacity unresolved","Official portfolio, territory and onboarding"],
].map(([account_type,why_fit,use_case,initial_order,procurement,primary_risk,evidence_required])=>({account_type,why_fit,use_case,initial_order,procurement,primary_risk,evidence_required}));

const useCases=[
 ["Retail resale","Finished 50 ml Agua, Tierra and Éter","50-unit pilot then replenishment","strong","assortment, margin and replenishment","No unsupported benefit claims","Current assortment and buyer route"],
 ["Curated wellness assortment","Three-product premium collection","mixed-SKU pilot","strong","SKU mix and economics","Marketing is not independent evidence","Category adjacency"],
 ["Boutique hotel retail","Premium packaged bottles or collection","small pilot / periodic restock","moderate","guest-shop model and freight","No unverified regulatory claims","Retail or amenity precedent"],
 ["Spa retail","Post-service retail ritual","50-unit pilot","moderate–strong","service integration and staff explanation","No health claims","Spa menu, retail area and buyer path"],
 ["Guest wellness experience","Curated in-room or experience add-on","bounded event/pilot","moderate","glass handling and usage model","Dosage statements unresolved","Operational fit and safe copy"],
 ["Corporate gifting","Finished product or three-item bundle","project order","moderate","seasonality, customization and delivery","No unsupported claims","Active gifting program"],
 ["Employee wellness kits","Coordinated kit component","campaign / pilot","moderate","HR procurement and fulfillment","Claims must remain non-medical","Program structure and audience"],
 ["Co-branded gifting","Adapted label/packaging","project order","moderate","approval lead time and exact scope","Private label not implied","Co-branding feasibility"],
 ["Selective distribution","Existing finished product portfolio","100–300 recurring; >300 conditioned","potentially strong","distributor economics and capacity","Documents client-stated","Territory, portfolio and terms"],
 ["Experiential alliance","Wellness event or curated collaboration","small batch / event","uncertain–moderate","repeatability and owner","No benefit overstatement","Current event or partnership model"],
].map(([name,plausible_offer,order_type,repeat_purchase,operational_dependency,customer_safe_limitation,validation_required])=>({name,plausible_offer,order_type,repeat_purchase,operational_dependency,customer_safe_limitation,validation_required}));

const rule=(rule:string,source:"client_context"|"founder_decision"|"system_interpretation",confidence:"strong"|"moderate"|"weak",affected_route:string)=>({rule,source,confidence,affected_route});
export const AMOR_SEARCH_BLUEPRINT={
 blueprint_id:id("blueprint",{context:AMOR_ACCEPTED_CONTEXT.id,version:1}),version:1,pilot_id:"amor-de-gea",context_id:AMOR_ACCEPTED_CONTEXT.id,context_version:1,readiness_context_id:AMOR_COMMERCIAL_READINESS.context_version_id,created_at:createdAt,review_state:"internal_review",approval_state:"founder_review",commercial_objective:objective,objective_boundary:"Highest relative commercial potential; no purchase probability or sales promise.",
 geography:{primary:"Colombia",national_discovery:true,conditions:["Prioritize commercially meaningful orders","Condition distant small orders on freight economics","Validate logistics before formal proposal","National coverage is client-stated, not independently verified"]},
 routes:{priority_1:"Independent specialty retail and premium wellness retail",priority_2:"Boutique hospitality, spas and wellness experiences",priority_3:"Corporate gifting, curated kits and co-branding",exploratory:"Regional distributors",deferred:["Large national distribution","Complex national chains","Private label","Immediate high-volume accounts","Procurement-heavy opportunities requiring verified claims"],source:"founder_decision"},
 account_archetypes:archetypes,
 account_size_ladder:[{tier:1,label:"Pilot",range:"approximately 50 units",state:"strongest initial fit"},{tier:2,label:"Early recurring",range:"approximately 100–300 units monthly",state:"attractive near-term target"},{tier:3,label:"Strategic scale",range:"above approximately 300 units",state:"conditioned by capacity validation"},{tier:4,label:"High volume",range:"approximately 1,000 units or more",state:"deferred or route-blocked until validated"}],
 use_cases:useCases,
 inclusion_rules:[rule("Visible wellness, natural-product or premium-gifting alignment","founder_decision","strong","all priority routes"),rule("Manageable initial order around Tier 1 or Tier 2","founder_decision","strong","all"),rule("Accessible or identifiable buying path","system_interpretation","moderate","all"),rule("Credible use for a premium 50 ml botanical product","client_context","strong","retail/hospitality/gifting"),rule("Plausible repeat purchase","founder_decision","moderate","retail/hospitality"),rule("Colombian geography with workable freight","client_context","strong","all"),rule("Reasonable procurement complexity","founder_decision","moderate","all"),rule("Current activity evidenced","system_interpretation","strong","all"),rule("Adjacent products or services are evidenced","system_interpretation","moderate","all"),rule("Scale does not immediately exceed readiness","founder_decision","strong","distribution"),rule("Retail, gifting, hospitality or experience integration is explicit","founder_decision","strong","priority routes")],
 exclusion_rules:["Private-label dependency","Immediate demand near or above 1,000 units","Unsupported regulated-health proposition required for entry","Economics dependent on low-value distant orders","Inactive or unverifiable business","No plausible use case","Procurement burden disproportionate to opportunity","Known relationship conflict","Entry requires unverified compliance claims","Identity cannot be resolved"],
 exclusion_boundary:"Unknown final margin alone never excludes an account.",
 conditioning_rules:["Ordinary capacity uncertain","Freight may be material","Distributor economics pending","Procurement complex","Buyer path unclear","Documentation not independently reviewed","Customer-safe claims require validation","Relationship status unknown"],
 procurement_tolerance:{favor:["Founder-led","Owner-led","Category-manager-accessible","Partnership-led","Boutique procurement","Pilot-friendly"],deprioritize:["Long supplier onboarding","National-chain procurement","Formal tenders","Complex compliance","Mandatory private label","Likely more than six months before first test"],exception:"Longer-cycle accounts may remain when strategic learning value is high."},
 buyer_path_hypotheses:{retail:["founder","owner","category buyer","purchasing","commercial manager"],hospitality_spa:["general manager","spa manager","guest-experience manager","purchasing","wellness director"],corporate_gifting:["commercial director","gifting buyer","HR/wellness","marketing","partnerships"],distributor:["category manager","portfolio manager","commercial director","purchasing"],boundary:"Role hypotheses only; no exact person is asserted."},
 research_depth:[{level:1,name:"Qualification",fields:["identity","activity","geography","account type","plausible use case","route compatibility"]},{level:2,name:"Prioritization",fields:["assortment","positioning","procurement complexity","buyer area","repeat potential","scale","evidence quality"]},{level:3,name:"Account Action Brief",limit:"3–5 priority accounts",fields:["decision area","comparable offer","priorities","entry hypothesis","tailored pitch","meeting questions","objections","evidence","unknowns","next action"],implemented:false}],
 source_strategy:{hierarchy:["Official company website","Official store/catalog/menu/services","Current official business-relevant social profile","Official hospitality or spa materials","Authoritative business directories","Credible trade/local business coverage","Search snippets for discovery only"],by_route:{retail:["official catalog","store locator","supplier/onboarding pages"],hospitality_spa:["official hotel/spa site","spa menu","guest experience materials"],gifting:["official corporate catalog","partnership pages","campaign materials"],distribution:["official portfolio","territory pages","supplier requirements"]},calls_made:0},
 query_hypotheses:[
  ["retail","Colombia","premium natural-product retailer","Retailers with current botanical/wellness assortments may support a 50-unit pilot","official catalog and active stores","mass chain, inactive catalog","8–12 identity-verified candidates or saturation"],
  ["retail","Bogotá Medellín Cali","independent premium wellness store","Owner/category-accessible stores may reduce entry friction","assortment, positioning, buyer route","generic supplement-only store","quality no longer improves"],
  ["retail","Colombia","premium healthy lifestyle concept store","Adjacent premium products may support curated assortment","official brands and price architecture","no product resale","6 qualified accounts"],
  ["retail","Colombia","natural-product retailer botanical extracts","Direct category adjacency may improve use-case clarity","current comparable products","regulated-only proposition","duplicates dominate"],
  ["hospitality_spa","Colombia","boutique hotel spa wellness retail","Spa retail may fit premium 50 ml products","spa menu, shop, guest wellness","large chain procurement","6 qualified accounts"],
  ["hospitality_spa","Cartagena Eje Cafetero Antioquia","boutique wellness hotel","Guest experience and gifting may support bounded pilots","official wellness experience","no wellness offer","evidence saturation"],
  ["hospitality_spa","Colombia","independent premium spa retail products","Accessible spa operators may test retail integration","services and product retail","medical claims required","6 identity-verified accounts"],
  ["hospitality_spa","Colombia","wellness retreat curated products","Experiential alliances may create differentiated use","current retreats and partnerships","event inactive","quality no longer improves"],
  ["gifting","Colombia","premium corporate gifting wellness kits","Finished packaging and customization may fit kits","corporate catalog and clients","private-label mandatory","6 qualified accounts"],
  ["gifting","Bogotá Medellín Cali","curated gift box natural wellness","Curators may accept small project orders","current boxes and order model","low-value nationwide shipping","evidence saturation"],
  ["gifting","Colombia","employee wellness kit provider","HR programs may support repeat campaigns","official programs and procurement","health claims required","4 qualified accounts"],
  ["gifting","Colombia","premium experience brand co-branding","Experience brands may value co-branded botanical gifts","active partnerships","unclear repeat buyer model","quality no longer improves"],
  ["distribution","Colombia region","regional natural-products distributor premium","Selective regional distribution may fit Tier 2","portfolio, territory, terms","immediate 1,000+ units","4 qualified accounts"],
  ["distribution","Colombia","wellness distributor independent brands","Portfolio adjacency may justify economics validation","official brands and onboarding","private label dependency","route incompatibility dominates"],
  ["distribution","Andean Colombia","regional specialty retail distributor","Bounded territories may avoid national-chain complexity","territory and customer model","complex tender","4 identity-verified accounts"],
 ].map(([route,geography,account_archetype,hypothesis,expected_evidence,exclusion_signals,stop_condition],index)=>({id:`qh_${index+1}`,route,geography,account_archetype,hypothesis,expected_evidence,exclusion_signals,stop_condition,executed:false})),
 stop_rules:["Evidence saturation","Insufficient identity","Repeated duplicates","Route produces mostly incompatible accounts","Required procurement exceeds current readiness","Enough qualified accounts exist to compare","Further search increases volume but not quality"],
 phase4_ceiling:{routes:"3–4",queries:16,raw_candidates:"60–100 maximum",identity_verified:"20–30",qualified:"12–18",deep_research:"8–12",portfolio:"approximately 10–15",action_briefs:"3–5",quota_policy:"Ceilings, never mandatory quotas; quality overrides volume."},
 prioritization:{dimensions:["brand_product_alignment","commercial_use_case_strength","operational_compatibility","ease_of_entry","procurement_complexity","order_size_compatibility","repeat_purchase_potential","buyer_path_clarity","evidence_strength","strategic_learning_value"],states:["strong","moderate","weak","unknown","not_applicable"],reason_required:true,timing_separate:true,opaque_score:false,purchase_probability:false},
 actionability_states:{ACT_NOW:"Strong compatibility, sufficient evidence, manageable entry and current reason to act",INVESTIGATE_NOW:"Promising with one or two material unknowns worth immediate validation",PRIORITIZE:"Strong structural opportunity without verified active timing",MONITOR:"Good potential constrained by current conditions or timing",LOW_PRIORITY:"Plausible but inferior to alternatives",EXCLUDE:"Hard constraint, no viable use case, identity/evidence failure or blocked route"},
 execution:{queries_executed:0,provider_calls:0,new_accounts:0,broad_discovery:false,ranking_mutation:false,customer_safe_promotion:false,final_report_updated:false,opportunity_facilitation:false},
} as const;

type State="strong"|"moderate"|"weak"|"unknown"|"not_applicable";
const specifications:Record<string,any>={
 "Natural + Mente":{change:"maintain",actionability:"PRIORITIZE",use:"Retail resale and curated wellness assortment",risk:"Current assortment, scale and buyer path remain unverified",buyer:"owner or category buyer",validation:"Verify current botanical assortment, procurement model and a Tier 1 pilot path",confidence:"moderate",states:["strong","strong","moderate","moderate","moderate","strong","strong","moderate","moderate","strong"]},
 "Tu Tienda Saludable":{change:"maintain",actionability:"PRIORITIZE",use:"Direct premium wellness retail resale",risk:"Commercial differentiation and evidence depth remain limited",buyer:"owner, founder or purchasing lead",validation:"Verify assortment adjacency, decision ownership and repeat-order economics",confidence:"moderate",states:["strong","strong","moderate","strong","moderate","strong","strong","moderate","moderate","strong"]},
 "Hotel Spa La Colina":{change:"raise",actionability:"PRIORITIZE",use:"Spa retail, guest wellness experience and gifting",risk:"Exact service integration, purchasing frequency and safe usage copy remain unknown",buyer:"general manager, spa manager or guest-experience lead",validation:"Verify spa retail model, 50-unit pilot use, glass handling and decision area",confidence:"moderate",states:["strong","strong","moderate","moderate","moderate","strong","moderate","moderate","moderate","strong"]},
 "BioPlaza":{change:"maintain",actionability:"PRIORITIZE",use:"Natural/wellness retail assortment",risk:"Supplier onboarding, competition and account scale may exceed ideal first-test complexity",buyer:"category buyer, purchasing or commercial manager",validation:"Verify onboarding, assortment gap, Tier 1–2 replenishment and account economics",confidence:"moderate",states:["strong","strong","moderate","weak","weak","moderate","strong","moderate","strong","moderate"]},
 "Distribuidora DAM":{change:"lower",actionability:"MONITOR",use:"Selective regional distribution",risk:"Distributor economics, ordinary capacity and channel requirements are unresolved",buyer:"portfolio/category manager or commercial director",validation:"Validate territory, expected opening volume, distributor margin and replenishment before prioritizing",confidence:"moderate",states:["moderate","moderate","weak","weak","weak","weak","moderate","moderate","moderate","strong"]},
 "Somos Consiente":{change:"monitor",actionability:"MONITOR",use:"Experiential alliance, gifting or co-branding",risk:"Repeatable purchasing model and order size are unclear",buyer:"founder, partnerships or commercial lead",validation:"Verify active commercial model, repeatable buyer use case and bounded order logic",confidence:"weak–moderate",states:["strong","moderate","moderate","moderate","moderate","moderate","weak","moderate","moderate","strong"]},
};
const dimensions=AMOR_SEARCH_BLUEPRINT.prioritization.dimensions;
export function buildAmorAccountRecalibration(baselines:any[]){return baselines.map((baseline:any)=>{const s=specifications[baseline.account_name];const structural_evaluation=dimensions.map((dimension,index)=>({dimension,state:s.states[index] as State,reason:`${s.use}; ${index===8?"only existing identity/account evidence is available":"evaluated against accepted context and route readiness"}.`}));const thesis_id=id("thesis_v2",{baseline:baseline.thesis_id,context:AMOR_ACCEPTED_CONTEXT.id});return {thesis_id,version:2,supersedes_id:baseline.thesis_id,baseline_preserved:true,account_id:baseline.account_id,account_name:baseline.account_name,baseline:{thesis_id:baseline.thesis_id,recommendation:baseline.decision,thesis:baseline.opportunity_statement,limitations:baseline.limitations},accepted_context_impact:{client_context:["Finished 50 ml offer","MOQ around 50","100–300 early recurrence","National Colombia coverage client-stated"],founder_search_hypotheses:[AMOR_SEARCH_BLUEPRINT.routes.priority_1,AMOR_SEARCH_BLUEPRINT.routes.priority_2,AMOR_SEARCH_BLUEPRINT.routes.priority_3],system_interpretations:["Favor manageable pilots","Condition freight, capacity and procurement"],open_validations:["Exact economics","ordinary/per-SKU capacity","relationship conflict","customer-safe claims"]},structural_evaluation,timing:{state:"no timing evidence",reason:"No fresh dated buying or sourcing signal exists; channel access is not intent."},decision:s.change,actionability:s.actionability,previous_thesis:baseline.opportunity_statement,recalibrated_thesis:`${baseline.account_name} has ${s.confidence} relative structural potential for ${s.use}. It should be handled as ${s.actionability}, without inferring demand or timing.`,what_changed:`Accepted context makes pilot size, route suitability and operational constraints explicit; decision is ${s.change}.`,responsible_input:"Accepted context plus founder-approved route priorities",strongest_use_case:s.use,main_risk:s.risk,buyer_path_hypothesis:{roles:s.buyer,state:"role_hypothesis"},validation_required:s.validation,recommended_next_move:s.actionability==="MONITOR"?"Resolve the named route constraint before outreach prioritization.":"Complete Level 2 research before any outreach decision.",confidence:s.confidence,limitation:"Internal-only; no buying intent, active timing or customer-safe promotion.",review_state:"internal_review",ranking_impact:"internal_comparison_only",customer_safe:false};});}

export function buildWhatChanged(recalibrated:ReturnType<typeof buildAmorAccountRecalibration>){return {baseline:"Baseline V1 — before client context",recalibration:"Context-driven recalibration V2",accounts:recalibrated.map(x=>({account:x.account_name,old_recommendation:x.baseline.recommendation,new_recommendation:x.actionability,old_thesis:x.previous_thesis,new_thesis:x.recalibrated_thesis,changed_constraint:"Explicit pilot/capacity/procurement readiness",changed_route:x.strongest_use_case,changed_use_case:x.strongest_use_case,changed_priority:x.decision,unchanged_limitation:"No verified buying intent or timing",new_validation_need:x.validation_required})),portfolio:{retail:"Remains core, now bounded by pilot size and procurement complexity.",hospitality:"Elevated as a differentiated boutique/spa route.",gifting:"Explicit third-priority route with repeatability validation.",distribution:"Reduced from scale bias to exploratory and capacity/economics conditioned.",capacity:"Tier 1–2 favored; Tier 3 conditioned; Tier 4 deferred.",geography:"National Colombia allowed; distant small orders freight-conditioned.",evidence:"Baseline evidence remains unchanged; no new research was run."}};}
