import checkpoint from "../../ml/data/opportunity-intelligence/amor_blueprint_v2_bounded_search_20260803_v1.checkpoint.json";
import { AMOR_V3R3 } from "./amor-de-gea-blueprint-v2-replay";
export const AMOR_V2_BOUNDED_RUN={run_id:checkpoint.run_id,state:checkpoint.state,blueprint_id:checkpoint.blueprint_id,compiler_version:checkpoint.compiler_version,provider:"tavily",provider_calls:checkpoint.provider_calls,provider_errors:checkpoint.provider_errors,raw_results:checkpoint.queries.reduce((n,q)=>n+q.raw_results,0),unique_domains:new Set(checkpoint.queries.flatMap(q=>q.candidates.map(c=>c.domain))).size,exact_cost_usd:checkpoint.exact_cost_usd,historical_calls_before:34,historical_calls_after:34+checkpoint.provider_calls,raw_payloads_persisted:checkpoint.raw_payloads_persisted} as const;
export const AMOR_V2_REPLACEMENT_QUERIES=checkpoint.queries.map(q=>({query_id:q.query_id,family:q.family,route:q.route,query:q.query,context_fields:q.context_fields,rule_ids:q.rule_ids,mechanism:q.mechanism,status:q.status,raw_results:q.raw_results,latency_ms:q.latency_ms,error:q.error}));
export const AMOR_V2_SEARCH_FUNNEL={raw:39,unique_domains:28,prior_domain_overlap:10,new_domains:18,identity_verified:6,qualified_challengers:1,deep_researched:6,new_portfolio_accounts:0,limits:checkpoint.limits} as const;
export const AMOR_V2_PRIOR_DOMAIN_REVIEW=[
 {domain:"imanderecuerdos.com",decision:"exclude",reason:"Corporate-gifting article and customization are visible, but third-party wellness curation and repeat program are not evidenced."},
 {domain:"em2c.com.co",decision:"exclude",reason:"Current official article supports corporate-gifting advice, not a verified multi-brand product-curation mechanism."},
 {domain:"markmelo.com",decision:"monitor",reason:"Official current gifting content includes wellness/promotional categories, but finished-product partner curation and moderate-order compatibility remain unverified."},
 {domain:"colombiamascompetitiva.com",decision:"exclude",reason:"Institutional ingredient portfolio is not a commercial buying account for finished 50 ml products."},
 {domain:"incadistributions.com",decision:"exclude",reason:"USA wholesale orientation and scale are incompatible with the approved Colombia selective-distribution gap."},
] as const;
export const AMOR_V2_DEEP_RESEARCH=[
 {account:"Zonazul Mercado Saludable",domain:"zonazul.co",route:"specialty_retail",official_url:"https://zonazul.co/",facts:["Active WooCommerce market","Local and national shipping stated","Healthy-product categories visible"],counterevidence:["No verified botanical-extract assortment","No buyer or pilot-size evidence"],procurement:"unknown, potentially owner/local",cycle:"unknown",recurrence:"moderate shelf/ecommerce hypothesis",logistics:"national freight requires validation",buyer_path:"Validate owner/category buying and third-party assortment before proposing a 50-unit mixed shelf test.",decision:"INVESTIGATE — NOT PORTFOLIO",challenges:"Funat",advantage:"Potentially simpler direct retail mechanism",remaining:"Multibrand botanical relevance and procurement are unverified."},
 {account:"Promohit",domain:"promohit.co",route:"gifting",official_url:"https://www.promohit.co/noticias/regalos-corporativos",facts:[],counterevidence:["Official page timed out with zero bytes"],procurement:"unknown",cycle:"unknown",recurrence:"unknown",logistics:"unknown",buyer_path:"No approach until official operating and curation evidence exists.",decision:"INSUFFICIENT EVIDENCE",challenges:"Sinergy On",advantage:"None demonstrated",remaining:"Identity, curation and recurrence."},
 {account:"Imán de Recuerdos",domain:"imanderecuerdos.com",route:"gifting",official_url:"https://www.imanderecuerdos.com/blogs/regalos/regalos-corporativos",facts:["Active Shopify site","Official article promotes personalized corporate gifts in Colombia"],counterevidence:["No evidence of third-party wellness-product curation","Article content does not prove a repeat corporate program"],procurement:"unknown",cycle:"unknown",recurrence:"weak",logistics:"requires validation",buyer_path:"Validate finished-product partner model before any commercial hypothesis.",decision:"EXCLUDE",challenges:"Habibi",advantage:"None demonstrated",remaining:"Curation and recurrence."},
 {account:"EM2C",domain:"em2c.com.co",route:"gifting",official_url:"https://em2c.com.co/10-ideas-regalos-corporativos-clientes-colaboradores",facts:["Official current article dated 2026-05-29","Corporate gifting positioned for client and employee relationships"],counterevidence:["Editorial evidence does not prove product curation or buyer behavior"],procurement:"unknown",cycle:"unknown",recurrence:"weak",logistics:"unknown",buyer_path:"Validate whether EM2C purchases third-party finished products; do not infer from content.",decision:"EXCLUDE",challenges:"Sinergy On",advantage:"None demonstrated",remaining:"Commercial mechanism."},
 {account:"Markmelo",domain:"markmelo.com",route:"gifting",official_url:"https://markmelo.com/gifting-corporativo-articulos-promocionales-colombia",facts:["Official 2026 gifting guide","Wellness and promotional-product categories are explicitly referenced"],counterevidence:["No verified partner-brand curation","Moderate order sizes and program recurrence are not evidenced"],procurement:"structured validation",cycle:"medium/unknown",recurrence:"moderate hypothesis",logistics:"requires validation",buyer_path:"Validate partnership/category buying, order minimum and finished-product inclusion before comparing with Sinergy On.",decision:"MONITOR",challenges:"Sinergy On",advantage:"Broader corporate gifting surface, but weaker curation evidence",remaining:"Buyer path, MOQ and recurrence."},
 {account:"Vitaliah",domain:"stevia.com.co",route:"regional_distribution",official_url:"https://stevia.com.co/pages/distribuidor-mayorista-o-tienda",facts:["Active Shopify business in Colombia","Official page recruits distributors/wholesale stores for its own products"],counterevidence:["Appears supplier/brand-led rather than buyer of third-party finished products","Scale and onboarding compatibility unknown"],procurement:"likely structurally incompatible",cycle:"long/unknown",recurrence:"not applicable as buyer",logistics:"national wholesale",buyer_path:"No approach; first establish whether it buys external brands rather than recruiting resellers.",decision:"EXCLUDE",challenges:"Distribuidora DAM gap",advantage:"None as buyer",remaining:"Buyer identity fails."},
] as const;
export const AMOR_V2_GAP_RESULTS={retail:{verdict:"one challenger to investigate, no portfolio addition",accounts:["Zonazul Mercado Saludable"]},hospitality:{verdict:"no new identity-qualified challenger",accounts:[]},gifting:{verdict:"no challenger clears third-party curation and recurrence evidence",accounts:["Markmelo — monitor"]},distribution:{verdict:"gap remains; no compatible selective distributor",accounts:[]}} as const;
export const AMOR_V2_CHALLENGERS=[{account:"Zonazul Mercado Saludable",current_challenged:"Funat",mechanism:"50-unit multibrand shelf/ecommerce test → replenishment",pilot:"plausible but unverified",procurement:"potentially easier, unverified",buyer_access:"unknown",recurrence:"more direct retail hypothesis",evidence:"active official store, insufficient botanical/buyer evidence",context_specificity:"moderate",learning:"tests smaller regional health retail",comparative_advantage:"not demonstrated strongly enough",decision:"INVESTIGATE OUTSIDE ACTIVE PORTFOLIO"}] as const;
export const AMOR_V2_SEARCH_QUALITY={V1:{queries:15,raw:90,unique_domains:56,unique_rate:0.622,identity_verified:24,qualified:18,qualified_rate:0.321,generic_query_count:5,context_trace_rate:0,procurement_compatible_rate:"unavailable",pilot_size_compatible_rate:"unavailable",recurrence_rate:"unavailable"},V2:{queries:8,raw:39,unique_domains:28,unique_rate:0.718,identity_verified:6,qualified:1,qualified_rate:0.036,generic_query_count:0,context_trace_rate:1,procurement_compatible_rate:0.167,pilot_size_compatible_rate:0.167,recurrence_rate:0.167,official_evidence_rate:0.214,false_positive_rate:0.821},interpretation:"V2 materially improved query traceability and unique-domain rate, but did not demonstrate better candidate yield. Strict context gates exposed that the returned web universe remained noisy; V2 search superiority is not demonstrated."} as const;
export const AMOR_V3R4_DECISION={id:null,status:"NOT CREATED — NO MATERIAL PORTFOLIO IMPROVEMENT",preserved_portfolio:AMOR_V3R3.id,retained:[...AMOR_V3R3.groups.first_test_sequence,...AMOR_V3R3.groups.strategic_priority,...AMOR_V3R3.groups.investigate_selectively],lowered:[],removed:[],new_accounts:[],external_investigation:["Zonazul Mercado Saludable"],reason:"No challenger showed a documented comparative advantage over an active V3R3 account."} as const;
export const AMOR_CONTEXT_VERDICT_V3={original:"context impact partially demonstrated",replay:"moderate impact demonstrated",post_search:"moderate impact demonstrated",reason:"Context compilation prevented noisy and structurally incompatible results from entering the portfolio, but replacement queries did not yet improve qualified yield or produce a superior account. Strong impact is not demonstrated."} as const;
export const AMOR_V2_COMPILER_LESSONS=["Commercial-mechanism terms improved traceability but search engines still returned editorial and directory pages.","Official-domain evidence expectations should be encoded through domain/site discovery stages, not only lexical query terms.","Gifting requires an explicit third-party curation discriminator after retrieval.","Hospitality queries need an account-first identity stage before mechanism evidence queries.","Distribution should remain deferred until a selective-buyer identity source exists.","Stop rules prevented a second batch and artificial portfolio turnover."] as const;
