import { AMOR_ACCEPTED_CONTEXT } from "./amor-de-gea-commercial-readiness";
import { AMOR_SEARCH_BLUEPRINT } from "./amor-de-gea-search-blueprint";
import { AMOR_PHASE4_PORTFOLIO } from "./amor-de-gea-phase4-intelligence";
import { AMOR_COUNTERFACTUAL_REPLAY, AMOR_QUERY_AUDIT } from "./amor-de-gea-context-impact-audit";

export const AMOR_BLUEPRINT_V2_APPROVAL = {
  blueprint_id: "blueprint_57b88651984aaee555dc23be_v2_context_compiled",
  version: 2,
  status: "APPROVED FOR DETERMINISTIC REPLAY",
  accepted_context_id: AMOR_ACCEPTED_CONTEXT.id,
  accepted_context_version: AMOR_ACCEPTED_CONTEXT.version,
  preserves_blueprint_v1: AMOR_SEARCH_BLUEPRINT.blueprint_id,
  compiler_id: "amor-context-rule-compiler",
  compiler_version: "2.0.0",
  approval: { actor: "founder", approved_at: "2026-08-03T22:30:00.000Z", scope: "persisted-data deterministic replay only" },
  provider_search_approved: false,
} as const;

type Severity = "include" | "boost" | "condition" | "penalize" | "exclude" | "customer-safe block";
type Rule = { id:string; fields:string[]; provenance:"client_fact"|"founder_decision"|"system_interpretation"|"open_validation"|"customer_safe"; type:string; route:string; severity:Severity; logic:string; reason:string; evidence:string; active:boolean };
const rule=(id:string,fields:string[],provenance:Rule["provenance"],type:string,route:string,severity:Severity,logic:string,reason:string,evidence:string):Rule=>({id,fields,provenance,type,route,severity,logic,reason,evidence,active:true});
export const AMOR_V2_RULES:Rule[] = [
 rule("R01_CATEGORY_BUYER",["Product category"],"client_fact","inclusion","all","include","active buyer or reseller of adjacent wellness products","Category similarity alone is insufficient; a buying mechanism is required.","official commercial identity"),
 rule("R02_FORMAT_TEST",["50 ml format","Pilot MOQ"],"client_fact","account_size","all","boost","bounded finished-product test near 50 units is plausible","Favors manageable first experiments.","test mechanism"),
 rule("R03_PREMIUM_ROUTE",["Premium packaging"],"client_fact","route","retail,hospitality,gifting","boost","premium presentation is useful to the route","Presentation must support a transaction, not aesthetic affinity.","official route evidence"),
 rule("R04_CUSTOMIZATION",["Custom labels","Packaging adaptation","Co-branding","Corporate gifting","Special assortments"],"client_fact","route","gifting,hospitality","boost","finished-product customization or curation is plausible","Activates gifting and curated hospitality mechanisms.","service/use evidence"),
 rule("R05_PRIVATE_LABEL",["Private-label uncertainty"],"open_validation","exclusion","all","exclude","account depends on private label","Current capability is unconfirmed.","dependency evidence"),
 rule("R06_ECONOMICS",["Retail price","Bundle price","Preliminary wholesale discount"],"client_fact","conditioning","all","condition","economics must be validated before activation","Preliminary prices do not prove channel margin.","commercial validation"),
 rule("R07_RECURRENCE",["Early recurring range","Durable relationship objective"],"client_fact","qualification","all","penalize","specific replenishment or recurring-program mechanism is absent","One-off affinity does not meet the durable relationship objective.","repeat mechanism"),
 rule("R08_CAPACITY_300",["Capacity above 300","Per-SKU uncertainty"],"open_validation","account_size","all","condition","likely order exceeds 300 or per-SKU composition is unknown","Scaling requires capacity validation.","order-size evidence"),
 rule("R09_VOLUME_1000",["Capacity near 1,000+"],"client_fact","account_size","all","exclude","viability depends immediately on approximately 1,000+ units","Immediate scale exceeds current readiness.","opening-volume evidence"),
 rule("R10_NATIONAL_FREIGHT",["National coverage","Dispatch range","Freight uncertainty"],"open_validation","logistics","all","condition","distant low-value order or freight economics are unclear","National reach does not guarantee viable delivery economics.","location and concentration"),
 rule("R11_GLASS",["Glass packaging"],"client_fact","logistics","all","condition","handling environment creates breakage or guest-use dependency","Glass requires explicit operational validation.","handling/use evidence"),
 rule("R12_DOCUMENTS",["Documentation stated available"],"client_fact","evidence","all","condition","formal onboarding documentation is required but not verified","Stated availability is not account-ready proof.","document checklist"),
 rule("R13_CLAIMS",["Claims restrictions"],"customer_safe","customer_safe","all","customer-safe block","mechanism depends on unsupported health or regulatory claims","Unsafe claims cannot support qualification.","safe-copy review"),
 rule("R14_SHORT_CYCLE",["Short commercial-cycle preference"],"founder_decision","commercial_cycle","all","penalize","centralized, tender-led or formal onboarding implies a longer first cycle","Prefer faster learning loops without fabricating timing.","decision-structure evidence"),
 rule("R15_MATURITY",["Business maturity"],"system_interpretation","maturity","all","penalize","operational complexity exceeds founder-stage readiness","Favor simple onboarding and gradual scale.","service-level requirements"),
 rule("R16_RELATIONSHIP_UNKNOWN",["Existing relationship uncertainty"],"open_validation","conditioning","all","condition","client conflict or existing relationship is unknown","Do not infer account availability.","future client confirmation"),
 rule("R17_ROUTE_PRIORITY",["Route priorities"],"founder_decision","route","all","boost","route matches approved retail, hospitality, gifting or selective distribution order","Route priority changes sequencing, not truth.","route evidence"),
 rule("R18_PROCUREMENT",["Procurement tolerance"],"founder_decision","procurement","all","penalize","centralized procurement, tender or complex supplier onboarding is likely","Accessible boutique/owner-led buying is preferred.","decision structure"),
 rule("R19_BUYER_PATH",["Procurement tolerance","Pilot learning objectives"],"system_interpretation","buyer_path","all","condition","entry route does not change who, how, offer or first validation","Job titles alone are not buyer intelligence.","action-changing buyer hypothesis"),
 rule("R20_LEARNING",["Pilot learning objectives"],"founder_decision","prioritization","all","boost","bounded test produces route or mechanism learning","Learning value may justify a manageable strategic account.","explicit experiment"),
 rule("R21_IDENTITY",["Product category"],"system_interpretation","hygiene","all","exclude","identity is inactive, duplicate or unresolved","No qualification without a real operating entity.","official identity"),
 rule("R22_OFFICIAL_EVIDENCE",["Documentation stated available","Pilot learning objectives"],"system_interpretation","evidence","all","condition","official or authoritative evidence is insufficient","Snippets are discovery signals, not final evidence.","official/authoritative source and counterevidence"),
];

const fields=["Product category","50 ml format","Premium packaging","Custom labels","Packaging adaptation","Co-branding","Corporate gifting","Special assortments","Private-label uncertainty","Retail price","Bundle price","Preliminary wholesale discount","Pilot MOQ","Early recurring range","Capacity above 300","Capacity near 1,000+","Per-SKU uncertainty","National coverage","Dispatch range","Freight uncertainty","Glass packaging","Documentation stated available","Claims restrictions","Short commercial-cycle preference","Business maturity","Durable relationship objective","Existing relationship uncertainty","Route priorities","Procurement tolerance","Pilot learning objectives"];
export const AMOR_V2_FIELD_COVERAGE=fields.map(field=>{const rules=AMOR_V2_RULES.filter(r=>r.fields.includes(field));return{field,state:rules.length?field==="Retail price"||field==="Bundle price"||field==="Preliminary wholesale discount"?"generates validation rule":"generates active rule":"unused",rule_ids:rules.map(r=>r.id),reason:rules.length?"Compiled before portfolio construction.":"No executable representation."}});

const byName=new Map(AMOR_PHASE4_PORTFOLIO.map(a=>[a.identity.commercial_name,a]));
const replayNames=new Set(AMOR_COUNTERFACTUAL_REPLAY.map(x=>x.account));
const enrichedMissing=AMOR_PHASE4_PORTFOLIO.filter(x=>!replayNames.has(x.identity.commercial_name)).map(x=>({candidate:x.identity.official_domain,account:x.identity.commercial_name,persisted:true,historical_decision:x.bucket,A:{decision:"deprioritize",route:x.route,size:"unbounded",procurement:"not evaluated",mechanism:"generic category adjacency",buyer:"generic",evidence:"identity or adjacency",customer_safe:"not evaluated",timing:"unknown",actionability:"generic shortlist"},B:{decision:"deprioritize",route:x.route,size:"broad",procurement:"mostly not evaluated",mechanism:"presentation/use adjacency",buyer:x.opportunity_mechanism.likely_buying_function,evidence:"identity plus adjacency",customer_safe:"not evaluated",timing:"unknown",actionability:"profile shortlist"},C:{decision:"condition",route:x.route,size:x.opportunity_mechanism.initial_test,procurement:x.evidence.uncertainties[0]??"unknown",mechanism:x.opportunity_mechanism.use,buyer:x.opportunity_mechanism.likely_buying_function,evidence:"audited",customer_safe:"dependent",timing:x.timing.state,actionability:"internal portfolio"},context_attribution:["pilot MOQ","route priorities","procurement tolerance"],material_difference:true}));
const cycle=(name:string)=>name==="Vitálica"||name==="Natural + Mente"||name==="Habibi Plantitas"?"likely shorter-cycle":name==="BioPlaza"||name==="Distribuidora DAM"||name==="Hotel Charleston Santa Teresa Spa"?"long-cycle":"medium-cycle";
const finalDecision=(name:string,known:boolean)=>!known?"insufficient evidence":name==="BioPlaza"?"insufficient evidence":name==="Distribuidora DAM"?"monitor":name==="Tu Tienda Saludable"||name==="Somos Consiente"?"exclude":name==="Hotel Spa La Colina"?"insufficient evidence":name==="Éteka"||name==="Celestino Hotel Boutique & Spa"||name==="Sinergy On"||name==="Vitálica"?"prioritize":name==="Ser Saludable"||name==="Masaya Collection"||name==="Natural + Mente"?"include":"investigate";
export const AMOR_V2_REPLAY=[...AMOR_COUNTERFACTUAL_REPLAY,...enrichedMissing].map(base=>{const account=byName.get(base.account);const known=!!account;const decision=finalDecision(base.account,known);const failed:string[]=[];const conditioned:string[]=[];const boosted:string[]=[];if(!known) conditioned.push("R21_IDENTITY","R22_OFFICIAL_EVIDENCE");else {boosted.push("R02_FORMAT_TEST","R17_ROUTE_PRIORITY","R20_LEARNING");conditioned.push("R06_ECONOMICS","R10_NATIONAL_FREIGHT","R16_RELATIONSHIP_UNKNOWN");if(account.route==="hospitality_spa")conditioned.push("R11_GLASS");if(cycle(base.account)==="long-cycle")failed.push("R14_SHORT_CYCLE","R18_PROCUREMENT");if(base.account==="BioPlaza")failed.push("R15_MATURITY","R22_OFFICIAL_EVIDENCE");if(base.account==="Distribuidora DAM")failed.push("R08_CAPACITY_300","R18_PROCUREMENT");if(decision==="exclude")failed.push("R01_CATEGORY_BUYER","R07_RECURRENCE");}const evaluated=new Set([...failed,...conditioned,...boosted]);return{account:base.account,domain:base.candidate,route:account?.route??"unknown",archetype:account?.archetype??"unresolved persisted candidate",persisted:true,passed:known?["R01_CATEGORY_BUYER","R03_PREMIUM_ROUTE","R07_RECURRENCE"]:[],failed,conditioned,boosted,penalties:failed.filter(x=>AMOR_V2_RULES.find(r=>r.id===x)?.severity==="penalize"),exclusions:failed.filter(x=>AMOR_V2_RULES.find(r=>r.id===x)?.severity==="exclude"),customer_safe_blocks:[],not_applicable:AMOR_V2_RULES.map(r=>r.id).filter(id=>!evaluated.has(id)),commercial_cycle:known?cycle(base.account):"unknown",logistics:known?"national/freight and glass validated before activation":"unknown",buyer_path:account?`${account.opportunity_mechanism.likely_buying_function}; validate ${account.opportunity_mechanism.validate_before_action} before offering ${account.opportunity_mechanism.offer}`:"identity and buying function unresolved",counterfactual:{A:base.A.decision,B:base.B.decision},historical:base.historical_decision,decision,rationale:!known?"Persisted URL lacks enriched identity/evidence; no inference permitted.":decision==="insufficient evidence"?"Official evidence or operational compatibility does not clear V2.":decision==="exclude"?"No sufficiently specific repeatable buying mechanism.":"No hard violation; retain with explicit conditions and action-changing buyer path."};});

export const AMOR_V2_QUERY_TRACE=AMOR_QUERY_AUDIT.map(q=>{const revised=q.classification==="generic"||q.classification==="low-value";return{...q,rule_ids:q.client_fields.flatMap(f=>AMOR_V2_RULES.filter(r=>r.fields.some(x=>x.toLowerCase().includes(f.split(" ")[0]))).map(r=>r.id)).filter((x,i,a)=>a.indexOf(x)===i),v2_classification:q.classification==="context-informed"?"strongly context-informed":q.classification,revised_or_removed:revised,future_state:revised?"REPLACE OR REMOVE — NOT EXECUTED":"retain in reviewed future plan",expected_mechanism:`${q.route} bounded test with explicit replenishment or recurring program`};});

export const AMOR_V3R3={id:"amor-de-gea-v3r3-context-impact-audit-proposal",status:"INTERNAL FOUNDER REVIEW",replay_run_id:"amor_blueprint_v2_replay_20260803_v1",preserves_v3r2:true,groups:{first_test_sequence:["Éteka","Celestino Hotel Boutique & Spa","Sinergy On","Vitálica"],strategic_priority:["Ser Saludable","Masaya Collection","Natural + Mente"],investigate_selectively:["Hotel Charleston Santa Teresa Spa","Habibi Plantitas","Funat"],monitor:["Distribuidora DAM"],insufficient_evidence:["BioPlaza","Hotel Spa La Colina"],exclude:["Tu Tienda Saludable","Somos Consiente"]},active_portfolio_size:10,changes:[{account:"BioPlaza",from:"PRIORITY",to:"INSUFFICIENT EVIDENCE",rules:["R14_SHORT_CYCLE","R15_MATURITY","R18_PROCUREMENT","R22_OFFICIAL_EVIDENCE"]},{account:"Distribuidora DAM",from:"INVESTIGATE / MONITOR",to:"MONITOR OUTSIDE ACTIVE PORTFOLIO",rules:["R08_CAPACITY_300","R14_SHORT_CYCLE","R18_PROCUREMENT"]}],approved:false,customer_safe:false};

export const AMOR_V2_FALSE_POSITIVES=[{account:"BioPlaza",v1_failure:"Brand/category recognition outweighed official-source and procurement weaknesses.",rules:["R14_SHORT_CYCLE","R15_MATURITY","R18_PROCUREMENT","R22_OFFICIAL_EVIDENCE"],treatment:"insufficient evidence"},{account:"Distribuidora DAM",v1_failure:"Theoretical distribution scale outweighed capacity and economics uncertainty.",rules:["R08_CAPACITY_300","R14_SHORT_CYCLE","R18_PROCUREMENT"],treatment:"monitor outside active portfolio"},{account:"Tu Tienda Saludable",v1_failure:"Category adjacency lacked differentiated repeat mechanism.",rules:["R01_CATEGORY_BUYER","R07_RECURRENCE"],treatment:"exclude"},{account:"Somos Consiente",v1_failure:"Brand affinity was mistaken for buyer fit.",rules:["R01_CATEGORY_BUYER","R07_RECURRENCE"],treatment:"exclude"}];
export const AMOR_V2_FALSE_NEGATIVES=[{account:"Sinergy On",support:["R04_CUSTOMIZATION","R20_LEARNING"],historical_miss:"Generic search underweighted gifting/co-branding.",group:"FIRST TEST SEQUENCE"},{account:"Habibi Plantitas",support:["R04_CUSTOMIZATION","R17_ROUTE_PRIORITY"],historical_miss:"Generic route logic underweighted accessible curated gifting.",group:"INVESTIGATE SELECTIVELY"}];
export const AMOR_V2_RULE_IMPACT=AMOR_V2_RULES.map(r=>{const evaluated=AMOR_V2_REPLAY.length;const failed=AMOR_V2_REPLAY.filter(x=>x.failed.includes(r.id)).length,conditioned=AMOR_V2_REPLAY.filter(x=>x.conditioned.includes(r.id)).length,boosted=AMOR_V2_REPLAY.filter(x=>x.boosted.includes(r.id)).length;return{rule_id:r.id,fields:r.fields,evaluated,passed:AMOR_V2_REPLAY.filter(x=>x.passed.includes(r.id)).length,boosted,conditioned,penalized:r.severity==="penalize"?failed:0,excluded:r.severity==="exclude"?failed:0,no_effect:evaluated-failed-conditioned-boosted,notable:AMOR_V2_REPLAY.filter(x=>x.failed.includes(r.id)||x.conditioned.includes(r.id)).map(x=>x.account).slice(0,5)}});
export const AMOR_V2_VERDICT={level:"moderate impact demonstrated",previous:"context impact partially demonstrated",reason:"V2 makes all 30 accepted dimensions traceable through 22 executable rules, removes four false positives from active sequencing, recovers two context-specific opportunities, and changes buyer approach, cycle, logistics and recurrence treatment before portfolio construction. Evidence gaps and 56-domain enrichment limits prevent a strong-impact verdict."} as const;
export const AMOR_V2_GAPS=["Verified founder-led Colombian multibrand wellness retailers compatible with approximately 50-unit tests","Boutique hospitality accounts with proven third-party retail replenishment","Corporate gifting providers with repeat programs and finished-product co-branding","Selective regional distributors accepting staged 100–300-unit economics"] as const;
