import type {ClientContext,OpportunityThesis,Decision,FitState} from "./account-opportunity-synthesis";
export const CLIENT_CONTEXT_REVIEW_VERSION="client-context-review-v1";
export type GapCategory="offer"|"economic"|"operational"|"compliance"|"commercial"|"strategic"|"disqualifier";
export type GapPriority="critical_blocker"|"high_leverage"|"important"|"useful"|"low_priority"|"not_needed_now";
export type AnswerSource="client_direct"|"client_document"|"public_website"|"prior_configuration"|"admin_entry"|"inferred"|"unknown";
export type ConflictState="none"|"possible_conflict"|"confirmed_conflict"|"resolved"|"stale_value"|"superseded";
const hash=(v:string)=>{let h=2166136261;for(let i=0;i<v.length;i++){h^=v.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(36)};
const META:Record<string,{category:GapCategory,impact:string[],sections:string[],who:string,document:boolean,interview:boolean,effort:"low"|"medium"|"high",critical:boolean,question:string,format:string}>={
 business_model:{category:"strategic",impact:["strategic_fit","commercial_accessibility_fit"],sections:["Client context summary","Account-client fit"],who:"client commercial lead",document:true,interview:true,effort:"low",critical:false,question:"Which B2B business model does Amor de Gea currently support?",format:"multi-select"},
 company_stage:{category:"strategic",impact:["client_capacity_fit"],sections:["Client context summary","Risks"],who:"client leadership",document:false,interview:true,effort:"low",critical:false,question:"Which company stage best describes Amor de Gea today?",format:"enum"},
 price_positioning:{category:"economic",impact:["economic_potential_fit","brand_positioning_fit"],sections:["Commercial use case","Risks"],who:"client commercial lead",document:true,interview:false,effort:"low",critical:true,question:"What verified wholesale price range and market positioning apply to the current B2B offer?",format:"range"},
 minimum_order:{category:"economic",impact:["account_scale_fit","operational_feasibility"],sections:["Commercial use case","Commercial sequence"],who:"client operations",document:true,interview:false,effort:"low",critical:true,question:"What is the minimum order quantity or value for one B2B account?",format:"numeric"},
 fulfillment_constraints:{category:"operational",impact:["operational_feasibility","commercial_accessibility_fit"],sections:["Access path","Risks"],who:"client operations",document:true,interview:true,effort:"medium",critical:true,question:"Which fulfillment, shipping or inventory constraints apply to B2B orders?",format:"free text"},
 certifications:{category:"compliance",impact:["operational_feasibility","offer_category_fit"],sections:["Commercial use case","Risks","Limitations"],who:"client compliance lead",document:true,interview:false,effort:"medium",critical:true,question:"Which current registrations, certifications and compliance documents can be evidenced?",format:"document upload"},
 product_formats:{category:"offer",impact:["offer_category_fit","channel_fit"],sections:["Commercial use case","Account-client fit"],who:"client product lead",document:true,interview:false,effort:"low",critical:true,question:"Which product formats and packaging configurations are currently available for B2B sale?",format:"multi-select"},
 customization_capacity:{category:"offer",impact:["operational_feasibility","brand_positioning_fit"],sections:["Commercial use case","Risks"],who:"client operations",document:true,interview:true,effort:"medium",critical:false,question:"What product or packaging customization is operationally available today?",format:"multi-select"},
 distribution_capability:{category:"operational",impact:["commercial_accessibility_fit","geography_fit","client_capacity_fit"],sections:["Access path","Commercial sequence","Risks"],who:"client operations",document:true,interview:true,effort:"medium",critical:true,question:"Through which geographies and delivery methods can Amor de Gea reliably fulfill B2B orders?",format:"multi-select"},
 production_capacity:{category:"operational",impact:["client_capacity_fit","account_scale_fit"],sections:["Commercial use case","Risks"],who:"client operations",document:true,interview:true,effort:"medium",critical:true,question:"What maximum monthly B2B volume can Amor de Gea supply reliably to one account?",format:"numeric"},
 account_size_constraints:{category:"commercial",impact:["account_scale_fit"],sections:["Account shortlist","Portfolio strategy"],who:"client commercial lead",document:false,interview:true,effort:"low",critical:true,question:"What account size or expected order range is commercially suitable today?",format:"range"},
 current_partnerships:{category:"commercial",impact:["relationship_path_plausibility","commercial_accessibility_fit"],sections:["Access path","Portfolio strategy"],who:"client commercial lead",document:true,interview:true,effort:"medium",critical:false,question:"Which current distributors, channel partners or B2B references may affect account access?",format:"free text"},
 preferred_deal_type:{category:"commercial",impact:["relationship_path_plausibility","strategic_fit"],sections:["Access path","Commercial sequence"],who:"client commercial lead",document:false,interview:true,effort:"low",critical:false,question:"Which commercial motions are preferred: direct wholesale, distributor, pilot, gifting or partnership?",format:"multi-select"},
 sales_cycle_tolerance:{category:"commercial",impact:["commercial_accessibility_fit","strategic_fit"],sections:["Commercial sequence","Risks"],who:"client leadership",document:false,interview:true,effort:"low",critical:false,question:"What B2B sales-cycle length is acceptable before an account becomes impractical?",format:"range"},
 margins:{category:"economic",impact:["economic_potential_fit","operational_feasibility"],sections:["Commercial use case","Risks"],who:"client finance/commercial lead",document:true,interview:true,effort:"medium",critical:true,question:"What minimum gross-margin or distributor-margin constraints must a B2B opportunity satisfy?",format:"range"},
 white_label_capacity:{category:"offer",impact:["offer_category_fit","operational_feasibility"],sections:["Commercial use case","Risks"],who:"client product/operations",document:true,interview:true,effort:"medium",critical:false,question:"Is white-label production currently available, unavailable or conditional?",format:"enum"},
 delivery_radius:{category:"operational",impact:["geography_fit","commercial_accessibility_fit"],sections:["Access path","Account shortlist"],who:"client operations",document:true,interview:false,effort:"low",critical:true,question:"What exact cities, departments or national zones can be served reliably today?",format:"multi-select"},
};
export interface ContextGap{gap_id:string;field:string;category:GapCategory;current_state:"unanswered";current_source:string;context_state:"explicit"|"inferred"|"missing";affected_accounts:string[];affected_theses:string[];affected_fit_dimensions:string[];affected_access_paths:string[];affected_use_cases:string[];affected_buying_path_assumptions:string[];affected_decisions:Decision[];affected_report_sections:string[];priority:GapPriority;priority_dimensions:{decision_impact:number;accounts_affected:number;report_impact:number;feasibility_impact:number;client_specificity_impact:number;confidence_impact:number;effort:number;urgency:number;reversibility:number;dependency_depth:number};effort:string;who_should_answer:string;document_can_answer:boolean;client_interview_required:boolean;blocking:boolean}
export function inventoryContextGaps(context:ClientContext,theses:OpportunityThesis[]):ContextGap[]{
 return context.unknown_fields.map<ContextGap>(field=>{const m=META[field];if(!m)throw new Error(`unclassified_context_gap:${field}`);const blocking=m.critical;const priority:GapPriority=blocking?"critical_blocker":m.impact.length>1?"high_leverage":"important";return {gap_id:`gap_${hash(`${context.context_id}:${field}`)}`,field,category:m.category,current_state:"unanswered",current_source:"Block 11 canonical client context",context_state:"missing",affected_accounts:theses.map(t=>t.account_id),affected_theses:theses.map(t=>t.thesis_id),affected_fit_dimensions:m.impact,affected_access_paths:theses.map(t=>t.access_paths[0]?.type).filter(Boolean),affected_use_cases:theses.flatMap(t=>t.use_cases.map(u=>u.use_case_id)),affected_buying_path_assumptions:["pilot","approval_sequence","procurement_role"],affected_decisions:Array.from(new Set(theses.map(t=>t.decision))),affected_report_sections:m.sections,priority,priority_dimensions:{decision_impact:blocking?5:3,accounts_affected:theses.length,report_impact:m.sections.length,feasibility_impact:m.impact.includes("operational_feasibility")?5:3,client_specificity_impact:4,confidence_impact:blocking?5:3,effort:m.effort==="low"?1:m.effort==="medium"?3:5,urgency:blocking?5:2,reversibility:4,dependency_depth:m.impact.length},effort:m.effort,who_should_answer:m.who,document_can_answer:m.document,client_interview_required:m.interview,blocking}}).sort((a,b)=>["critical_blocker","high_leverage","important","useful","low_priority","not_needed_now"].indexOf(a.priority)-["critical_blocker","high_leverage","important","useful","low_priority","not_needed_now"].indexOf(b.priority)||a.field.localeCompare(b.field));
}
export interface IntakeQuestion{question_id:string;gap_id:string;text:string;category:GapCategory;field:string;why:string;affected_accounts:string[];affected_theses:string[];possible_answers:string[];validation_type:string;evidence_required:string[];who_should_answer:string;answer_format:string;document_can_answer:boolean;interview_required:boolean;expected_decision_impact:string;next_system_action:string;priority:GapPriority}
export function questionsForGaps(gaps:ContextGap[]):IntakeQuestion[]{return gaps.filter(g=>["critical_blocker","high_leverage","important"].includes(g.priority)).map(g=>{const m=META[g.field];return {question_id:`q_${hash(g.gap_id)}`,gap_id:g.gap_id,text:m.question,category:g.category,field:g.field,why:`Affects ${g.affected_fit_dimensions.join(", ")} and ${g.affected_report_sections.join(", ")}.`,affected_accounts:g.affected_accounts,affected_theses:g.affected_theses,possible_answers:["verified value","unknown","not applicable"],validation_type:m.document?"document_or_client_confirmation":"client_confirmation",evidence_required:m.document?["supporting document or evidence reference"]:["explicit client answer"],who_should_answer:m.who,answer_format:m.format,document_can_answer:m.document,interview_required:m.interview,expected_decision_impact:g.blocking?"May enable or disqualify all dependent account theses.":"May strengthen, weaken or redirect access/use-case hypotheses.",next_system_action:"Create reviewed answer, then recalculate affected theses deterministically.",priority:g.priority}})}
export interface ClientAnswer{answer_id:string;question_id:string;client_id:string;value:unknown;normalized_value:unknown;unit:string|null;provenance:string[];answer_source:AnswerSource;context_state:"explicit"|"inferred";confidence:number;supplied_by:string;supplied_at:string;verified_by:string|null;verified_at:string|null;review_status:"unreviewed"|"accepted"|"rejected";contradiction_state:ConflictState;notes:string|null;expires_at:string|null}
export interface IntakeSession{intake_id:string;tenant_id:string|null;client_id:string;context_version:string;status:"draft"|"in_progress"|"submitted"|"under_review"|"accepted"|"partially_accepted"|"rejected"|"superseded"|"expired";created_by:string;started_at:string;completed_at:string|null;question_set_version:string;methodology_version:string;answers:ClientAnswer[];evidence_refs:string[];unresolved_questions:string[];conflicting_answers:string[];reviewer_state:"unreviewed"|"reviewed";supersedes_id:string|null;created_at:string;fixture_mode:boolean}
export function createIntake(input:{tenant_id:string|null;client_id:string;context_version:string;created_by:string;started_at:string;questions:IntakeQuestion[];fixture_mode?:boolean}):IntakeSession{return {intake_id:`intake_${hash(`${input.client_id}:${input.context_version}:${input.started_at}`)}`,tenant_id:input.tenant_id,client_id:input.client_id,context_version:input.context_version,status:"draft",created_by:input.created_by,started_at:input.started_at,completed_at:null,question_set_version:CLIENT_CONTEXT_REVIEW_VERSION,methodology_version:CLIENT_CONTEXT_REVIEW_VERSION,answers:[],evidence_refs:[],unresolved_questions:input.questions.map(q=>q.question_id),conflicting_answers:[],reviewer_state:"unreviewed",supersedes_id:null,created_at:input.started_at,fixture_mode:input.fixture_mode??false}}
export interface ContextVersion{version_id:string;client_id:string;version:number;status:"active"|"draft"|"superseded"|"historical";values:Record<string,ClientAnswer>;previous_version_id:string|null;changed_fields:string[];reason:string;source_intake_id:string;effective_at:string;reviewer:string;affected_theses:string[];recalculation_status:"pending"|"completed";immutable:true}
export function acceptIntake(intake:IntakeSession,prior:ContextVersion|null,reviewer:string,at:string,affected:string[]):ContextVersion{if(!["submitted","under_review"].includes(intake.status))throw new Error("intake_not_reviewable");if(intake.fixture_mode)throw new Error("fixture_intake_cannot_enter_production");const accepted=intake.answers.filter(a=>a.review_status==="accepted"&&["client_direct","client_document","admin_entry"].includes(a.answer_source));const values={...(prior?.values??{})};for(const a of accepted)values[a.question_id]=a;const changed=accepted.map(a=>a.question_id);return {version_id:`ctxv_${hash(`${intake.client_id}:${prior?.version??0+1}:${changed.join(",")}:${at}`)}`,client_id:intake.client_id,version:(prior?.version??0)+1,status:"active",values,previous_version_id:prior?.version_id??null,changed_fields:changed,reason:"Accepted reviewed intake answers.",source_intake_id:intake.intake_id,effective_at:at,reviewer,affected_theses:affected,recalculation_status:"pending",immutable:true}}
export type FeasibilityState="feasible"|"likely_feasible"|"uncertain"|"likely_infeasible"|"infeasible"|"insufficient_context"|"not_applicable";
export interface FeasibilityDimension{dimension:string;state:FeasibilityState;client_fields:string[];account_requirements:string[];evidence:string[];assumptions:string[];blocker:string|null;next_verification:string;confidence:number}
const FEAS:{[k:string]:string[]}={product:["product_formats"],pricing:["price_positioning","minimum_order"],margin:["margins"],fulfillment:["fulfillment_constraints"],geographic:["distribution_capability","delivery_radius"],capacity:["production_capacity"],certification:["certifications"],procurement:["preferred_deal_type"],pilot:["customization_capacity"],sales_cycle:["sales_cycle_tolerance"],operational_complexity:["fulfillment_constraints","production_capacity"],implementation_burden:["certifications","product_formats"]};
const answerFor=(version:ContextVersion|null,field:string)=>Object.values(version?.values??{}).find(a=>typeof a.normalized_value==="object"&&a.normalized_value!==null&&(a.normalized_value as {field?:string}).field===field);
export function assessFeasibility(version:ContextVersion|null):FeasibilityDimension[]{return Object.entries(FEAS).map(([dimension,fields])=>{const found=fields.map(f=>answerFor(version,f));const complete=found.every(Boolean);const negative=found.some(a=>typeof (a?.normalized_value as {value?:unknown})?.value==="boolean"&&(a!.normalized_value as {value:boolean}).value===false);return {dimension,state:!complete?"insufficient_context":negative?"infeasible":"likely_feasible",client_fields:fields,account_requirements:[],evidence:found.filter(Boolean).flatMap(a=>a!.provenance),assumptions:[],blocker:!complete?`Missing ${fields.filter((_,i)=>!found[i]).join(", ")}.`:negative?"Explicit client answer indicates infeasibility.":null,next_verification:`Provide and review ${fields.join(", ")}.`,confidence:complete?.8:0}})}
export interface ThesisDelta{delta_id:string;account_id:string;prior_state:{decision:Decision;confidence:number};current_state:{decision:Decision;confidence:number};responsible_fields:string[];evidence:string[];changes:string[];materiality:"none"|"low"|"medium"|"high";confidence:number;reviewer_state:"unreviewed";baseline:boolean}
export function recalculateThesis(prior:OpportunityThesis,version:ContextVersion,previous:ContextVersion|null):{thesis:OpportunityThesis;delta:ThesisDelta}{
  const feasibility=assessFeasibility(version);const infeasible=feasibility.some(x=>x.state==="infeasible");const resolved=feasibility.filter(x=>x.state==="likely_feasible").length;
  const decision:Decision=infeasible?"exclude":prior.decision;const confidence=Math.max(0,Math.min(.85,prior.confidence.overall+(resolved*.015)-(infeasible?.3:0)));
  const thesis={...prior,decision,confidence:{...prior.confidence,overall:confidence,strategy:Math.max(0,prior.confidence.strategy+(resolved*.01)-(infeasible?.3:0)),limiting_factor:infeasible?"commercial_feasibility":prior.confidence.limiting_factor},limitations:prior.limitations.filter(x=>!version.changed_fields.some(f=>x.includes(f))),review_state:"unreviewed" as const};
  const changes:string[]=[];if(decision!==prior.decision)changes.push("decision_changed","account_disqualified");if(confidence>prior.confidence.overall)changes.push("client_fit_strengthened","confidence_changed");if(confidence<prior.confidence.overall)changes.push("client_fit_weakened","confidence_changed");
  const baseline=!previous;return {thesis,delta:{delta_id:`delta_${hash(`${prior.thesis_id}:${version.version_id}`)}`,account_id:prior.account_id,prior_state:{decision:prior.decision,confidence:prior.confidence.overall},current_state:{decision,confidence},responsible_fields:version.changed_fields,evidence:Object.values(version.values).flatMap(a=>a.provenance),changes:baseline?[]:changes,materiality:baseline?"none":decision!==prior.decision?"high":changes.length?"medium":"none",confidence:.8,reviewer_state:"unreviewed",baseline}};
}
export type SafetyState="internal_only"|"context_incomplete"|"evidence_incomplete"|"review_required"|"safe_with_strong_limitations"|"customer_safe"|"expired"|"rejected";
export interface SafetyAssessment{assessment_id:string;thesis_id:string;state:SafetyState;gates:Array<{gate:string;passed:boolean;reason:string}>;customer_safe_content:{identity:string;fit:string;timing:string;limitations:string[]}|null;internal_only:true;ranking_impact:"off"}
export function assessCustomerSafety(thesis:OpportunityThesis,input:{context_complete:boolean;feasibility_resolved:boolean;human_reviewed:boolean;central_claims_traceable:boolean;conflict:boolean;buying_intent_claimed:boolean;fresh:boolean}):SafetyAssessment{const gates=[["client_context",input.context_complete,"Verified context incomplete."],["identity",thesis.identity_confidence>=.8,"Identity not confirmed."],["evidence",input.central_claims_traceable,"Central claims not traceable."],["claim_separation",!input.buying_intent_claimed,"Unsupported buying intent."],["client_fit",thesis.gates.find(g=>g.gate==="client_fit")?.state==="pass","Client fit unsupported."],["feasibility",input.feasibility_resolved,"Critical feasibility unresolved."],["timing_honesty",thesis.why_now.state==="no_current_timing"||thesis.why_now.evidence.length>0,"Timing not honest."],["counterevidence",!!thesis.counterevidence.alternative_explanation,"Counterevidence absent."],["limitations",thesis.limitations.length>0,"Limitations absent."],["review",input.human_reviewed,"Human review incomplete."],["freshness",input.fresh,"Context/evidence stale."],["conflict",!input.conflict,"Context conflict unresolved."]].map(([gate,passed,reason])=>({gate:gate as string,passed:passed as boolean,reason:reason as string}));const failed=gates.filter(g=>!g.passed);let state:SafetyState="customer_safe";if(!input.human_reviewed)state="review_required";if(!input.context_complete||input.conflict)state="context_incomplete";else if(!input.central_claims_traceable||input.buying_intent_claimed)state="evidence_incomplete";else if(failed.length&&input.human_reviewed&&input.feasibility_resolved)state="safe_with_strong_limitations";return {assessment_id:`safety_${hash(`${thesis.thesis_id}:${gates.map(g=>g.passed).join("")}`)}`,thesis_id:thesis.thesis_id,state,gates,customer_safe_content:state==="customer_safe"||state==="safe_with_strong_limitations"?{identity:`${thesis.account_name} (${thesis.domain})`,fit:thesis.opportunity_statement,timing:thesis.why_now.statement,limitations:thesis.limitations}:null,internal_only:true,ranking_impact:"off"}}
export function validationShortlist(theses:OpportunityThesis[],safety:SafetyAssessment[]){return theses.map(t=>{const s=safety.find(x=>x.thesis_id===t.thesis_id)!;return {account:t.account_name,current_decision:t.decision,context_quality:t.context_quality,thesis_confidence:t.confidence.overall,feasibility_state:"insufficient_context",customer_safety_state:s.state,state:s.state==="context_incomplete"?"blocked_by_client_context":"ready_for_thesis_review",blockers:s.gates.filter(g=>!g.passed).map(g=>g.gate),next_reviewer_action:"Complete critical client context, then review thesis and feasibility.",review_priority:"high"}})}
export function sectionReadiness(theses:OpportunityThesis[],gaps:ContextGap[]){const sections=["Client context summary","Market landscape","Buyer segments","Verified company universe","Account shortlist","Account identity","Account-client fit","Commercial use case","Access path","Buying path","Why This Account","Why Now","Why Not Now","Counterevidence","Risks","Monitoring trigger","Portfolio strategy","Commercial sequence","Methodology","Limitations"];return sections.map(section=>{const missing=gaps.filter(g=>g.affected_report_sections.includes(section)).map(g=>g.field);const factual=["Market landscape","Buyer segments","Verified company universe","Account identity","Methodology"].includes(section);return {section,state:factual?"ready_with_limitations":missing.length?"blocked":"internal_only",supporting_outputs:theses.map(t=>t.thesis_id),missing_context:missing,missing_evidence:[],review_status:"unreviewed",customer_safety_state:"review_required"}})}
