import block10 from "../../ml/data/entity-resolution/amor-de-gea-block10-2026-07-30T14-24-06-487Z.json";
import block11 from "../../ml/data/opportunity-synthesis/amor-de-gea-block11-2026-07-30T15-51-48-651Z.json";
import block12 from "../../ml/data/client-context-review/amor-de-gea-block12-2026-07-30T16-09-40-801Z.json";
export const AMOR_PILOT_ID="amor-de-gea";
export const PILOT_WORKSPACE_VERSION="amor-pilot-workspace-v1";
export const LEGACY_PILOT_ALIASES=["amor_de_gea","pilot-amor-de-gea","amor-de-gea-pilot"];
export function canonicalPilotId(value:string){return value===AMOR_PILOT_ID||LEGACY_PILOT_ALIASES.includes(value)?AMOR_PILOT_ID:null}
export interface PilotWorkspace{
 pilot:{pilot_id:string;tenant_id:null;client_id:string;client_name:string;slug:string;production_status:"internal";status:"context_required";active_context_version:null;active_account_ids:string[];methodology_version:string;source_runs:string[];created_at:string;updated_at:string;last_intelligence_refresh:string;last_human_review:null;readiness:string;blockers:string[]};
 overview:{context_completeness:number;accounts:number;decisions:Record<string,number>;theses:number;reviewed:number;signals:number;timing_coverage:number;evidence_coverage:string;critical_blockers:number;customer_safe:number;report_ready:number;diagnosis:string;next_action:string};
 questions:any[];accounts:any[];theses:any[];feasibility:any[];safety:any[];sections:any[];shortlist:any[];activity:Array<{event_type:string;actor:string;timestamp:string;object:string;summary:string;methodology_version:string;provenance:string[]}>;
 checklist:Array<{step:number;label:string;status:"complete"|"blocked"|"pending";owner:string;dependency:string|null;blocker:string|null;completion_criterion:string}>;
 reconciliation:Array<{data_type:string;expected:number;supabase:number|null;artifact:number;canonical:number;orphaned:number|null;missing:number;action:string;production_availability:string}>;
 availability:{canonical_artifacts:"available";database:"unverified"|"available"|"partial";message:string};final_report_generation:"disabled";internal_only:true;ranking_impact:"off";
}
export function buildPilotWorkspace():PilotWorkspace{
 const accounts=(block11 as any).theses.map((t:any)=>{const id=(block10 as any).accounts.find((a:any)=>a.domain===t.domain);const f=(block12 as any).feasibility.find((x:any)=>x.account_id===t.account_id);const safety=(block12 as any).safety.find((x:any)=>x.thesis_id===t.thesis_id);return {...t,identity:id?.identity_profile??null,feasibility:f?.dimensions??[],safety}});
 const updated=(block12 as any).generated_at;const ids=accounts.map((a:any)=>a.account_id);
 const activity=[{event_type:"pilot_reconciled",actor:"system",timestamp:updated,object:AMOR_PILOT_ID,summary:"Canonical workspace assembled from reviewed Intelligence artifacts; no client answer created.",methodology_version:PILOT_WORKSPACE_VERSION,provenance:["Block 10","Block 11","Block 12"]},...accounts.map((a:any)=>({event_type:"thesis_generated",actor:"system",timestamp:(block11 as any).generated_at,object:a.thesis_id,summary:`Internal thesis generated for ${a.account_name}.`,methodology_version:a.methodology_version,provenance:[a.domain]}))];
 const checklist=["Confirm pilot identity","Confirm six-account scope","Complete critical client context","Review accepted context","Recalculate theses","Review six theses","Resolve evidence gaps","Resolve feasibility blockers","Complete customer-safety review","Reassess report sections","Approve report preparation","Generate final report in a later block"].map((label,i)=>({step:i+1,label,status:(i<2?"complete":i===11?"pending":"blocked") as "complete"|"blocked"|"pending",owner:i<2?"LeadLens":"Admin reviewer",dependency:i?String(i):null,blocker:i<2?null:"Required client context/review gates remain incomplete.",completion_criterion:i<2?"Canonical state verified.":"All preceding review and evidence gates pass."}));
 const recon=[["identity profiles",6,6],["opportunity theses",6,6],["context questions",17,17],["feasibility assessments",6,6],["safety assessments",6,6],["report sections",20,20],["accepted answers",0,0]].map(([data_type,expected,artifact])=>({data_type:String(data_type),expected:Number(expected),supabase:null,artifact:Number(artifact),canonical:Number(artifact),orphaned:null,missing:Math.max(0,Number(expected)-Number(artifact)),action:"Verify/backfill with idempotent server operation after DB reconciliation.",production_availability:"bundled canonical artifact + database overlay"}));
 return {pilot:{pilot_id:AMOR_PILOT_ID,tenant_id:null,client_id:AMOR_PILOT_ID,client_name:"Amor de Gea",slug:AMOR_PILOT_ID,production_status:"internal",status:"context_required",active_context_version:null,active_account_ids:ids,methodology_version:PILOT_WORKSPACE_VERSION,source_runs:[(block10 as any).generated_at,(block11 as any).generated_at,updated],created_at:(block10 as any).generated_at,updated_at:updated,last_intelligence_refresh:updated,last_human_review:null,readiness:"blocked_by_client_context",blockers:["10 critical client-context gaps","6 unreviewed theses","No current timing","0 customer-safe outputs"]},overview:{context_completeness:(block12 as any).summary.context_completeness,accounts:accounts.length,decisions:(block11 as any).summary.decisions,theses:accounts.length,reviewed:(block12 as any).summary.theses_reviewed,signals:0,timing_coverage:0,evidence_coverage:"Central commercial evidence remains incomplete.",critical_blockers:(block12 as any).summary.critical_blockers,customer_safe:(block12 as any).summary.customer_safe,report_ready:(block12 as any).summary.report_sections_ready,diagnosis:`${accounts.length} accounts have verified identities and internal theses. The pilot is blocked by unresolved client context, unreviewed theses and absent current timing.`,next_action:"Answer and submit the highest-priority critical client-context fields for Admin review."},questions:(block12 as any).questions,accounts,theses:(block11 as any).theses,feasibility:(block12 as any).feasibility,safety:(block12 as any).safety,sections:(block12 as any).sections,shortlist:(block12 as any).shortlist,activity,checklist,reconciliation:recon,availability:{canonical_artifacts:"available",database:"unverified",message:"Canonical artifacts are production-bundled; database overlay is optional and unavailable values remain explicit."},final_report_generation:"disabled",internal_only:true,ranking_impact:"off"};
}
export function dryRunPilotBackfill(workspace:PilotWorkspace){return {mode:"dry_run",writes:0,synthetic_answers:0,records:{pilot:1,accounts:workspace.accounts.length,theses:workspace.theses.length,questions:workspace.questions.length,safety:workspace.safety.length,sections:workspace.sections.length},idempotency_key:`pilot-backfill:${workspace.pilot.pilot_id}:${workspace.pilot.updated_at}`,actions:workspace.reconciliation.map(x=>({data_type:x.data_type,action:x.action}))}}
