"use client";
import { useCallback, useEffect, useState } from "react";
import AdminLayout from "@/app/admin/_components/AdminLayout";
import { adminFetch } from "@/lib/admin/admin-client";

type RuntimePayload = { checked_at: string; state: "available" | "degraded" | "unavailable"; reason: string | null; deployment: { commit: string | null; environment: string }; env: { database_configured: boolean; worker_configured: boolean; cron_configured: boolean }; runs: null | { sample_size: number; statuses: Record<string, number>; stale: number; p50_ms: number | null; p90_ms: number | null; p95_ms: number | null; failures: Array<{ code: string | null; stage: string }> }; monitor: null | { available: boolean; sample_size: number; statuses: Record<string, number>; p95_ms: number | null }; control_plane: null | { available: boolean; latest_observed_at?: string | null; source_data_cutoff?: string | null; error?: string | null } };
const ms = (value: number | null | undefined) => value == null ? "Not measured" : `${Math.round(value / 1000)}s`;
const Card = ({ label, value, note }: { label: string; value: string | number; note: string }) => <div style={{ background: "#fff", border: "1px solid #e2e8f0", borderRadius: 10, padding: 14 }}><div style={{ color: "#64748b", fontSize: ".68rem", fontWeight: 800, textTransform: "uppercase", letterSpacing: ".06em" }}>{label}</div><div style={{ color: "#0f172a", fontSize: "1.5rem", fontWeight: 900, margin: "5px 0" }}>{value}</div><div style={{ color: "#64748b", fontSize: ".72rem" }}>{note}</div></div>;
const State = ({ ok, label, detail }: { ok: boolean; label: string; detail: string }) => <div style={{ background: "#fff", border: "1px solid #e2e8f0", borderLeft: `4px solid ${ok ? "#15803d" : "#b45309"}`, borderRadius: 8, padding: 12 }}><strong style={{ fontSize: ".8rem" }}>{label}</strong><div style={{ color: "#64748b", fontSize: ".72rem", marginTop: 4 }}>{detail}</div></div>;

export default function RuntimeHealthPage() {
  const [data, setData] = useState<RuntimePayload | null>(null), [error, setError] = useState<string | null>(null), [loading, setLoading] = useState(true);
  const refresh = useCallback(async () => { setLoading(true); setError(null); try { const response = await adminFetch("/api/admin/system-health"); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Runtime telemetry unavailable"); setData(body); } catch (e) { setError(e instanceof Error ? e.message : "Runtime telemetry unavailable"); } finally { setLoading(false); } }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  return <AdminLayout><main style={{ maxWidth: 1080, margin: "0 auto" }}>
    <header style={{ display: "flex", justifyContent: "space-between", gap: 16, alignItems: "flex-start", marginBottom: 20 }}><div><span style={{ color: "#0284c7", fontSize: ".68rem", fontWeight: 800, letterSpacing: ".08em" }}>OPERATIONS · CANONICAL RUNTIME</span><h1 style={{ margin: "4px 0", fontSize: "1.5rem" }}>Runtime & Exceptions</h1><p style={{ color: "#64748b", fontSize: ".8rem", margin: 0 }}>Intelligence lifecycle, latency, stale recovery, Monitor and Control Plane availability. This is not a launch-readiness score.</p>{data && <p style={{ color: "#94a3b8", fontSize: ".68rem" }}>Build {data.deployment.commit?.slice(0, 12) ?? "unavailable"} · {data.deployment.environment} · checked {new Date(data.checked_at).toLocaleString()}</p>}</div><button onClick={() => void refresh()} disabled={loading} style={{ border: 0, borderRadius: 8, background: "#0f172a", color: "#fff", padding: ".6rem .9rem", fontWeight: 700 }}>{loading ? "Checking…" : "Refresh"}</button></header>
    {error && <div style={{ background: "#fef2f2", border: "1px solid #fecaca", padding: 12, borderRadius: 8, color: "#991b1b" }}>{error}</div>}
    {data && <>{data.state !== "available" && <div style={{ background: "#fffbeb", border: "1px solid #fde68a", padding: 12, borderRadius: 8, color: "#92400e", marginBottom: 16 }}><strong>Telemetry {data.state}.</strong> {data.reason}</div>}
      <section><h2 style={{ fontSize: ".95rem" }}>Intelligence runs</h2><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(160px,1fr))", gap: 10 }}><Card label="Observed runs" value={data.runs?.sample_size ?? "Unavailable"} note="Productive Intelligence Spine only"/><Card label="Processing" value={data.runs?.statuses.processing ?? 0} note="Queued, claimed or processing"/><Card label="Completed" value={data.runs?.statuses.completed ?? 0} note="Persisted completed runs"/><Card label="Failed" value={data.runs?.statuses.failed ?? 0} note="Inspect exceptions below"/><Card label="Stale" value={data.runs?.stale ?? "Unavailable"} note="Processing for more than 15 minutes"/><Card label="p95" value={ms(data.runs?.p95_ms)} note={`p50 ${ms(data.runs?.p50_ms)} · p90 ${ms(data.runs?.p90_ms)}`}/></div></section>
      <section style={{ marginTop: 22 }}><h2 style={{ fontSize: ".95rem" }}>Runtime controls</h2><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(230px,1fr))", gap: 10 }}><State ok={data.env.database_configured} label="Canonical database" detail={data.env.database_configured ? "Configured and queried by this endpoint." : "Unavailable."}/><State ok={data.env.worker_configured} label="Asynchronous worker" detail={data.env.worker_configured ? "Authenticated worker configured." : "Guided Admin pilots only; customer async execution is degraded."}/><State ok={data.control_plane?.available === true} label="Control Plane telemetry" detail={data.control_plane?.available ? `Latest ${data.control_plane.latest_observed_at ? new Date(data.control_plane.latest_observed_at).toLocaleString() : "unknown"}.` : "Snapshot store unavailable."}/><State ok={data.monitor?.available === true} label="Monitor runtime" detail={data.monitor?.available ? `${data.monitor.sample_size} persisted runs · p95 ${ms(data.monitor.p95_ms)}.` : "Monitor telemetry unavailable."}/></div></section>
      <section style={{ marginTop: 22 }}><h2 style={{ fontSize: ".95rem" }}>Recent exceptions</h2>{data.runs?.failures.length ? <ul style={{ background: "#fff", border: "1px solid #e2e8f0", borderRadius: 8, padding: "12px 30px", color: "#475569", fontSize: ".78rem" }}>{data.runs.failures.map((failure, index) => <li key={`${failure.stage}:${index}`}>{failure.stage}: {failure.code ?? "failure code unavailable"}</li>)}</ul> : <p style={{ color: "#64748b", fontSize: ".78rem" }}>No persisted Intelligence failure in the current sample.</p>}</section>
    </>}
  </main></AdminLayout>;
}
