import type { ProductCode } from "@/lib/products/catalog";

export type LandingLocale = "en" | "es" | "pt" | "ja";
type PlanCopy = { job: string; points: string[] };

export interface LandingV2Copy {
  skip: string; navigation: string; language: string; category: string; primary: string; secondary: string; synthetic: string;
  nav: { product: string; sample: string; pricing: string; how: string; signIn: string };
  hero: { title: string; lead: string; inputOutput: string };
  decisions: { prioritize: string; validate: string; monitor: string; hold: string };
  portfolio: { label: string; kicker: string; title: string; disclosure: string; company: string; why: string; decision: string; evidence: string; confirm: string };
  trust: { label: string; items: Array<{ title: string; body: string }> };
  outcomes: { eyebrow: string; title: string; body: string; items: Array<{ title: string; body: string }> };
  flow: { eyebrow: string; title: string; body: string; items: Array<{ title: string; body: string }> };
  interpretation: { eyebrow: string; title: string; body: string; label: string; example: string; action: string; loading: string; error: string; result: string; target: string; criteria: string; defaultSummary: string; defaultTarget: string; defaultCriteria: string[]; disclosure: string };
  case: { eyebrow: string; title: string; body: string; inspect: string; fact: string; factNote: string; analysis: string; thesis: string; inference: string; weakness: string; weaknessText: string; uncertainty: string; next: string; validationText: string; recommendation: string; full: string };
  audience: { eyebrow: string; title: string; items: string[] };
  pricing: { eyebrow: string; title: string; body: string; recommended: string; choose: string; compare: string; plans: Record<ProductCode, PlanCopy> };
  ongoing: { eyebrow: string; title: string; body: string; action: string };
  method: { eyebrow: string; title: string; body: string; items: string[] };
  faq: { eyebrow: string; title: string; items: Array<{ q: string; a: string }> };
  final: { title: string; body: string };
  footer: { privacy: string; terms: string; refund: string };
}

const en: LandingV2Copy = {
  skip: "Skip to content", navigation: "Main navigation", language: "Language", category: "Commercial Intelligence", primary: "Find where to focus", secondary: "View sample", synthetic: "Illustrative sample — synthetic companies and evidence.",
  nav: { product: "Product", sample: "Sample", pricing: "Pricing", how: "How it works", signIn: "Sign in" },
  hero: { title: "Know which companies deserve your attention — and why.", lead: "LeadLens researches and compares companies so you can focus commercial effort where it can contribute most to growth — with evidence behind every decision and uncertainty kept visible.", inputOutput: "Your commercial objective in. A prioritized, evidence-backed company portfolio out." },
  decisions: { prioritize: "Prioritize", validate: "Validate", monitor: "Monitor", hold: "Hold" },
  portfolio: { label: "Illustrative executive portfolio", kicker: "Executive portfolio", title: "Where attention is justified", disclosure: "3 companies evaluated", company: "Company", why: "Recent development and evidence", decision: "Attention", evidence: "Evidence", confirm: "Confirm" },
  trust: { label: "How LeadLens earns trust", items: [
    { title: "Evidence you can inspect", body: "See the dated public basis behind each case." },
    { title: "Uncertainty stays visible", body: "Know what weakens the case and what remains unknown." },
    { title: "A decision, not a contact list", body: "Focus on where investigation is worth your team's time." },
  ] },
  outcomes: { eyebrow: "What LeadLens does", title: "From a broad market to a clearer decision.", body: "LeadLens reduces the work between knowing who exists and deciding where to focus.", items: [
    { title: "Find the companies that matter", body: "Research a defined set or identify relevant companies from your commercial objective." },
    { title: "Understand why now", body: "Connect recent public developments to your offer without treating signals as buying intent." },
    { title: "Know what to verify next", body: "See the evidence, uncertainty and next validation before your team acts." },
  ] },
  flow: { eyebrow: "How it works", title: "Three steps from context to attention.", body: "The research is sophisticated. The customer journey should not be.", items: [
    { title: "Tell us what you're looking for", body: "Describe your offer, commercial objective, market and any companies or exclusions that matter." },
    { title: "LeadLens researches and evaluates", body: "It investigates relevant companies, checks recent developments and tests each case against your context." },
    { title: "See where to focus and why", body: "Receive a compared portfolio with evidence, uncertainty and a practical next step for every company." },
  ] },
  interpretation: { eyebrow: "Company interpretation", title: "Show LeadLens what a useful company looks like.", body: "Describe your business and objective. LeadLens turns your words into a compact research brief before any external research begins.", label: "What do you sell, to whom, and what are you trying to achieve?", example: "We provide supply-chain planning software to mid-sized manufacturers and want to identify companies where new facilities, acquisitions or operational expansion create a reason to engage.", action: "Interpret my context", loading: "Interpreting…", error: "We could not interpret that context. Try again.", result: "LeadLens read", target: "Likely company type", criteria: "Developments to investigate", defaultSummary: "Supply-chain planning software", defaultTarget: "Mid-sized manufacturers", defaultCriteria: ["New facilities", "Acquisitions or integration", "Operational capacity expansion"], disclosure: "Based only on this description. No company research has run yet." },
  case: { eyebrow: "One company, inspected", title: "See the reasoning behind the recommendation.", body: "Open one concise case to separate the observed fact from the commercial interpretation and its limits.", inspect: "Inspect case", fact: "Verified development", factNote: "Observed fact in the illustrative evidence set.", analysis: "Commercial interpretation", thesis: "Northstar is building out regional distribution — plausibly widening supplier and tooling needs before procurement is formalized.", inference: "An inference, not confirmed buying intent.", weakness: "What weakens the case", weaknessText: "Procurement ownership is not confirmed — the buying decision may sit at group level.", uncertainty: "Decision-relevant uncertainty.", next: "What to validate", validationText: "Confirm whether regional purchasing is centralized before outreach.", recommendation: "Recommended next action.", full: "View full sample" },
  audience: { eyebrow: "Designed for focused commercial teams", title: "Useful when every account requires judgment.", items: ["Specialized consultancies and professional services", "Founder-led or lean B2B sales and business development", "Selected agencies and partnership teams pursuing high-value companies"] },
  pricing: { eyebrow: "One-time analysis", title: "Choose the decision you need to make.", body: "The standard of truth never changes. Move up when you need a broader decision, stronger comparison or a portfolio view — not simply more names.", recommended: "Recommended", choose: "Choose", compare: "Compare all plans", plans: {
    preview_launch_v0: { job: "Decide which company deserves attention first.", points: ["Compare two complete company cases", "Inspect evidence, uncertainty and the next validation", "Leave with one clear focus"] },
    brief_launch_v0: { job: "Turn a shortlist into a clear next focus.", points: ["Compare the cases that justify attention", "See what supports and weakens each one", "Prioritize the next validation"] },
    intelligence_launch_v0: { job: "Allocate attention across a commercial portfolio.", points: ["Rank the portfolio, not just individual companies", "Compare patterns, risks and evidence side by side", "Export a structured decision set"] },
    premium_launch_v0: { job: "See the commercial context that could change the decision.", points: ["Reveal portfolio patterns and relevant alternatives", "Focus on decision-critical briefs and open questions", "Know what to validate next across the broadest accepted scope"] },
  } },
  ongoing: { eyebrow: "Ongoing intelligence", title: "Keep watching after the one-time picture.", body: "When priorities need to stay current, LeadLens can revisit known companies, retain account memory and surface material changes over time.", action: "Explore ongoing plans" },
  method: { eyebrow: "Account Opportunity Intelligence methodology", title: "Facts, inference and limitations stay separate.", body: "LeadLens does not claim to know buying intent. It organizes public evidence into a case your team can inspect instead of asking you to trust an opaque score.", items: ["Dated public sources where available", "No static contact database or email list", "Uncertainty and weakening evidence shown", "Synthetic examples labeled clearly"] },
  faq: { eyebrow: "Questions", title: "What to know before you start", items: [
    { q: "What do I receive?", a: "A one-time portfolio of evaluated companies, with a recommendation, evidence, uncertainty and next validation for each." },
    { q: "Do you provide contacts or email lists?", a: "No. LeadLens helps decide which companies deserve investigation; it is not a contact database or outreach tool." },
    { q: "What if no company is strong enough?", a: "LeadLens does not fill a quota with weak cases. The report explains what was investigated and why the current result should be refined, monitored or stopped." },
    { q: "Is a recommendation proof of buying intent?", a: "No. It is an evidence-backed reason to allocate attention, with explicit conditions your team should validate." },
  ] },
  final: { title: "Spend your next hour on the right companies.", body: "Start with a bounded analysis or inspect the sample before deciding." },
  footer: { privacy: "Privacy", terms: "Terms", refund: "Refund policy" },
};

const es: LandingV2Copy = {
  ...en, skip: "Saltar al contenido", navigation: "Navegación principal", language: "Idioma", category: "Inteligencia comercial", primary: "Encuentra dónde enfocarte", secondary: "Ver muestra", synthetic: "Muestra ilustrativa — empresas y evidencia sintéticas.",
  nav: { product: "Producto", sample: "Muestra", pricing: "Precios", how: "Cómo funciona", signIn: "Ingresar" },
  hero: { title: "Descubre qué empresas merecen tu atención — y por qué.", lead: "LeadLens investiga y compara empresas para que enfoques el esfuerzo comercial donde más puede contribuir al crecimiento, con evidencia detrás de cada decisión y la incertidumbre siempre visible.", inputOutput: "Entra tu objetivo comercial. Sale un portafolio priorizado con evidencia." },
  decisions: { prioritize: "Priorizar", validate: "Validar", monitor: "Monitorear", hold: "Reservar" },
  portfolio: { label: "Portafolio ejecutivo ilustrativo", kicker: "Portafolio ejecutivo", title: "Dónde se justifica la atención", disclosure: "3 empresas evaluadas", company: "Empresa", why: "Cambio reciente y evidencia", decision: "Atención", evidence: "Evidencia", confirm: "Confirmar" },
  trust: { label: "Cómo genera confianza LeadLens", items: [{ title: "Evidencia que puedes revisar", body: "Consulta la base pública y fechada detrás de cada caso." }, { title: "La incertidumbre sigue visible", body: "Entiende qué debilita el caso y qué sigue sin conocerse." }, { title: "Una decisión, no una lista", body: "Enfócate donde investigar merece el tiempo de tu equipo." }] },
  outcomes: { eyebrow: "Qué hace LeadLens", title: "De un mercado amplio a una decisión más clara.", body: "LeadLens reduce el trabajo entre saber quién existe y decidir dónde enfocarse.", items: [{ title: "Encuentra las empresas relevantes", body: "Investiga un conjunto definido o identifica empresas desde tu objetivo comercial." },{ title: "Entiende por qué ahora", body: "Conecta cambios públicos recientes con tu oferta sin tratarlos como intención de compra." },{ title: "Sabe qué debes validar después", body: "Revisa evidencia, incertidumbre y la siguiente validación antes de actuar." }] },
  flow: { eyebrow: "Cómo funciona", title: "Tres pasos del contexto a la atención.", body: "La investigación es sofisticada. La experiencia no tiene que serlo.", items: [{ title: "Cuéntanos qué buscas", body: "Describe tu oferta, objetivo, mercado y las empresas o exclusiones importantes." },{ title: "LeadLens investiga y evalúa", body: "Investiga empresas relevantes, verifica cambios recientes y prueba cada caso contra tu contexto." },{ title: "Decide dónde enfocarte y por qué", body: "Recibe un portafolio comparado con evidencia, incertidumbre y una siguiente acción." }] },
  interpretation: { ...en.interpretation, eyebrow: "Interpretación comercial", title: "Muéstrale a LeadLens cómo luce una empresa útil.", body: "Describe tu negocio y objetivo. LeadLens convierte tus palabras en un brief de investigación antes de consultar fuentes externas.", label: "¿Qué vendes, a quién y qué quieres lograr?", action: "Interpretar mi contexto", loading: "Interpretando…", error: "No pudimos interpretar el contexto. Inténtalo de nuevo.", result: "Lectura de LeadLens", target: "Tipo de empresa probable", criteria: "Cambios a investigar", defaultSummary: "Software de planificación de supply chain", defaultTarget: "Fabricantes medianos", defaultCriteria: ["Nuevas instalaciones", "Adquisición o integración", "Expansión de capacidad operativa"], disclosure: "Basado solo en esta descripción. Aún no se investigaron empresas." },
  case: { ...en.case, eyebrow: "Una empresa, examinada", title: "Revisa el razonamiento detrás de la recomendación.", body: "Abre un caso conciso que separa el hecho observado de la interpretación comercial y sus límites.", inspect: "Revisar caso", fact: "Cambio verificado", factNote: "Hecho observado en la evidencia ilustrativa.", analysis: "Interpretación comercial", thesis: "Northstar está ampliando su distribución regional, lo que podría aumentar necesidades de proveedores y herramientas antes de formalizar compras.", inference: "Inferencia, no intención de compra confirmada.", weakness: "Qué debilita el caso", weaknessText: "No está confirmada la propiedad de compras; la decisión puede estar en la matriz.", uncertainty: "Incertidumbre relevante para decidir.", next: "Qué validar", validationText: "Confirmar si las compras regionales están centralizadas antes del contacto.", recommendation: "Siguiente acción recomendada.", full: "Ver muestra completa" },
  audience: { eyebrow: "Para equipos comerciales enfocados", title: "Útil cuando cada empresa exige criterio.", items: ["Consultoras especializadas y servicios profesionales", "Ventas B2B y desarrollo de negocio con equipos pequeños", "Agencias seleccionadas y equipos de alianzas con cuentas de alto valor"] },
  pricing: { eyebrow: "Análisis de una sola vez", title: "Elige la decisión que necesitas tomar.", body: "El estándar de verdad no cambia. Sube de nivel cuando necesites una decisión más amplia, mejor comparación o una vista de portafolio, no solo más nombres.", recommended: "Recomendado", choose: "Elegir", compare: "Comparar todos los planes", plans: {
    preview_launch_v0: { job: "Decide qué empresa merece atención primero.", points: ["Compara dos casos completos", "Revisa evidencia, incertidumbre y próxima validación", "Sal con un foco claro"] },
    brief_launch_v0: { job: "Convierte una lista corta en el próximo foco.", points: ["Compara los casos que justifican atención", "Ve qué sostiene y debilita cada uno", "Prioriza la próxima validación"] },
    intelligence_launch_v0: { job: "Asigna atención en un portafolio comercial.", points: ["Ordena el portafolio, no solo empresas aisladas", "Compara patrones, riesgos y evidencia", "Exporta un conjunto estructurado de decisiones"] },
    premium_launch_v0: { job: "Entiende el contexto comercial que puede cambiar la decisión.", points: ["Revela patrones del portafolio y alternativas relevantes", "Enfoca briefs críticos y preguntas abiertas", "Sabe qué validar después en el mayor alcance aceptado"] },
  } },
  ongoing: { eyebrow: "Inteligencia continua", title: "Sigue observando después de la foto inicial.", body: "Cuando las prioridades deben mantenerse vigentes, LeadLens revisa empresas conocidas, conserva memoria y detecta cambios materiales.", action: "Explorar planes continuos" },
  method: { eyebrow: "Metodología de Account Opportunity Intelligence", title: "Hechos, inferencias y limitaciones permanecen separados.", body: "LeadLens no afirma conocer la intención de compra. Organiza evidencia pública en un caso que tu equipo puede revisar, sin pedirte que confíes en un puntaje opaco.", items: ["Fuentes públicas fechadas cuando existen", "Sin base estática de contactos o correos", "Incertidumbre y evidencia que debilita visibles", "Ejemplos sintéticos claramente etiquetados"] },
  faq: { eyebrow: "Preguntas", title: "Qué debes saber antes de comenzar", items: [{ q: "¿Qué recibo?", a: "Un portafolio de empresas evaluadas con recomendación, evidencia, incertidumbre y siguiente validación." }, { q: "¿Entregan contactos o listas de correos?", a: "No. LeadLens ayuda a decidir qué empresas merecen investigación; no es una base de contactos ni una herramienta de outreach." }, { q: "¿Qué ocurre si ninguna empresa es suficientemente fuerte?", a: "LeadLens no rellena cupos con casos débiles. El reporte explica qué se investigó y por qué conviene refinar, monitorear o detener." }, { q: "¿Una recomendación demuestra intención de compra?", a: "No. Es una razón respaldada por evidencia para asignar atención, con condiciones explícitas que tu equipo debe validar." }] },
  final: { title: "Dedica tu próxima hora a las empresas correctas.", body: "Comienza con un análisis acotado o revisa la muestra antes de decidir." },
  footer: { privacy: "Privacidad", terms: "Términos", refund: "Política de reembolso" },
};

const pt: LandingV2Copy = {
  ...en, skip: "Ir para o conteúdo", navigation: "Navegação principal", language: "Idioma", category: "Inteligência comercial", primary: "Encontrar onde focar", secondary: "Ver amostra", synthetic: "Amostra ilustrativa — empresas e evidências sintéticas.",
  nav: { product: "Produto", sample: "Amostra", pricing: "Preços", how: "Como funciona", signIn: "Entrar" },
  hero: { title: "Saiba quais empresas merecem sua atenção — e por quê.", lead: "A LeadLens pesquisa e compara empresas para concentrar o esforço comercial onde ele pode contribuir mais para o crescimento, mantendo evidências e incertezas visíveis.", inputOutput: "Seu objetivo comercial entra. Um portfólio priorizado com evidências sai." },
  decisions: { prioritize: "Priorizar", validate: "Validar", monitor: "Monitorar", hold: "Manter" },
  portfolio: { ...en.portfolio, label: "Portfólio executivo ilustrativo", kicker: "Portfólio executivo", title: "Onde a atenção se justifica", disclosure: "3 empresas avaliadas", company: "Empresa", why: "Mudança recente e evidência", decision: "Atenção", evidence: "Evidência", confirm: "Confirmar" },
  trust: { label: "Como a LeadLens gera confiança", items: [{ title: "Evidência verificável", body: "Veja a base pública e datada de cada caso." }, { title: "Incerteza visível", body: "Saiba o que enfraquece o caso e o que permanece desconhecido." }, { title: "Uma decisão, não uma lista", body: "Foque onde a investigação merece o tempo da equipe." }] },
  outcomes: { ...en.outcomes, eyebrow: "O que a LeadLens faz", title: "De um mercado amplo a uma decisão mais clara.", body: "A LeadLens reduz o trabalho entre saber quem existe e decidir onde focar.", items: [{ title: "Encontre as empresas relevantes", body: "Pesquise um conjunto definido ou identifique empresas a partir do objetivo comercial." },{ title: "Entenda por que agora", body: "Conecte mudanças públicas recentes à sua oferta sem tratá-las como intenção de compra." },{ title: "Saiba o que validar", body: "Veja evidências, incertezas e a próxima validação antes de agir." }] },
  flow: { ...en.flow, eyebrow: "Como funciona", title: "Três passos do contexto à atenção.", body: "A pesquisa é sofisticada. A jornada não precisa ser.", items: [{ title: "Conte o que procura", body: "Descreva oferta, objetivo, mercado e empresas ou exclusões relevantes." },{ title: "A LeadLens pesquisa e avalia", body: "Investiga empresas, verifica mudanças e testa cada caso no seu contexto." },{ title: "Veja onde focar e por quê", body: "Receba um portfólio comparado com evidências, incertezas e próximo passo." }] },
  interpretation: { ...en.interpretation, eyebrow: "Interpretação comercial", title: "Mostre à LeadLens como é uma empresa útil.", body: "Descreva negócio e objetivo. A LeadLens transforma suas palavras em um brief antes de pesquisar fontes externas.", label: "O que você vende, para quem e o que quer alcançar?", action: "Interpretar meu contexto", loading: "Interpretando…", error: "Não foi possível interpretar. Tente novamente.", result: "Leitura da LeadLens", target: "Tipo provável de empresa", criteria: "Mudanças a pesquisar", defaultSummary: "Software de planejamento da cadeia de suprimentos", defaultTarget: "Fabricantes de médio porte", defaultCriteria: ["Novas instalações", "Aquisições ou integração", "Expansão da capacidade operacional"], disclosure: "Baseado apenas nesta descrição. Nenhuma empresa foi pesquisada ainda." },
  case: { ...en.case, eyebrow: "Uma empresa, examinada", title: "Veja o raciocínio por trás da recomendação.", body: "Abra um caso conciso que separa o fato da interpretação e dos limites.", inspect: "Examinar caso", fact: "Mudança verificada", factNote: "Fato observado no conjunto ilustrativo.", analysis: "Interpretação comercial", thesis: "A Northstar está ampliando a distribuição regional, o que pode aumentar necessidades de fornecedores antes da compra ser formalizada.", inference: "Inferência, não intenção de compra confirmada.", weakness: "O que enfraquece o caso", weaknessText: "A responsabilidade por compras não está confirmada; a decisão pode estar no grupo.", uncertainty: "Incerteza relevante.", next: "O que validar", validationText: "Confirmar se as compras regionais são centralizadas antes do contato.", recommendation: "Próxima ação recomendada.", full: "Ver amostra completa" },
  audience: { eyebrow: "Para equipes comerciais focadas", title: "Útil quando cada empresa exige julgamento.", items: ["Consultorias especializadas e serviços profissionais", "Vendas B2B e desenvolvimento de negócios com equipes enxutas", "Agências e equipes de parcerias que buscam contas de alto valor"] },
  pricing: { eyebrow: "Análise única", title: "Escolha o tamanho da decisão.", body: "Todos os níveis usam o mesmo padrão de verdade. Níveis superiores adicionam amplitude e comparação, não fatos melhores.", recommended: "Recomendado", choose: "Escolher", compare: "Comparar todos os planos", plans: {
    preview_launch_v0: { job: "Teste a LeadLens numa decisão compacta de duas empresas.", points: ["Uma recomendação por empresa", "Evidência e incerteza", "Relatório web e PDF"] }, brief_launch_v0: { job: "Avalie uma lista focada de seis empresas.", points: ["Casos comparáveis", "O que sustenta e enfraquece cada caso", "Relatório web e PDF"] }, intelligence_launch_v0: { job: "Priorize um portfólio de doze empresas.", points: ["Portfólio ordenado", "Comparação lado a lado", "Casos completos e CSV"] }, premium_launch_v0: { job: "Entenda o contexto comercial que pode mudar a decisão.", points: ["Padrões do portfólio e alternativas relevantes", "Briefs críticos e questões em aberto", "O que validar no maior escopo aceito"] },
  } },
  ongoing: { eyebrow: "Inteligência contínua", title: "Continue observando depois da análise inicial.", body: "Quando as prioridades precisam ficar atuais, a LeadLens revisita empresas conhecidas, mantém memória e identifica mudanças materiais.", action: "Explorar planos contínuos" },
  method: { eyebrow: "Metodologia de Account Opportunity Intelligence", title: "Fatos, inferências e limitações permanecem separados.", body: "A LeadLens não afirma conhecer intenção de compra. Ela organiza evidências públicas em um caso verificável, sem exigir confiança numa pontuação opaca.", items: ["Fontes públicas datadas quando disponíveis", "Sem banco estático de contatos ou e-mails", "Incerteza e evidência contrária visíveis", "Exemplos sintéticos claramente identificados"] },
  faq: { eyebrow: "Perguntas", title: "O que saber antes de começar", items: [{ q: "O que recebo?", a: "Um portfólio de empresas avaliadas com recomendação, evidência, incerteza e próxima validação." }, { q: "Vocês fornecem contatos ou listas de e-mail?", a: "Não. A LeadLens ajuda a decidir quais empresas merecem investigação; não é um banco de contatos." }, { q: "E se nenhuma empresa for forte o suficiente?", a: "A LeadLens não preenche cotas com casos fracos. O relatório explica o que foi investigado e por que refinar, monitorar ou parar." }, { q: "Uma recomendação prova intenção de compra?", a: "Não. É uma razão apoiada por evidências para alocar atenção, com condições que sua equipe deve validar." }] },
  final: { title: "Use sua próxima hora nas empresas certas.", body: "Comece com uma análise limitada ou veja a amostra antes de decidir." },
  footer: { privacy: "Privacidade", terms: "Termos", refund: "Política de reembolso" },
};

const ja: LandingV2Copy = {
  ...en, skip: "本文へ移動", navigation: "メインナビゲーション", language: "言語", category: "コマーシャルインテリジェンス", primary: "注力先を見つける", secondary: "サンプルを見る", synthetic: "説明用サンプル — 企業と根拠は合成データです。",
  nav: { product: "製品", sample: "サンプル", pricing: "料金", how: "仕組み", signIn: "ログイン" },
  hero: { title: "今、注目すべき企業と、その理由を明確に。", lead: "LeadLensは企業を調査・比較し、成長につながる商業活動の注力先を、根拠と不確実性を明示して示します。", inputOutput: "商業目標を入力。優先順位と根拠を備えた企業ポートフォリオを出力。" },
  decisions: { prioritize: "優先", validate: "検証", monitor: "監視", hold: "保留" },
  portfolio: { ...en.portfolio, label: "例示エグゼクティブポートフォリオ", kicker: "エグゼクティブポートフォリオ", title: "注目が正当化される企業", disclosure: "3社を評価", company: "企業", why: "最近の変化と根拠", decision: "判断", evidence: "根拠", confirm: "確認" },
  trust: { label: "LeadLensの信頼性", items: [{ title: "確認できる根拠", body: "各ケースの公開情報と日付を確認できます。" }, { title: "不確実性を明示", body: "ケースを弱める要因と未知の点を示します。" }, { title: "リストではなく判断", body: "調査する価値のある企業に集中できます。" }] },
  outcomes: { ...en.outcomes, eyebrow: "LeadLensがすること", title: "広い市場から、明確な判断へ。", body: "企業の存在を知ることと、注力先を決めることの間の作業を減らします。", items: [{ title: "重要な企業を見つける", body: "指定した企業群、または商業目標から関連企業を調査します。" },{ title: "なぜ今かを理解する", body: "公開情報の変化を、購買意向と断定せずに提案内容と結びつけます。" },{ title: "次に何を確認するか", body: "根拠、不確実性、次の検証事項を確認してから行動できます。" }] },
  flow: { ...en.flow, eyebrow: "仕組み", title: "文脈から注目先まで、3つのステップ。", body: "調査は高度でも、顧客体験はシンプルに。", items: [{ title: "探している企業像を伝える", body: "提案、目標、市場、重要な企業や除外条件を説明します。" },{ title: "LeadLensが調査・評価", body: "関連企業、最近の変化、顧客文脈との適合を検証します。" },{ title: "注力先と理由を見る", body: "比較、根拠、不確実性、次の行動を含むポートフォリオを受け取ります。" }] },
  interpretation: { ...en.interpretation, eyebrow: "商業文脈の解釈", title: "有望な企業像をLeadLensに伝える。", body: "事業と目標を説明すると、外部調査の前に簡潔な調査方針へ変換します。", label: "何を、誰に販売し、何を達成したいですか？", action: "文脈を解釈", loading: "解釈中…", error: "解釈できませんでした。もう一度お試しください。", result: "LeadLensの読み取り", target: "想定企業タイプ", criteria: "調査する変化", defaultSummary: "サプライチェーン計画ソフトウェア", defaultTarget: "中規模メーカー", defaultCriteria: ["新しい施設", "買収または統合", "業務能力の拡大"], disclosure: "この説明のみに基づきます。企業調査はまだ行われていません。" },
  case: { ...en.case, eyebrow: "1社を詳しく確認", title: "推奨の根拠を確認する。", body: "観測事実、商業的解釈、限界を分けて表示します。", inspect: "ケースを確認", fact: "確認された変化", factNote: "説明用の根拠で観測された事実。", analysis: "商業的解釈", thesis: "Northstarは地域配送を拡大しており、調達確定前に供給業者やツールの需要が広がる可能性があります。", inference: "推論であり、購買意向の確認ではありません。", weakness: "ケースを弱める要因", weaknessText: "調達責任者は未確認で、判断がグループ本社にある可能性があります。", uncertainty: "判断に関わる不確実性。", next: "確認事項", validationText: "接触前に地域調達が一元管理されているか確認する。", recommendation: "推奨される次の行動。", full: "完全なサンプルを見る" },
  audience: { eyebrow: "集中型の営業チーム向け", title: "一社ごとに判断が必要なときに。", items: ["専門コンサルティングとプロフェッショナルサービス", "少人数のB2B営業・事業開発チーム", "高価値企業を追う代理店・提携チーム"] },
  pricing: { eyebrow: "一度きりの分析", title: "判断の規模を選ぶ。", body: "すべてのプランで同じ真実性基準を使用します。上位プランは範囲と比較を増やしますが、事実の質は変えません。", recommended: "おすすめ", choose: "選択", compare: "全プランを比較", plans: {
    preview_launch_v0: { job: "2社のコンパクトな判断でLeadLensを試す。", points: ["各社への推奨", "根拠と不確実性", "WebレポートとPDF"] }, brief_launch_v0: { job: "6社の候補リストを評価する。", points: ["比較可能なケース", "各ケースを支える点と弱める点", "WebレポートとPDF"] }, intelligence_launch_v0: { job: "12社のポートフォリオを優先順位付けする。", points: ["順位付きポートフォリオ", "並列比較", "完全なケースとCSV"] }, premium_launch_v0: { job: "判断を変えうる商業的文脈を確認する。", points: ["ポートフォリオのパターンと関連する代替案", "判断に重要なブリーフと未解決事項", "最大範囲で次に検証すべき点"] },
  } },
  ongoing: { eyebrow: "継続インテリジェンス", title: "一度きりの分析後も変化を追跡。", body: "優先順位を最新に保つ必要がある場合、既知の企業を再評価し、記憶を保持し、重要な変化を示します。", action: "継続プランを見る" },
  method: { eyebrow: "Account Opportunity Intelligence メソドロジー", title: "事実、推論、限界を分けて表示。", body: "LeadLensは購買意向を断定せず、不透明なスコアではなく確認可能なケースとして公開情報を整理します。", items: ["利用可能な場合は日付付き公開情報", "静的な連絡先・メールリストなし", "不確実性と弱める根拠を表示", "合成例を明確に表示"] },
  faq: { eyebrow: "質問", title: "開始前に知っておくこと", items: [{ q: "何を受け取れますか？", a: "評価済み企業のポートフォリオと、推奨、根拠、不確実性、次の確認事項を受け取ります。" }, { q: "連絡先やメールリストは提供しますか？", a: "いいえ。LeadLensは調査すべき企業の判断を支援するもので、連絡先データベースではありません。" }, { q: "十分に強い企業がない場合は？", a: "弱いケースで枠を埋めません。調査内容と、改善・監視・停止すべき理由を説明します。" }, { q: "推奨は購買意向の証明ですか？", a: "いいえ。チームが検証すべき条件を伴う、注目を割くための根拠です。" }] },
  final: { title: "次の1時間を、正しい企業に。", body: "限定分析を始めるか、まずサンプルをご覧ください。" },
  footer: { privacy: "プライバシー", terms: "利用規約", refund: "返金ポリシー" },
};

const COPY: Record<LandingLocale, LandingV2Copy> = { en, es, pt, ja };
export function getLandingV2Copy(locale: LandingLocale): LandingV2Copy { return COPY[locale]; }
